### ISSUE TITLE
Question appears differently and can't be edited in proposal template

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#1007]
Emma found that in the Artemis template, one of the multiple choice questions shows a different value when editing the question, and doesn't do anything when renamed.

This came up on a call with Emma Gozzard 20/02/2024.

---

1. Question shows "Direct Access"
<img src="https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/14293717/979314a9-e2aa-4888-a104-15101273efd6" width="230" height="300" />

2. If you click "Proposed_route_Artemis" to edit the question, the options shows "Direct Access - Continuation"
<img src="https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/14293717/df25468e-e67a-43f8-88af-b9c89eab99bf" width="230" height="300" />

3. If you rename the option and save, it looks like it works
<img src="https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/14293717/7e695d45-1109-4fc3-872b-e92142d3d2f1" width="280" height="150" />

4. The option still shows "Direct Access"
<img src="https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/14293717/979314a9-e2aa-4888-a104-15101273efd6" width="230" height="300" />

**Comment by ellen-wright** [comment]
Updates from sprint planning with ESS:
The question needs to be able to be edited without these changes effecting all templates the question is on, however, it is hard to tell if you are editing the question or if  you are editing just a specific template. 

We should make it more clear when you are editing the question and when you are editing the template by adding a heading on each page to indicate this.
