### ISSUE TITLE
Send STFC emails via proposal status actions

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#1011]
We have previously discussed that we should change how we send our emails to utilise the new [proposal status actions](https://github.com/UserOfficeProject/user-office-core/pull/298). This gives us more control over who receives emails at which point and means we can configure it via the interface.

Possible questions, issues or things to be mindful of:
- We may need to define the User Office as a new email recipient (i.e. for Rapid Access emails)
- Training/documentation/awareness for User Officers since it will need setting up with each new workflow
- We may want to BCC the Sink inbox with each sent email

---

Things needed before switching over (this may not be conclusive):

- [x] Add template names to code so that they are selectable in the frontend (via https://github.com/UserOfficeProject/user-office-core/pull/563).
- [x] Make the PI and Co-I available in all templates, so that we can reference them in any email (via https://github.com/UserOfficeProject/user-office-core/pull/563).
- [x] Update the email template placeholders to accomodate the changes in structure of data being passed in (see https://git.devs.facilities.rl.ac.uk/isisbusapps/BisAppSettings/pulls/453).
- [x] #1039
- [x] #1040
- [x] #1120
- [x] Investigate/check that emails work with the internal call workflow. There was an issue raised at the end of latest round about proposals not going into the correct status and a fix implemented in: https://github.com/UserOfficeProject/user-office-core/pull/605. Emails should still send on (re)submissions at any point but they should not duplicate when the workflow changes, etc.
- [x] Do the switchover. Remove the existing handler (it might need to stay for certain emails), configure workflows in frontend, ensure all calls that need different emails have their own workflows, merge (email https://git.devs.facilities.rl.ac.uk/isisbusapps/BisAppSettings/pulls/453), etc..
     - [x] Dev
     - [x] Prod

Things needed a bit further down the line:
- [x] Send an email on call creation. Not sure how we accomplish this with the proposal events, maybe we just keep using the existing handler - after discussion we agreed that this can stay in the existing handler.
- [x] #1041 - being handled by R&A
- [x] Training/documentation/awareness for User Officers. - to be raised at a Xpress demo with George, Nick, etc. and handled by them.

**Comment by zvailanu98** [comment]
https://github.com/UserOfficeProject/user-office-core/pull/563#issuecomment-2015937269

**Comment by mutambaraf** [comment]
Sprint planning: 09/07/2024 - List of stages where notifications can be send for each role and send to @Cat-Lucifer

**Comment by mutambaraf** [comment]
@Cat-Lucifer  As a follow up from our sprint planning, for every workflow event for example on ISIS Direct `PROPOSAL_SUBMITTED`, We have to set  notifications as show below but at the current moment we are only sending emails to pi and co-proposers when a proposal is submitted. I have attached screenshots for the user groups that we can send the notifications. 
![image](https://github.com/UserOfficeProject/issue-tracker/assets/71100224/acc0abfd-bf0f-40ca-8675-58be77ab8284)

![image](https://github.com/UserOfficeProject/issue-tracker/assets/71100224/1008b75b-173f-4ac7-8244-f56e1a9fdb22)

**Comment by simonfernandes** [comment]
Sprint planning notes:

Let's remove the email sent on call creation, we have a better handle on call dates now.

**Comment by mutambaraf** [comment]
@simonfernandes .We are triggering all events on a proposal so status actions will be executed on all stations actions when submitting a proposal when internal call is open. But do not understand this part `Emails should still send on (re)submissions at any point but they should not duplicate when the workflow changes, etc.`

**Comment by simonfernandes** [comment]
@mutambaraf What I meant by this is that if a proposal is submitted during the external call, when the workflow changes to internal it shouldn't send all of those emails again. And in the internal stage, all resubmissions should still trigger emails to confirm the changes.

**Comment by simonfernandes** [comment]
Sprint planning notes:

This has now been tested on dev and Xpress emails are working, but they are currently duplicated becasue of the existing handler. 

We can either:
- Switch all existing calls to use email status actions and then merge https://github.com/UserOfficeProject/user-office-core/pull/711
- Don't send any emails on the `PROPOSAL_SUBMITTED` event via status actions. These can be sent from the handler and avoid duplicate emails. If we do it this way, we won't have the ability to resend emails via the "replay status action" feature.

**Comment by simonfernandes** [comment]
Sprint planning notes:

Do a hotfix/release of the proposal system (which removes the emails send via the handler), but make sure we deactivate the email status actions so that we don't send duplicates. Release this together with the BisAppSettings configs. Then we can add email status actions to all calls.

**Comment by mutambaraf** [comment]
@Cat-Lucifer we have release status actions for emails and made changes to the following workflows .

1. ISIS Rapid workflow.
![image](https://github.com/user-attachments/assets/49ad7664-0be9-4f42-ad03-e87c0e7753f8)
2. HPL workflow.
![image](https://github.com/user-attachments/assets/1b74ee9b-91b5-422b-9bd1-5353131e0853)
3. LSF Workflow.
![image](https://github.com/user-attachments/assets/935ce2d2-5f9b-4505-8a16-c1856fbcfea2)
4. ISIS Direct workflow.
![image](https://github.com/user-attachments/assets/c52bcdff-3f48-41b9-a4b5-7529b6aba741)

**Comment by simonfernandes** [comment]
I think a couple of things need changing in the new setup:

1. ISIS Rapid submitted event emails should also send to the User Office recipient.
2. Combine recipient emails should be unticked everywhere so that we always send an email per proposal to a recipient. We don't support this in the email templates and we don't have a use case for combining them currently.

**Comment by mutambaraf** [comment]
> I think a couple of things need changing in the new setup:
> 
> 1. ISIS Rapid submitted event emails should also send to the User Office recipient.
> 2. Combine recipient emails should be unticked everywhere so that we always send an email per proposal to a recipient. We don't support this in the email templates and we don't have a use case for combining them currently.

Have updated as above.

**Comment by simonfernandes** [comment]
This is now complete with all of the above work.

**Comment by Cat-Lucifer** [comment]
@mutambaraf @simonfernandes Can I just check, does the above mean that anybody with the User Officer role will receive an email upon the submission of any ISIS, HPL and LSF proposal?

**Comment by simonfernandes** [comment]
@Cat-Lucifer Yes with those updated screenshots it looks like we're accidentally spamming you! We should only be sending the User Office an email for ISIS Rapid submissions, right? It doesn't work on role, the `USER_OFFICE` recipient is configured to send to your email address and the isisuo address.

**Comment by Cat-Lucifer** [comment]
@simonfernandes Yes, please only send proposal submission emails to myself and the UO for Rapid Access.

**Comment by simonfernandes** [comment]
@Cat-Lucifer We've updated the workflows now
