### ISSUE TITLE
Query end point with missing field

### ISSUE THREAD

**Issue by YufanKambang** [UserOfficeProject/user-office-project-issue-tracker#1016]
we are experiencing this issue: https://logs.devs.facilities.rl.ac.uk/app/discover#/doc/7e1733e0-d283-11ea-856e-3dc8c807c0b0/kubernetes-bisappslogs-7.13.2-2024.02.29?id=YByo8o0BmDwNftjbrVLK 

it is attempting to call a field that no longer exist. We have changed organisation to institution: https://github.com/UserOfficeProject/user-office-core/pull/468/files

Think about and include, if relevant:
 - Who does this affect?
the users, i dont really understand the type of error and what effect it has
 - What needs to change?l
need to check https://github.com/isisbusapps/proposal-lookup/blob/develop/proposal-lookup/proposal-lookup-ejb/src/main/resources/proposal/submission/schema.graphqls and change any existing "organisation" into "institution" to match the PR.
 - What events does this affect?
I do not know, believe will keep giving us error logs that does not represent a functional error
 - Why does it need to change?
so that we do not receive the error log, and so that user does not get an error. Code is consistent and actually searches for a field that exists
 - Who requested it and when?
submission stand up by the team, on 29/02/2024
-->

**Comment by mutambaraf** [comment]
These release might solve this issue: https://github.com/isisbusapps/proposal-lookup/pull/104

**Comment by YufanKambang** [comment]
I believe it has :)
