### ISSUE TITLE
Whitespace in proposal answers can cause empty space and blank pages in PDF

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#1017]
If certain proposal questions are shown in the proposal PDF, and the user has added a lot of whitespace to the answer, the proposal PDF displays all of that whitespace.

We could restrict the characters a user can enter, but if we don't want to do that we may want to trim any trailing whitespace.

The examples we saw were in proposals 2410381 and 2410485, where the same user had entered a considerable amount of whitespace when answering what their sample properties were.

The question key is `sample_properties` and the custom PDF template affected was `ISIS Direct`. We may want to check if this also affects the default template (where more questions are printed), and if there are any other questions that we want to apply a fix to.

Related to https://github.com/UserOfficeProject/issue-tracker/issues/959.

**Comment by bashanlam** [comment]
Update the field to single line text.

**Comment by Cat-Lucifer** [comment]
Please also apply to `chemical_formula` Q

**Comment by Cat-Lucifer** [comment]
![image](https://github.com/UserOfficeProject/issue-tracker/assets/108054517/402076fe-8b68-4eac-981b-d9f32fba67a1)

**Comment by Cat-Lucifer** [comment]
@deepaksftc Yes, we should definitely avoid making any changes to questions, that affect answers, while the call is open.  I say we do nothing for this call, and discuss options when it has closed (22 April).  It might be worth speaking with the R&A team too, as they are also working on a very similar issue.

**Comment by Cat-Lucifer** [comment]
@deepaksftc I have had a random look at a quite a few proposals, and I think setting the character limit to 50 characters will be fine.  We can see how that goes during the next round and reassess if needed.  Thanks

**Comment by deepaksftc** [comment]
@Cat-Lucifer, I did some testing in local and it looks like changing the character limit for these fields in ISIS Samples sub template is not impacting the already submitted proposals (loading or pdf downloads). So, I am planning to set the character limit in production, if its fine for you?

**Comment by Cat-Lucifer** [comment]
@deepaksftc Sounds good to me.  Thanks!
