### ISSUE TITLE
Make changes to dev and prod environmental variables.

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#1018]
### What is the problem and why is it a problem
As part of these [changes](https://github.com/UserOfficeProject/user-office-core/pull/548) we need to make changes to : 

- [ ] Docker orchestration docker composer file on backend environmental variables.
- [ ] Local .env secrete in busapp settings . 
- [ ] kubernetes deployment on backend environmental variables.

**Comment by deepaksftc** [comment]
Note: Need to wait for this PR https://github.com/UserOfficeProject/user-office-core/pull/548 to be completed and reviewed.
