### ISSUE TITLE
Modify end of year queries to work with the new database for ISIS Direct

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#102]
Split from #78 

Requires #77 and #85 

This is to move all of the queries at the end of the financial year (1st April 2023) that use the proposals database to the new database.

Issues with this:
 - query performance
 - difficulties with IDs or questions changing
 - significant proposal schema differences
 - handle old proposal and new proposal data (within limits)

/overwrite opened 2020-09-04

**Comment by simonfernandes** [comment]
Queries identified as being needed for FAPs: [FAP Queries.xlsx](https://github.com/UserOfficeProject/user-office-project-issue-tracker/files/9281750/FAP.Queries.xlsx)

**Comment by simonfernandes** [comment]
Closing, new issues will be created to more clearly cover all ISIS reporting.
