### ISSUE TITLE
As an Xpress scientist, I need a way to manage my Xpress proposals

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#1027]
We need an area for Xpress scientists to manage their Xpress proposals. Features needed include:

- [ ] https://github.com/UserOfficeProject/issue-tracker/issues/1139
- [ ] https://github.com/UserOfficeProject/issue-tracker/issues/1096
- [ ] https://github.com/UserOfficeProject/issue-tracker/issues/1140
- [ ] https://github.com/UserOfficeProject/issue-tracker/issues/1031
- [ ] https://github.com/UserOfficeProject/issue-tracker/issues/1137
- [ ] https://github.com/UserOfficeProject/issue-tracker/issues/1138
- [ ] https://github.com/UserOfficeProject/issue-tracker/issues/1028

See https://github.com/UserOfficeProject/issue-tracker/issues/1079 for how permissions should work

**Comment by mutambaraf** [comment]
We also need to define what proposals a particular scientist need to manage probably by technique. Away day 22/05/2024.

**Comment by mutambaraf** [comment]
Were will this be hosted, the assumption is that this will be in the new proposal system. Away day 2024.

**Comment by simonfernandes** [comment]
We need to consider whether scientists need to make a selection and/or sorting of proposals for https://github.com/UserOfficeProject/issue-tracker/issues/1028 (exporting proposals) when designing the management page.

**Comment by simonfernandes** [comment]
Also see Fredrik's suggestion in https://github.com/UserOfficeProject/issue-tracker/discussions/1032#discussioncomment-9752530 where he suggests using the existing technical and management pages.

**Comment by simonfernandes** [comment]
Closing this in favour of keeping track of management issues via the project board tab
