### ISSUE TITLE
As an Xpress scientist, I need a way to manage my sample cans through comments

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#1031]
Sample safety need to manage their sample cans via a proposal's comments. The comments should not be shown to the user.

**Comment by mutambaraf** [comment]
This will be through the notes field. Away day 22/05/2024

**Comment by simonfernandes** [comment]
@Cat-Lucifer Will a single text box be adequate for scientists to keep track of their samples, so long as it can handle enough characters?

**Comment by Cat-Lucifer** [comment]
@simonfernandes Yes, I think will be fine

**Comment by mutambaraf** [comment]
@Cat-Lucifer .We can go up to 50 characters in the database will this be sufficient.

**Comment by simonfernandes** [comment]
@mutambaraf Sorry both, I forgot to note down what was mentioned on a call with Emma and Deepak.

We said that having an expandable section for each proposal row where the scientist would have a large area (I think definitely more than 50 chars!) to write comments would be a good idea. I don't know exactly what this would look like or how it would function, but we spoke about having something akin to this, but with a section for comments:

![image](https://github.com/user-attachments/assets/71f6ce23-a61a-4a24-886d-e167bd7c697e)

**Comment by mutambaraf** [comment]
Okay thanks there is a comment column on proposal table but is currently limited to 50 characters looks like its not being used we must be able to use it. Will try to use comment-for-management looks like its for reviews but if we are not going to do fap views it must be fine.

**Comment by mutambaraf** [comment]
@Cat-Lucifer .Do we have any proposal status linked to this .Because at the moment comments can be added by the scientists who have access to the proposal .And they can add/update the comment at anytime even after all events on the proposal have been completed.

**Comment by Cat-Lucifer** [comment]
@mutambaraf  No.  Sample can info is only for a very small number of instruments, so is going to be managed by instrument scientists in the comments section.

**Comment by simonfernandes** [comment]
@Cat-Lucifer I think what Farai meant (and it's a question I have if not) is should the comment section only be editable when the proposal is in certain statuses?

**Comment by Cat-Lucifer** [comment]
@simonfernandes  Ahh, sorry for misunderstanding.  The comments section should be available for editing in all proposal statuses.

**Comment by mutambaraf** [comment]
Do we lock it after a given status like at the end or we just leave it open.

**Comment by Cat-Lucifer** [comment]
@mutambaraf  Let's start with leaving the comments section unlocked.  We can always change this later down the line if we see any issues with this.

**Comment by mutambaraf** [comment]
@Cat-Lucifer .One last comment will you be adding comments on scientists behalf.

**Comment by Cat-Lucifer** [comment]
@mutambaraf That's a good Q!  Maybe...

**Comment by mutambaraf** [comment]
@Cat-Lucifer .Do we need a timestamp to the comment when one is added to a proposals.

**Comment by Cat-Lucifer** [comment]
@mutambaraf Yes, it might be a nice feature to have a timestamp and edited by name.

**Comment by mutambaraf** [comment]
@Cat-Lucifer the first issue have been added to the current PR .But for tracking who updated the comment have opened this issue: https://github.com/UserOfficeProject/issue-tracker/issues/1274
