### ISSUE TITLE
Whitelist Scheduler for PDF download

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#1037]
Refs https://github.com/isisbusapps/Schedule/pull/4120

**Comment by zvailanu98** [comment]
> Refs https://github.com/isisbusapps/Schedule/pull/4120

Great editor

**Comment by ACLay** [comment]
As mentioned in the joint sprint planning I don't think we should be doing this. It feels to me like the scheduler's not manging the links properly, so I'm gonna have a look at what's going on over there.

**Comment by deepaksftc** [comment]
Closing this issue as Scheduler confirmed that they will be handling this through their backend now and no changes from our side would be required.
