### ISSUE TITLE
Remove references to the exchange server and replace it with a new mail relay in the User Office Project

### ISSUE THREAD

**Issue by go994** [UserOfficeProject/user-office-project-issue-tracker#1042]
### What is the problem and why is it a problem
We've now received notification from DI that they're planning to replace exchsmtp with a new SMTP relay. this new relay supports authentication but doesn't (currently) require it. 

We need to replace all instances of `exchsmtp.stfc.ac.uk` with `ob-mgw.stfc.ac.uk` and replace any instance of port 25 with port 26.

### Steps to reproduce (if it's a bug).

The only reference to the exchange SMTP server that I could find is [here ](https://github.com/UserOfficeProject/user-office-core/blob/64944a28c77c7779cffb754d0415834d22cbcd34/.github/workflows/test-build.yml#L338). If other places need to change within the user office project then that should be identified and changed as part of the pr that closes this issue.

**Comment by simonfernandes** [comment]
Closed via: 

https://github.com/isisbusapps/docker-orchestration/pull/561
https://github.com/isisbusapps/docker-orchestration/pull/576
