### ISSUE TITLE
Use the user time request rather than tech reviewer

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/user-office-project-issue-tracker#1044]
STFC like to use the requested time as the basis for their decisions in the meeting with the technical review as more a guideline. 
This might be implemented with a special time question, like the instrument picker question.

**Comment by joshhdawes** [comment]
Reopening, since we're expecting a final PR that 1) restricts requested time input to integers (#1134), and 2) fixes the existing PDF download error (#1111).

**Comment by Scott-James-Hurley** [comment]
Closed by https://github.com/UserOfficeProject/user-office-core/pull/636
