### ISSUE TITLE
The message "Failed to delete the proposal because it has dependencies which need to be deleted first." is displayed when a user tries to delete the proposal.

### ISSUE THREAD

**Issue by bashanlam** [UserOfficeProject/user-office-project-issue-tracker#1056]
The user encountered an error while attempting to delete the draft proposal. The error appeared in the log (https://logs.devs.facilities.rl.ac.uk/app/discover#/doc/7e1733e0-d283-11ea-856e-3dc8c807c0b0/kubernetes-bisappslogs-7.13.2-2024.04.09?id=-7lMwo4Bheqbk5w9dA69), indicating a failure to delete the proposal due to existing dependencies. Specifically, the error message stated: "Failed to delete the proposal because it has dependencies. The key (proposal_pk)=(17453) is still referenced from the table fap_proposals."

![image](https://github.com/UserOfficeProject/issue-tracker/assets/114708346/cf0c75da-8ddd-4113-8b32-4077d39d1e76)

**Comment by simonfernandes** [comment]
Closed via https://github.com/UserOfficeProject/user-office-core/pull/581
