### ISSUE TITLE
Indian/Dutch/Riken/Artemis users will be able to access legacy proposals

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#1057]
Split from https://github.com/UserOfficeProject/issue-tracker/issues/85

Core data needs to be imported to the new system for these routes.

**Comment by bashanlam** [comment]
@simonfernandes I've adapted the Artemis call name creation process from LSF as shown below. What are your thoughts on this approach?       
if length of referenceNumber >= 8 then 

- call name will be facility + "20" + referenceNumber.substring(0,2) + "_" + referenceNumber.charAt(2)
- (e.g. referenceNumber = 12120000 then call name is Artemis 2012_1. )

else

- call name will be "Artemis Historic"

**Comment by simonfernandes** [comment]
@bashanlam Seems like this should be fine seeing as that's how it's done for LSF.

Will also tag @mutambaraf in case he has any more thoughts as I have never used this legacy importer but I know Farai did the LSF import.

**Comment by simonfernandes** [comment]
Now done and imported into prod
