### ISSUE TITLE
Duplicate proposals in Instrument Sci View

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/user-office-project-issue-tracker#1058]
When looking from an instrument sci view, the proposals are duplicated for each scientist on an instrument. This is a problem with the db query in the STFC view.

**Comment by martin-trajanovski** [comment]
@TCMeldrum I am mentioning this https://github.com/UserOfficeProject/user-office-core/pull/575 here because in the multiple FAPs PR this should be fixed. I removed many things that were redundant and unnecessary.
