### ISSUE TITLE
Unable to proceed to the next step of filling out the proposal. It stops on "All genericTemplates must be completed"

### ISSUE THREAD

**Issue by deepaksftc** [UserOfficeProject/user-office-project-issue-tracker#1063]
### What is the problem and why is it a problem
This happened for an user, during the call.

When attempting to copy publications from a prior proposal (RB2320275) (Polarized neutron reflectometry .., Depth selective magnetic..)

User "14441" was unable to proceed to the next step of filling out the proposal. It stopped on "All genericTemplates must be completed" after having added three publications. They were all appearing correctly so the add seemed to have worked but then progressing through the proposal form wasn't possible.

The timestamp for this would be around 17 April 2024 15:30 - 15:50

User had to submit proposal with just 1 publication. User was allowed to proceed after removing the other 2 publications.

**Comment by deepaksftc** [comment]
Got this from logs. Couldn't find any other error related to this one in log. 
{
    "errors": [{
            "message": "Unexpected error value: \"Error while calling UserOfficeWebService\"",
            "locations": [{
                    "line": 2,
                    "column": 3
                }
            ],
            "path": ["genericTemplates"]
        }
    ],
    "context": {
        "requestUserId": 14441,
        "request": {
            "query": "query getGenericTemplatesWithProposalData($filter: GenericTemplatesFilter) {\n  genericTemplates(filter: $filter) {\n    ...genericTemplate\n    proposal {\n      primaryKey\n      proposalId\n      title\n    }\n  }\n}\n\nfragment genericTemplate on GenericTemplate {\n  id\n  title\n  creatorId\n  questionaryId\n  created\n  proposalPk\n  questionId\n}",
            "operationName": "getGenericTemplatesWithProposalData",
            "variables": {
                "filter": {
                    "questionId": "generic_template_1634227264949"
                }
            },
            "http": {
                "method": "POST",
                "headers": {},
                "search": "",
                "body": {
                    "query": "query getGenericTemplatesWithProposalData($filter: GenericTemplatesFilter) {\n  genericTemplates(filter: $filter) {\n    ...genericTemplate\n    proposal {\n      primaryKey\n      proposalId\n      title\n    }\n  }\n}\n\nfragment genericTemplate on GenericTemplate {\n  id\n  title\n  creatorId\n  questionaryId\n  created\n  proposalPk\n  questionId\n}",
                    "variables": {
                        "filter": {
                            "questionId": "generic_template_1634227264949"
                        }
                    },
                    "operationName": "getGenericTemplatesWithProposalData"
                }
            }
        }
    }
}

**Comment by simonfernandes** [comment]
We're unable to replicate this so since it only affected a single user for now we can close and re-open in the future.
