### ISSUE TITLE
Problem with experimental area field filter

### ISSUE THREAD

**Issue by deepaksftc** [UserOfficeProject/user-office-project-issue-tracker#1064]
### What is the problem and why is it a problem

When logged in as Experiment scientist, random results show up when selecting option from filters. Filter by experimental area field seems to be not working.

### Steps to reproduce (if it's a bug).

1. Log in as Experiment Scientist
2. Try applying filter by call and instrument
3. Same result appears with and without choosing an option from experimental area filter
![image](https://github.com/UserOfficeProject/issue-tracker/assets/149392207/202cd237-ef69-47e1-a974-c993d3a01179)

**Comment by ellen-wright** [comment]
After trying to recreate the problem on prod by testing with filtering with multiple different experimental areas, the correct results were being returned. It seems that this may no longer be a problem.
