### ISSUE TITLE
Status of proposals which where submitted during internal call open not being updated after call internal close

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#1065]
### What is the problem and why is it a problem
Proposals that are being submitted during call internal call open are not being update through the work flow correctly. This was identified in the last ISIS 2024_2 call internal close.

##### ISIS 2024_2 workflow

![image](https://github.com/UserOfficeProject/issue-tracker/assets/71100224/92b126d4-504a-44f9-b01b-8fe00b596c06)

##### Proposal RB 2420500 logs.
![image](https://github.com/UserOfficeProject/issue-tracker/assets/71100224/ec266c24-75ec-4354-a47a-6beda1b29ffb)

**Comment by simonfernandes** [comment]
Sprint planning notes:

We should do some thorough testing of different internal/external scenarios and whether proposals reach the correct statuses when expected
