### ISSUE TITLE
HPL proposals require a grant to progress

### ISSUE THREAD

**Issue by EdwardHaynes** [UserOfficeProject/user-office-project-issue-tracker#1066]
Grants are compulsory on HPL proposals but this doesn't need to be the case. Some users had to create fake grants in order to progress their HPL proposals. I'm unsure if this effects other routes but might be worth checking.

This was a request received from David Carroll and Emma Gozzard.

"Needing to add a grant to progress the submission – Dino Jaroszynski indicated that for him to progress he had to add a grant – this should not be required - please confirm if this is an issue as Dino was rushing his submission" - Dave Carroll in the support inbox - April 29, 2024 3:18 PM

**Comment by simonfernandes** [comment]
Sprint planning notes:

There doesn't seem to be a way to make a sub template optional. The "is required" checkbox is missing from the question. We could add this as a nice solution. If this is difficult or time consuming then, as a workaround, we could we could add a leading question like "do you have a grant?" that when ticked shows the sub template.

**Comment by simonfernandes** [comment]
Sprint planning notes:

Go ahead with the workaround of the leading question for now, then we can always come back to this and make the template optional.

**Comment by Cat-Lucifer** [comment]
Proposal template workaround done.

**Comment by simonfernandes** [comment]
Workaround is fine for upcoming round, https://github.com/UserOfficeProject/issue-tracker/issues/1180 opened for future improvement
