### ISSUE TITLE
Technical documents required for Gemini TA3 but not Orion

### ISSUE THREAD

**Issue by EdwardHaynes** [UserOfficeProject/user-office-project-issue-tracker#1067]
Technical documents are required for Gemini TA3 (CLF-HPL) instruments and not Orion. More investigation might be needed for other instruments.

This was a request received from David Carroll and Emma Gozzard.

"Having to upload a technical doc for Orion proposals / being allowed to upload tech documents  – two of the Orion proposals have a technical document when they should not - Phil Martin pointed out the system seemed to force him to upload a technical document and I asked that he upload a blank – I assume the same for the others. I will pass these onto the Orion team as the PIs have now added information into these. ... ideally it would be mandatory Gemini TA3 and not mandatory for Orion – can that level of finesse be used?" 
 - Dave Carroll in the support inbox - April 29, 2024 3:38 PM

**Comment by simonfernandes** [comment]
Sprint planning notes:

@Cat-Lucifer to try adding dependencies to the tech spec question so that they don't show for Orion. We need to test that an Orion user can just click save and continue on the empty topic. Emma to also test that this won't affect users cloning proposals with the previous template.

**Comment by Cat-Lucifer** [comment]
Tested in Dev:
* Submitted an Orion proposal with tech spec attached.
* Changed the questionnaire to show tech spec Q for non-Orion selection only.
* Cloned previous Orion proposal.  Tech spec Q not showing and was able to submit proposal okay.
* Checked that tech spec Q showed when selected Gemini - it did.

Tested successfully, so changed the HPL proposal questionnaire - dependency of Q `upload_technical_specification` to show when `Facility_Area` field does not equal Orion.
