### ISSUE TITLE
Unclear error messages when trying to clone legacy proposals

### ISSUE THREAD

**Issue by EdwardHaynes** [UserOfficeProject/user-office-project-issue-tracker#1069]
Users are trying to clone legacy proposals and receiving error messages. It's probably easier to disable the cloning option for these proposals rather than change the errors but I'll leave that for Submissions to decide on.

This was a request received from David Carroll and Emma Gozzard.

Email from Dave Carroll in the support inbox - April 29, 2024 5:27 PM

**Comment by simonfernandes** [comment]
Sprint planning notes:

We should add a check whether the clone is possible and valid (i.e. not legacy) at the point of the user clicking clone and have a pop up message.
