### ISSUE TITLE
FAP Review Assignment Conflict of Interest Prompt is Bugged

### ISSUE THREAD

**Issue by Scott-James-Hurley** [UserOfficeProject/user-office-project-issue-tracker#1074]
Through the support inbox, a user reports (16.05.24): 
"Every proposal prompts me that the reviewers and proposers have conflicts. This is a lovely idea but it is broken. What is odd is that the number of conflicts and their specific type, while all wrong, changes each time"

This affects FAP chairs, secretaries, User Officer (basically, any users assigning FAP reviews) when assigning FAP reviews to FAP members. This may cause confusion when doing the assignments. The prompt needs to be absent when there are no conflicts and display accurate information when there are.

### Steps to reproduce (if it's a bug).

- Create a proposal
- Assign it to a FAP
- Assign FAP members to the Panel that are in the same organisation as the proposer or are the proposer
- Assign the review for the proposal to those FAP members
- (You may need to meet other conditions if there are conflict warnings other than same org and person)
- Also verify no warning appears when there are no conflicts with the proposal and FAP reviewers.

**Comment by joshhdawes** [comment]
User reported that they're now able to assign/re-assign proposals without any problems - they just ignore the conflict-of-interest warnings.

Needs follow up.

**Comment by TCMeldrum** [comment]
After discussion with Emma during the FAP reviews feedback review meeting (12/7/24), we are just going to disable the prompt for stfc as fap secs have been and will continue to do it manually and the logic would be hard to implement.
