### ISSUE TITLE
How do we define who can manage and which instrument they can assign to in Xpress

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#1079]
This came up on away day 22/05/2024

**Comment by simonfernandes** [comment]
Hi @Cat-Lucifer. Sorry, we mentioned yesterday about having two lists of names attached to a technique, for 1) who would receive the initial notification that a proposal was submitted to the technique and 2) for who would have permission to assign an instrument. Have I understood that correctly? (Should have written live notes!) So scientists attached to the _technique_ would be able to change the instrument and status of a proposal in that technique, and scientists attached to the _instrument_ would only have permission to update the status? And both sets of people would also have access to the new xpress proposal list page.

**Comment by Cat-Lucifer** [comment]
@simonfernandes So, points 1) and 2) are correct.  As all science groups do handle Xpress differently within their group, with regard to who does what, we might need more steer from the science group leaders on this.  It's likely lists 1) and 2) are the same people, per technique, which would make it easier I guess.

I think let's aim to have the notification list and permissions list the same, so they can all change the instrument and status of a proposal in that technique, but explore how easy it is to have those two lists containing different people if that's necessary.

**Comment by simonfernandes** [comment]
Sprint planning notes:

Initially let's have a single list of users (admins) attached and they all receive the notification and all have permissions to view/change proposals. Once we have the management page in place we can consult group leaders and confirm they're happy with this. This is how it's currently done in legacy.

**Comment by simonfernandes** [comment]
@Cat-Lucifer Is the list of people on the technique (to receive the notification and have view/edit permissions, as above) different to all of the people attached to each instrument combined? If they are different, should people who are on the instrument be able to view/edit the proposals if they are not on the technique?

**Comment by Cat-Lucifer** [comment]
@simonfernandes  They might be different.  These are Qs for GLs when we meet with them.

**Comment by simonfernandes** [comment]
@Cat-Lucifer We may need to have that discussion sooner as it's going to impact some of our design decisions sooner around the technique picker and management page: https://github.com/UserOfficeProject/issue-tracker/discussions/1032#discussioncomment-9752530

**Comment by Cat-Lucifer** [comment]
@simonfernandes  No worries.  Let's chat more in our upcoming meeting.

**Comment by simonfernandes** [comment]
Update 25/07 based on email correspondence with @Cat-Lucifer:

- Everyone in the technique should:
  - be notified that a proposal has been submitted
  - be able to view the proposal
  - be able to change the status to under review or reject it
  - be able to assign an instrument to the proposal and change its status
  - be able to view the proposal once it's assigned an instrument, and make further status updates
  - be able to comment on the proposal for sample management
 
- Nobody outside of the technique or Xpress should have visibility of the proposal at any point

- In future, we may need to make permissions more flexible by specifying two subsets of people at the technique level:
  - Those who should be initially notified of a submission
  - Those who:
    - should have initial visibility of the proposal once it is submitted (after the review everyone in the technique should be able to see it)
    - should be able to review the proposal (assign an instrument, change status, add comments)
   
---

The wording above assumes that all permissions are at a technique level (i.e. people belong to a technique). The details of which people belong to each instrument isn't needed so long as we have the above.

**Comment by Cat-Lucifer** [comment]
[like]  Gozzard, Emma (STFC,RAL,ISIS) reacted to your message:
________________________________
