### ISSUE TITLE
Do we need a technique picker question to give access to the right instrument scientists in Xpress

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#1080]
Came up on away day 22/05/2024.

See https://github.com/UserOfficeProject/issue-tracker/discussions/1032 for discussion on how we might ask the user for a technique and link it to instruments and scientists. This discussion should be updated as decisions are made.

**Comment by simonfernandes** [comment]
We've decided to create a technique picker question. See the discussion above for more info.
