### ISSUE TITLE
Xpress scientist need a alternative view for submitted proposals which link to the management page

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#1081]
Came up on away day 22/05/2024.

**Comment by simonfernandes** [comment]
@mutambaraf Please could you give more info on this one? I don't understand what it's about

**Comment by simonfernandes** [comment]
@mutambaraf Any thoughts on this?

**Comment by simonfernandes** [comment]
@mutambaraf Let me know if this can be closed

**Comment by mutambaraf** [comment]
@simonfernandes I think on the top on my head this was for Experimental scientist to view proposals in their current table to view Xpress proposals. But if they have access to the management page this may not be necessary .

**Comment by simonfernandes** [comment]
Cool, I will close for now then 😊
