### ISSUE TITLE
Technical reviews are requested on every call, even if we don't intend to use them

### ISSUE THREAD

**Issue by ACLay** [UserOfficeProject/user-office-project-issue-tracker#1084]
### What is the problem and why is it a problem

We've been contacted by one of the instrument scientists on MuSR confused as to why they're marked as pending a technical review on a proposal which is part of the Rapid access route, for which reviews are handled offline rather than through the technical review/FAP process built into the software.

It might be good to make review assignment configurable at the call level to avoid such confusion going forward.

> Sent: 22 May 2024 17:45
> To: Facilities Business Systems & Support <[FacilitiesBusinessSystem@stfc.ac.uk](mailto:FacilitiesBusinessSystem@stfc.ac.uk)>
> Subject: Still seeing rejected proposal for technical review 
>  
> Good afternoon,
>  
> I am a muon Instrument scientist on the MuSR instrument at ISIS and I’d like to report a bug or inconsistency with the technical review system for proposals. 
>  
> I was viewing some proposals in the system when I noticed there seemed to be a technical review pending for MuSR. When I looked at the proposal (RB2400032) I noted that this corresponded to a proposal that had already been rejected for rapid access. Since it has been rejected, I don’t think I should still see the proposal in the review system. 
>  
> Just thought I’d let you know, since this could be confusing when it comes to the next proposal round if it isn’t just a one-off.

**Comment by joshhdawes** [comment]
@ACLay is this a duplicate of Tom's issue https://github.com/UserOfficeProject/issue-tracker/issues/1092 (for which there's already a PR)?

**Comment by ACLay** [comment]
Yes, this looks like a duplicate to me
