### ISSUE TITLE
Expired proposals showing to instrument scientists 

### ISSUE THREAD

**Issue by ellen-wright** [UserOfficeProject/user-office-project-issue-tracker#1089]
### What is the problem and why is it a problem
In the instrument scientists experimental area view, expired proposals are being returned in the proposal table.  
Do we want to make it so only active proposals are returned to instrument scientists?

**Comment by simonfernandes** [comment]
Sprint planning notes:

@Cat-Lucifer Should we be excluding these?

**Comment by Cat-Lucifer** [comment]
@simonfernandes Yes, I think we should.
