### ISSUE TITLE
Show All Rows For Tables for FAP assignment tables

### ISSUE THREAD

**Issue by Scott-James-Hurley** [UserOfficeProject/user-office-project-issue-tracker#1091]
From a meeting with Emma Gozzard about mass assigning FAP reviews (30.05.24).

It would be good if the dropdown that selects the number of rows displayed on a table has an option for showing all entries. This would be particularly useful for the `Proposals and Assignments` tab in FAPs but ideally this can be generalised for all tables.

![image](https://github.com/UserOfficeProject/issue-tracker/assets/44348929/d61398c3-89b1-45cf-a09e-2eed1b35c9a9)

**Comment by joshhdawes** [comment]
@martin-trajanovski I'm sure I've mentioned you in another, similar issue, but I can't find it now.

I'm told that you've been doing some work on improving how tables are displayed - will that work help with this issue?

**Comment by martin-trajanovski** [comment]
> @martin-trajanovski I'm sure I've mentioned you in another, similar issue, but I can't find it now.
> 
> I'm told that you've been doing some work on improving how tables are displayed - will that work help with this issue?

It is good to keep track of this. The work on the refactor and upgrades PR https://github.com/UserOfficeProject/user-office-core/pull/653 will definitely help with the approach how to fix this and maybe we can even reuse some parts for selection of all the proposals. But if this doesn't follow the backend pagination approach and only want to show all rows for tables in FAP assignment then we might need to develop another solution here. I know that in those tables we are loading all the data at once and one solution could be to dynamically set the 
```javascript
options={{
  pageSizeOptions: [5, 10, 20, 50],
}}
``` 
for example something like:
```javascript
options={{
  pageSizeOptions: [5, 10, 20, FapProposalsWitIdAndFormattedDate.length],
}}
``` 
and then we will be able to show all the proposals in one page and select them
