### ISSUE TITLE
Over fetching Data on Fap table

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/user-office-project-issue-tracker#1098]
On the `FapsTable.tsx` fetches all the fap data for all faps but when you click into edit a fap it refetches all this data for that specific fap. 

We are using graphql we are able to only fetch the data we need and no more. We should also check common pages for data over fetching. 

Modified `getFaps` query

**Comment by joshhdawes** [comment]
Representative of a wider problem - we should set up an epic for a larger bit of work, in which we do a wider investigation into problematic queries.

**Comment by ACLay** [comment]
Was it this issue we had some discussion of cacheing or reusing data as you switch between tabs? The client library mentioned in this issue may be of help for that https://github.com/UserOfficeProject/issue-tracker/issues/1220
