### ISSUE TITLE
Create Xpress workflow

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#1109]
We need to figure out what statuses we need in the proposal workflow and create anything necessary.

In a team meeting with Fredrik today (5th Sept 2024) we spoke about utilising a "Quick review" (or similar) status that would be in every Xpress call workflow. We could then do a lookahead that the status exists in a proposal's call workflow instead of explicitly checking whether it's an Xpress proposal.

**Comment by bashanlam** [comment]
@simonfernandes @srconway @deepaksftc @mutambaraf @ellen-wright  
### Xpress calls and proposals workflow
To determine if a call or proposal is an Xpress route, it must be linked to an Xpress workflow. An Xpress workflow must also be associated with the proposal status EXP_REVIEW. The following is the task list. 
- Create an Xpress proposal status with 
1.	Short code: EXP_REVIEW
2.	Name: Quick review
3.	Description: Proposal need quick review only.

- Create a new Xpress proposal workflow
1. It is mandatory to attach the proposal status: EXP_REVIEW to the workflow.
2. Default status: Draft -> Editable Submitted -> Submitted (locked) -> Quick Review
![image](https://github.com/user-attachments/assets/adc98437-c009-42a4-af4d-fc08a8745c52)

- Create an Xpress call
1. It is mandatory to attach an Xpress proposal workflow.

- Create an Xpress proposal
1. It is mandatory to attach a Xpress call.

- Update the getCalls function in the CallDataSource to include a filter for identifying Xpress routes.
1. Use CallsFilter with proposalStatusShortCode: EXP_REVIEW as input to return a list of Xpress calls.

**Comment by simonfernandes** [comment]
@bashanlam Please could you make sure this workflow is created on dev and prod before closing it off?

**Comment by simonfernandes** [comment]
@bashanlam I see you have said and marked this as done but I can't see that a prod workflow has been created? I think it would be a really good idea to get reviews from the team on a dev version before creating it on prod, because it's important that it's set up correctly.
