### ISSUE TITLE
Error encountered when inserting generic_templates: value too long on production.

### ISSUE THREAD

**Issue by bashanlam** [UserOfficeProject/user-office-project-issue-tracker#1118]
### What is the problem and why is it a problem

Error encountered when inserting generic_templates: value too long on production.

https://logs.devs.facilities.rl.ac.uk/app/discover#/doc/7e1733e0-d283-11ea-856e-3dc8c807c0b0/kubernetes-bisappslogs-7.13.2-2024.07.15?id=qr6Et5ABidrAvdFDRc9B

"{\"errors\":[{\"message\":\"insert into \\\"generic_templates\\\" (\\\"creator_id\\\", \\\"proposal_pk\\\", \\\"question_id\\\", \\\"questionary_id\\\", \\\"title\\\") values ($1, $2, $3, $4, $5) returning * - value too long for type character varying(500)\",\"locations\":[{\"line\":2,\"column\":3}],\"path\":[\"createGenericTemplate\"]}],\"context\":{\"requestUserId\":14959,\"request\":{\"query\":\"mutation createGenericTemplate($title: String!, $templateId: Int!, $proposalPk: Int!, $questionId: String!) {\\n  createGenericTemplate(\\n    title: $title\\n    templateId: $templateId\\n    proposalPk: $proposalPk\\n    questionId: $questionId\\n  ) {\\n    ...genericTemplate\\n    questionary {\\n      isCompleted\\n      ...questionary\\n    }\\n  }\\n}\\n\\nfragment genericTemplate on GenericTemplate {\\n  id\\n  title\\n  creatorId\\n  questionaryId\\n  created\\n  proposalPk\\n  questionId\\n}\\n\\nfragment questionary on Questionary {\\n  questionaryId\\n  templateId\\n  created\\n  steps {\\n    ...questionaryStep\\n  }\\n}\\n\\nfragment questionaryStep on QuestionaryStep {\\n  topic {\\n    ...topic\\n  }\\n  isCompleted\\n  fields {\\n    ...answer\\n  }\\n}\\n\\nfragment topic on Topic {\\n  title\\n  id\\n  templateId\\n  sortOrder\\n  isEnabled\\n}\\n\\nfragment answer on Answer {\\n  answerId\\n  question {\\n    ...question\\n  }\\n  sortOrder\\n  topicId\\n  config {\\n    ...fieldConfig\\n  }\\n  dependencies {\\n    questionId\\n    dependencyId\\n    dependencyNaturalKey\\n    condition {\\n      ...fieldCondition\\n    }\\n  }\\n  dependenciesOperator\\n  value\\n}\\n\\nfragment question on Question {\\n  id\\n  question\\n  naturalKey\\n  dataType\\n  categoryId\\n  config {\\n    ...fieldConfig\\n  }\\n}\\n\\nfragment fieldConfig on FieldConfig {\\n  ... on BooleanConfig {\\n    small_label\\n    required\\n    tooltip\\n  }\\n  ... on DateConfig {\\n    small_label\\n    required\\n    tooltip\\n    minDate\\n    maxDate\\n    defaultDate\\n    includeTime\\n  }\\n  ... on EmbellishmentConfig {\\n    html\\n    plain\\n    omitFromPdf\\n  }\\n  ... on FileUploadConfig {\\n    file_type\\n    max_files\\n    pdf_page_limit\\n    omitFromPdf\\n    small_label\\n    required\\n    tooltip\\n  }\\n  ... on IntervalConfig {\\n    units {\\n      ...unit\\n    }\\n    small_label\\n    required\\n    tooltip\\n  }\\n  ... on NumberInputConfig {\\n    units {\\n      ...unit\\n    }\\n    numberValueConstraint\\n    small_label\\n    required\\n    tooltip\\n  }\\n  ... on ProposalBasisConfig {\\n    tooltip\\n  }\\n  ... on ProposalEsiBasisConfig {\\n    tooltip\\n  }\\n  ... on SampleEsiBasisConfig {\\n    tooltip\\n  }\\n  ... on SampleBasisConfig {\\n    titlePlaceholder\\n  }\\n  ... on SampleDeclarationConfig {\\n    addEntryButtonLabel\\n    minEntries\\n    maxEntries\\n    templateId\\n    esiTemplateId\\n    templateCategory\\n    required\\n    small_label\\n  }\\n  ... on SubTemplateConfig {\\n    addEntryButtonLabel\\n    copyButtonLabel\\n    canCopy\\n    isMultipleCopySelect\\n    isCompleteOnCopy\\n    minEntries\\n    maxEntries\\n    templateId\\n    templateCategory\\n    required\\n    small_label\\n  }\\n  ... on SelectionFromOptionsConfig {\\n    variant\\n    options\\n    isMultipleSelect\\n    small_label\\n    required\\n    tooltip\\n  }\\n  ... on TextInputConfig {\\n    min\\n    max\\n    multiline\\n    placeholder\\n    small_label\\n    required\\n    tooltip\\n    htmlQuestion\\n    isHtmlQuestion\\n    isCounterHidden\\n  }\\n  ... on ShipmentBasisConfig {\\n    small_label\\n    required\\n    tooltip\\n  }\\n  ... on RichTextInputConfig {\\n    small_label\\n    required\\n    tooltip\\n    max\\n  }\\n  ... on DynamicMultipleChoiceConfig {\\n    small_label\\n    required\\n    tooltip\\n    url\\n    jsonPath\\n    apiCallRequestHeaders {\\n      name\\n      value\\n    }\\n    isMultipleSelect\\n    variant\\n  }\\n  ... on VisitBasisConfig {\\n    small_label\\n    required\\n    tooltip\\n  }\\n  ... on GenericTemplateBasisConfig {\\n    titlePlaceholder\\n    questionLabel\\n  }\\n  ... on FeedbackBasisConfig {\\n    small_label\\n    required\\n    tooltip\\n  }\\n  ... on InstrumentPickerConfig {\\n    variant\\n    small_label\\n    required\\n    tooltip\\n    isMultipleSelect\\n    instruments {\\n      id\\n      name\\n    }\\n  }\\n}\\n\\nfragment unit on Unit {\\n  id\\n  unit\\n  quantity\\n  symbol\\n  siConversionFormula\\n}\\n\\nfragment fieldCondition on FieldCondition {\\n  condition\\n  params\\n}\",\"operationName\":\"createGenericTemplate\",\"variables\":{\"title\":\"Ahmed, A., Schoberer, J., Cooke, E. & Botchway, S. W. Multicolor FRET-FLIM Microscopy to Analyze Multiprotein Interactions in Live Cells. in 287–301 (2021). doi:10.1007/978-1-0716-1126-5_16. 6.\\nmTOR direct interactions with Rheb-GTPase and raptor: sub-cellular localization using fluorescence lifetime imaging RB Yadav, P Burgos, AW Parker, V Iadevaia, CG Proud, RA Allen, ... BMC cell biology 14 (1), 1-16\\nmTOR direct interactions with Rheb-GTPase and raptor: sub-cellular localization using fluorescence lifetime imaging SW Botchway, CD Stubbs, A Jeshtadi, JP O'Connell, RA Allen, CG Proud, ...\\nDirect interaction of baculovirus capsid proteins VP39 and EXON0 with kinesin-1 in insect cells determined by fluorescence resonance energy transfer-fluorescence lifetime … JO Danquah, S Botchway, A Jeshtadi, LA King Journal of virology 86 (2), 844-853\\nInteraction of poxvirus intracellular mature virion proteins with the TPR domain of kinesin light chain in live infected cells revealed by two-photon-induced fluorescence … A Jeshtadi, P Burgos, CD Stubbs, AW Parker, LA King, MA Skinner, ... Journal of virology 84 (24), 12886-12894\",\"templateId\":5,\"proposalPk\":18248,\"questionId\":\"generic_template_1634227264949\"},\"http\":{\"method\":\"POST\",\"headers\":{},\"search\":\"\",\"body\":{\"query\":\"mutation createGenericTemplate($title: String!, $templateId: Int!, $proposalPk: Int!, $questionId: String!) {\\n  createGenericTemplate(\\n    title: $title\\n    templateId: $templateId\\n    proposalPk: $proposalPk\\n    questionId: $questionId\\n  ) {\\n    ...genericTemplate\\n    questionary {\\n      isCompleted\\n      ...questionary\\n    }\\n  }\\n}\\n\\nfragment genericTemplate on GenericTemplate {\\n  id\\n  title\\n  creatorId\\n  questionaryId\\n  created\\n  proposalPk\\n  questionId\\n}\\n\\nfragment questionary on Questionary {\\n  questionaryId\\n  templateId\\n  created\\n  steps {\\n    ...questionaryStep\\n  }\\n}\\n\\nfragment questionaryStep on QuestionaryStep {\\n  topic {\\n    ...topic\\n  }\\n  isCompleted\\n  fields {\\n    ...answer\\n  }\\n}\\n\\nfragment topic on Topic {\\n  title\\n  id\\n  templateId\\n  sortOrder\\n  isEnabled\\n}\\n\\nfragment answer on Answer {\\n  answerId\\n  question {\\n    ...question\\n  }\\n  sortOrder\\n  topicId\\n  config {\\n    ...fieldConfig\\n  }\\n  dependencies {\\n    questionId\\n    dependencyId\\n    dependencyNaturalKey\\n    condition {\\n      ...fieldCondition\\n    }\\n  }\\n  dependenciesOperator\\n  value\\n}\\n\\nfragment question on Question {\\n  id\\n  question\\n  naturalKey\\n  dataType\\n  categoryId\\n  config {\\n    ...fieldConfig\\n  }\\n}\\n\\nfragment fieldConfig on FieldConfig {\\n  ... on BooleanConfig {\\n    small_label\\n    required\\n    tooltip\\n  }\\n  ... on DateConfig {\\n    small_label\\n    required\\n    tooltip\\n    minDate\\n    maxDate\\n    defaultDate\\n    includeTime\\n  }\\n  ... on EmbellishmentConfig {\\n    html\\n    plain\\n    omitFromPdf\\n  }\\n  ... on FileUploadConfig {\\n    file_type\\n    max_files\\n    pdf_page_limit\\n    omitFromPdf\\n    small_label\\n    required\\n    tooltip\\n  }\\n  ... on IntervalConfig {\\n    units {\\n      ...unit\\n    }\\n    small_label\\n    required\\n    tooltip\\n  }\\n  ... on NumberInputConfig {\\n    units {\\n      ...unit\\n    }\\n    numberValueConstraint\\n    small_label\\n    required\\n    tooltip\\n  }\\n  ... on ProposalBasisConfig {\\n    tooltip\\n  }\\n  ... on ProposalEsiBasisConfig {\\n    tooltip\\n  }\\n  ... on SampleEsiBasisConfig {\\n    tooltip\\n  }\\n  ... on SampleBasisConfig {\\n    titlePlaceholder\\n  }\\n  ... on SampleDeclarationConfig {\\n    addEntryButtonLabel\\n    minEntries\\n    maxEntries\\n    templateId\\n    esiTemplateId\\n    templateCategory\\n    required\\n    small_label\\n  }\\n  ... on SubTemplateConfig {\\n    addEntryButtonLabel\\n    copyButtonLabel\\n    canCopy\\n    isMultipleCopySelect\\n    isCompleteOnCopy\\n    minEntries\\n    maxEntries\\n    templateId\\n    templateCategory\\n    required\\n    small_label\\n  }\\n  ... on SelectionFromOptionsConfig {\\n    variant\\n    options\\n    isMultipleSelect\\n    small_label\\n    required\\n    tooltip\\n  }\\n  ... on TextInputConfig {\\n    min\\n    max\\n    multiline\\n    placeholder\\n    small_label\\n    required\\n    tooltip\\n    htmlQuestion\\n    isHtmlQuestion\\n    isCounterHidden\\n  }\\n  ... on ShipmentBasisConfig {\\n    small_label\\n    required\\n    tooltip\\n  }\\n  ... on RichTextInputConfig {\\n    small_label\\n    required\\n    tooltip\\n    max\\n  }\\n  ... on DynamicMultipleChoiceConfig {\\n    small_label\\n    required\\n    tooltip\\n    url\\n    jsonPath\\n    apiCallRequestHeaders {\\n      name\\n      value\\n    }\\n    isMultipleSelect\\n    variant\\n  }\\n  ... on VisitBasisConfig {\\n    small_label\\n    required\\n    tooltip\\n  }\\n  ... on GenericTemplateBasisConfig {\\n    titlePlaceholder\\n    questionLabel\\n  }\\n  ... on FeedbackBasisConfig {\\n    small_label\\n    required\\n    tooltip\\n  }\\n  ... on InstrumentPickerConfig {\\n    variant\\n    small_label\\n    required\\n    tooltip\\n    isMultipleSelect\\n    instruments {\\n      id\\n      name\\n    }\\n  }\\n}\\n\\nfragment unit on Unit {\\n  id\\n  unit\\n  quantity\\n  symbol\\n  siConversionFormula\\n}\\n\\nfragment fieldCondition on FieldCondition {\\n  condition\\n  params\\n}\",\"variables\":{\"title\":\"Ahmed, A., Schoberer, J., Cooke, E. & Botchway, S. W. Multicolor FRET-FLIM Microscopy to Analyze Multiprotein Interactions in Live Cells. in 287–301 (2021). doi:10.1007/978-1-0716-1126-5_16. 6.\\nmTOR direct interactions with Rheb-GTPase and raptor: sub-cellular localization using fluorescence lifetime imaging RB Yadav, P Burgos, AW Parker, V Iadevaia, CG Proud, RA Allen, ... BMC cell biology 14 (1), 1-16\\nmTOR direct interactions with Rheb-GTPase and raptor: sub-cellular localization using fluorescence lifetime imaging SW Botchway, CD Stubbs, A Jeshtadi, JP O'Connell, RA Allen, CG Proud, ...\\nDirect interaction of baculovirus capsid proteins VP39 and EXON0 with kinesin-1 in insect cells determined by fluorescence resonance energy transfer-fluorescence lifetime … JO Danquah, S Botchway, A Jeshtadi, LA King Journal of virology 86 (2), 844-853\\nInteraction of poxvirus intracellular mature virion proteins with the TPR domain of kinesin light chain in live infected cells revealed by two-photon-induced fluorescence … A Jeshtadi, P Burgos, CD Stubbs, AW Parker, LA King, MA Skinner, ... Journal of virology 84 (24), 12886-12894\",\"templateId\":5,\"proposalPk\":18248,\"questionId\":\"generic_template_1634227264949\"},\"operationName\":\"createGenericTemplate\"}}}}}"

**Comment by simonfernandes** [comment]
App no for the above: 25130007

**Comment by simonfernandes** [comment]
Sprint planning notes: 

Evidence suggests the user was able to sort this out.
