### ISSUE TITLE
A round may have a different deadline for staff than external users

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#112]
A round may have a different deadline for staff than external users.

For example, the ISIS direct deadline is 1 week later for staff as they provide support and advice to users during the user submission period.

**Comment by JEThompson97** [comment]
Will only want this for ISIS (not CLF)
ISIS Direct will want this from the new system

**Comment by WhittyPM** [comment]
Linked to change log ID 1

**Comment by TickleThePanda** [comment]
Sonia had the idea that we can do this by introducing a new status which means "Submitted (internal edit only)". When a proposal is in this state, any user with the instrument scientist or user officer role can still edit it in the normal front-end. We'd need a new "Internal close" event and associated dates in the call.

**Comment by mutambaraf** [comment]
Possible implementation 
- Add additional field for internal call end date.
- Add proposal workflow status for editable submitted internal proposals.
- Add call internal event to be emitted when internal call ends.
- Update existing or create new asynchronous job for call internal ended check and proposal update.
- Add a new filter to calls for active internal calls.

Processes

- Internal call close date will be set on call creation, on calls with ( editable submitted internal proposals)  status as part on the proposal workflow (default will be call end date).
- Internal users will be able to submit or edit proposal after call end date (Will return open calls for internal users if available based on roles).
- Will also show call internal close date and the duration to close in the front end.
- Update proposal workflow to include the new event and proposal status.
- Will also add an additional filter for open internal calls.

**Comment by mutambaraf** [comment]
Design review outcome.
- Single call event for internal call close.
- Send internal call close notification for support staff (If call end event is sending notifications)
- Use the current end call  asynchronous job to reduce work load if possible.
- Use jwt to set internal user status for a user(Check with user services) default to false.
- All proposals will go through the same proposal status workflow .
- Proposals submitted during internal call open must emit all the previous events.
