### ISSUE TITLE
As a reviewer, I want to score proposals as R and X, not just a numerical value

### ISSUE THREAD

**Issue by joshhdawes** [UserOfficeProject/user-office-project-issue-tracker#1121]
Currently proposals can be scored only with numerical values. An improvement would be to allow R and X to be used instead of numbers to mark different outcomes for proposals.

This could be implemented by adding an extra field for R or X next to the numerical score.

**Comment by TCMeldrum** [comment]
Eli wanted to have some custom review questionnaire making the review page a template like proposals or samples: https://github.com/UserOfficeProject/user-office-core/discussions/651 this sounds like it can be achieved through that and can be solved by helping them create this feature.

**Comment by joshhdawes** [comment]
ELI are actively working on this, so would be good to either take advantage of their work, or work with them on the feature.

**Comment by joshhdawes** [comment]
After a discussion with ELI on 30/7/24, it seems that they've made very good progress towards having review templates. Using this, it shouldn't be too difficult to add a new field for R/X/whatever else to reviews.

@TCMeldrum is going to test the new feature, and will be involved in the PR review.

ELI will also give a status update and demo in the sprint planning meeting with ESS on 7/8/24.

**Comment by joshhdawes** [comment]
Based on the sprint planning meeting, we're currently waiting for ELI to put their work in PR so we can review it and build on it.

**Comment by martin-trajanovski** [comment]
@joshhdawes as I can see the PR has already been created here https://github.com/UserOfficeProject/user-office-core/pull/691

**Comment by joshhdawes** [comment]
@martin-trajanovski thanks for pointing that out!

**Comment by TCMeldrum** [comment]
> Based on the sprint planning meeting, we're currently waiting for ELI to put their work in PR so we can review it and build on it.

We don't really need to build on it code wise, we can just use what they have implemented and create a template with the X and R  options

**Comment by joshhdawes** [comment]
@TCMeldrum alright - good to know. I was wondering if there'd be some work to do to implement another question in the template, but you're right - based on the demo we've seen that should already be possible.

Should be a nice easy issue to get rid of, then!

**Comment by TCMeldrum** [comment]
Yeah we will just need to create the template on prod once this is released

**Comment by joshhdawes** [comment]
@TCMeldrum since this is now out on prod and we have a demo with Emma on Monday, unless there's anything else to do, I'll close this issue.

**Comment by TCMeldrum** [comment]
Emma has made the template
