### ISSUE TITLE
As a FAP secretary, I want to see how many proposals have been assigned to each reviewer in my FAP

### ISSUE THREAD

**Issue by joshhdawes** [UserOfficeProject/user-office-project-issue-tracker#1124]
Currently, it's not possible for a FAP secretary to see how many proposals each reviewer in their FAP has been given.

It would be useful for a simple numerical value to be added to the proposals system.

**Comment by joshhdawes** [comment]
@TCMeldrum is going to look into this and see if it's already possible, or some work is needed.

**Comment by TCMeldrum** [comment]
I think this fixed, but we need to review showing the number of proposals on a fap as well as I think that is going to include the old call as well
