### ISSUE TITLE
As a FAP secretary, I want to be able to modify technical comments made on proposals by Reviewers

### ISSUE THREAD

**Issue by joshhdawes** [UserOfficeProject/user-office-project-issue-tracker#1126]
FAP secretaries want to be able to modify technical comments to remove any information that might not be useful to that particular stage in the review process.

**Comment by joshhdawes** [comment]
Checked with ESS, and now @TCMeldrum is going to check with @Cat-Lucifer.

**Comment by Cat-Lucifer** [comment]
@joshhdawes @TCMeldrum  I will be having a meeting with Carina (my equivalent at ESS) to discuss this.  It isn't booked in yet, but hopefully will be this Friday.

**Comment by yoganandaness** [comment]
@joshhdawes @TCMeldrum It's a go ahead from ESS to modify the technical comments. 

I would also like to add along with a suggestion, to log this modification for auditing purpose.
