### ISSUE TITLE
Exporting FAP spreadsheet generated a spreadsheet missing instruments for one FAP secretary

### ISSUE THREAD

**Issue by joshhdawes** [UserOfficeProject/user-office-project-issue-tracker#1127]
One FAP secretary reported that the spreadsheets generated for a FAP did not include proposals for all instruments.

While @TCMeldrum has attempted to reproduce this bug and everything was fine, this should be investigated further.

**Comment by joshhdawes** [comment]
@georgeflecknell could you please let us know who we should contact to investigate this?

**Comment by georgeflecknell** [comment]
I think it was Greg Smith. The final item on the complied feedback document. Sorry for the pure software gore of this link:

https://stfc365.sharepoint.com/:w:/r/sites/isiscomputingdivision-staffsite/Shared%20Documents/Reviews%20and%20Allocations/Projects/User%20Office%20Core/[ProposalSystemReviewFeaturesFeedback.docx](https://stfc365.sharepoint.com/:w:/r/sites/isiscomputingdivision-staffsite/Shared%20Documents/Reviews%20and%20Allocations/Projects/User%20Office%20Core/ProposalSystemReviewFeaturesFeedback.docx?d=w2fdd9098f4b44269a592f7c3a4a5a965&csf=1&web=1&e=UcPJ8a)?d=w2fdd9098f4b44269a592f7c3a4a5a965&csf=1&web=1&e=UcPJ8a

**Comment by joshhdawes** [comment]
Thanks to @georgeflecknell for following up with the user. It turns out they hadn't realised that each instrument has its own sheet in the spreadsheet.

Perhaps we can make this clearer.

**Comment by TCMeldrum** [comment]
Clearer in what way, its a feature of excel? Like training documents maybe?

**Comment by georgeflecknell** [comment]
We could mention it in the training docs yes. I'll tell Nick Edwards.

**Comment by joshhdawes** [comment]
@georgeflecknell has this been added to the training docs? If so, I'll close this issue.

**Comment by georgeflecknell** [comment]
Yep

![image](https://github.com/user-attachments/assets/309efecd-2e67-4ebf-9bc2-784ce147240a)
