### ISSUE TITLE
As any user, I would like links to user documentation be available in the system

### ISSUE THREAD

**Issue by joshhdawes** [UserOfficeProject/user-office-project-issue-tracker#1129]
Currently, there is no link to user documentation within the proposals system.

It would be really useful for users to be able to find all user documentation by clicking a link on the page they're already using.

**Comment by joshhdawes** [comment]
@Cat-Lucifer while I don't intend to make a habit of assigning issues to you, I thought it'd be convenient here since this corresponds to the action item you got in the feedback review meeting.

**Comment by Cat-Lucifer** [comment]
> @Cat-Lucifer while I don't intend to make a habit of assigning issues to you, I thought it'd be convenient here since this corresponds to the action item you got in the feedback review meeting.

@joshhdawes  I get issues assigned to me now and again, so it's no worries!

**Comment by Cat-Lucifer** [comment]
Done.

**Comment by joshhdawes** [comment]
@Cat-Lucifer just thought - where has this been done? Was it a code change?

**Comment by Cat-Lucifer** [comment]
@joshhdawes  No code change.  I added some info in the reviewer area of the `Pages` section of the proposal system.  I would paste a screenshot, but the systems are currently down!
