### ISSUE TITLE
As a reviewer, I would like to see a recap of my reviews once I've submitted them

### ISSUE THREAD

**Issue by joshhdawes** [UserOfficeProject/user-office-project-issue-tracker#1130]
It would be useful for reviewers to be able to see recaps of their reviews once they've submitted them.

**Comment by TCMeldrum** [comment]
I think this is already the case, users can filter their reviews by status:
![image](https://github.com/user-attachments/assets/ba731998-cabd-4289-aa84-a1ea0fe492a1)
and see the reviews they have submitted.  This shows all reviews, even for previous rounds. I guess this wasn't in the training documents so some people did not see that they could filter by status and left it so they could only see draft reviews. I think all we need to do is update training documentation to show this feature to reviewers.

**Comment by TCMeldrum** [comment]
This just needs updating in the training documents
