### ISSUE TITLE
As a reviewer, I would like to be able to download a PDF of only the proposals that I have to review

### ISSUE THREAD

**Issue by joshhdawes** [UserOfficeProject/user-office-project-issue-tracker#1131]
Currently, for a reviewer to see all proposals they have to review, they usually have to go via the FAP booklet.

It would be nice for reviewers to be able to download PDFs containing only the proposals they have to review.

**Comment by joshhdawes** [comment]
@Bhaswati1148 mentioned that this feature already exists in an early form - users can select multiple proposals, and then click a single download button.

@Cat-Lucifer will this be acceptable, or do we need to put the relevant proposals into a single PDF?

**Comment by joshhdawes** [comment]
@Bhaswati1148 tells me that the download button actually generates a single PDF.

**Comment by Cat-Lucifer** [comment]
@joshhdawes @Bhaswati1148  Fab!  In that case, all that needs to happen is for the documentation to be updated accordingly.

@georgeflecknell
