### ISSUE TITLE
Proposal Count on FAP page only includes active FAP

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/user-office-project-issue-tracker#1136]
The proposal count on the FAP page includes proposals on calls that have ended. We should make sure this number is only for active calls. 
![image](https://github.com/user-attachments/assets/edd0987d-316d-422b-b06d-ed598b395a8a)

**Comment by joshhdawes** [comment]
@TCMeldrum does this PR https://github.com/UserOfficeProject/user-office-core/pull/689 address this?

**Comment by TCMeldrum** [comment]
Yeah forgot I made this issue sorry
