### ISSUE TITLE
Scientists should be able to assign an instrument to Xpress proposals

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#1137]
Scientists should be able to assign an instrument to a proposal when a proposal is submitted to their technique:

- Scientists should only be able to mark a proposal as accepted once an instrument has been selected
- The instruments available for selection should be limited to those within the technique

The suggestion so far has been to use a dropdown on the management page, but this is still open for suggestions and needs finalising.

**Comment by simonfernandes** [comment]
@Cat-Lucifer Just to check, do we only ever want to assign a single instrument to a proposal?

**Comment by Cat-Lucifer** [comment]
@simonfernandes  Good question!  I think yes.  If the sample needs multiple instruments the PI can resubmit or instrument scientists can sort this out using the capabilities of the scheduler.
