### ISSUE TITLE
Scientists should be able to change statuses on Xpress proposals

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#1138]
Scientists should be able to select from a list of static statuses for proposals within their technique.

- Status changes should trigger status actions

So far these are the statuses that we have talked about, but this list still needs to be finalised:

  > From: Gozzard, Emma (STFC,RAL,ISIS) <emma.gozzard@stfc.ac.uk> 
  > Sent: Thursday, July 25, 2024 1:08 PM
  > To: Fernandes, Simon (STFC,RAL,ISIS) <simon.fernandes@stfc.ac.uk>
  > Cc: Singh, Sukhvinder (STFC,RAL,ISIS) <Sukhvinder.Singh@stfc.ac.uk>
  > Subject: RE: Xpress questions
  >
  > I think, at the very least, we need:
  > 
  > Submitted
  > Under review
  > Unsuccessful or Reject
  > Queued or Approved (i.e. approved and waiting to be run)
  > Finished

**Comment by simonfernandes** [comment]
Hi @Cat-Lucifer. You previously mentioned these as a rough idea for proposal statuses. I've since been looking at the legacy Xpress import and we'll need to map the statuses over (I suppose ideally we might want to just mark all old proposals as rejected or finished, but I don't think there's a way of knowing which ones are actually still "in progress", is there?). Does this mapping help to come up with a final status list, and how does the mapping look to you? Legacy is on the left and new on the right side.

> Submitted (locked)
> Under review
> Unsuccessful
> Approved
> Finished

      ['No status', 'Submitted (locked)'],
      ['Submitted', 'Submitted (locked)'],
      ['Saved', DO NOT IMPORT'],
      ['Sample size and/or hazards review', 'Under review'],
      ['Under Review', 'Under review'],
      ['Under Review- with can', 'Under review'],
      ['Unsuccessful', 'Unsuccessful'],
      ['Sample being returned to user', 'Approved'],
      ['Awaiting Can', 'Approved'],
      ['Awaiting Sample', 'Approved'],
      ['No sample can- awaiting sample', 'Approved'],
      ['Successful- request can', 'Approved'],
      ['Successful- send sample', 'Approved'],
      ['Queued', 'Approved'],
      ['Disposed of by ISIS', 'Approved'],
      ['Successful', 'Approved'],
      ['Sample size and/or hazards accepted- please send sample', 'Approved'],
      ['Finished', 'Finished'],
      ['Closed', 'Finished'],

**Comment by simonfernandes** [comment]
Hi @Cat-Lucifer, following on from our discussion, please could you check this? Thanks 😊

### Status/instrument changes:
- When a proposal is first submitted (submitted locked status), scientists can only choose the Under Review or Unsuccessful statuses. (To ensure that the under review status is triggered in order send the email to Sample Safety)
- Scientists can only mark the status as Accepted when an instrument has been assigned.
- The proposal is ingested by Allocations when the status is Accepted. (Since this is the final point of ingestion downstream do we need a confirmation dialog for this?)
- When the status is Approved, the scientist can only change the status to Unsuccessful or Finished. (Avoids re-ingestion complications)
- When the status is Approved or Finished, the scientist can change the instrument, but it won't have an effect downstream.
- If the legacy proposal is pre-2024, the proposal should somehow be "locked" (i.e. scientist cannnot make changes to it)

### Status mappings:

If the proposal is submitted before 01/01/2024:

Drafts are not imported, everything is finished except unsuccessful.

If the proposal is submitted after 01/01/2024:

      ['No status', 'Submitted (locked)'],
      ['Submitted', 'Submitted (locked)'],
      ['Saved', DO NOT IMPORT'],
      ['Sample size and/or hazards review', 'Under review'],
      ['Under Review', 'Under review'],
      ['Under Review- with can', 'Under review'],
      ['Unsuccessful', 'Unsuccessful'],
      ['Sample being returned to user', 'Approved'],
      ['Awaiting Can', 'Approved'],
      ['Awaiting Sample', 'Approved'],
      ['No sample can- awaiting sample', 'Approved'],
      ['Successful- request can', 'Approved'],
      ['Successful- send sample', 'Approved'],
      ['Queued', 'Approved'],
      ['Disposed of by ISIS', 'Approved'],
      ['Successful', 'Approved'],
      ['Sample size and/or hazards accepted- please send sample', 'Approved'],
      ['Finished', 'Finished'],
      ['Closed', 'Finished'],

**Comment by Cat-Lucifer** [comment]
@simonfernandes   Thanks!  I think that's broadly right.

For: "When the status is Approved or Finished, the scientist can change the instrument, but it won't have an effect downstream" this should be:

* Locked with regard to instrument (they can change this in the scheduler instead) once changed to `Approved` status.
* A change of status to either `Unsuccessful` or `Finished` should be allowed when the proposal is in the `Approved` status.
* The proposal should be fully locked when in `Finished` status.

Thanks!

ETA - bold statues changed:

  ['No status', 'Submitted (locked)'],
  ['Submitted', 'Submitted (locked)'],
  ['Saved', DO NOT IMPORT'],
  ['Sample size and/or hazards review', 'Under review'],
  ['Under Review', 'Under review'],
  ['Under Review- with can', 'Under review'],
  ['Unsuccessful', 'Unsuccessful'],
  ['Sample being returned to user', '**Finished**'],
  ['Awaiting Can', 'Approved'],
  ['Awaiting Sample', 'Approved'],
  ['No sample can- awaiting sample', 'Approved'],
  ['Successful- request can', 'Approved'],
  ['Successful- send sample', 'Approved'],
  ['Queued', 'Approved'],
  ['Disposed of by ISIS', '**Finished**'],
  ['Successful', '**Finished**'],
  ['Sample size and/or hazards accepted- please send sample', 'Approved'],
  ['Finished', 'Finished'],
  ['Closed', 'Finished'],

**Comment by simonfernandes** [comment]
Hi @Cat-Lucifer, I think I've got most of this logic down now and I'm hoping there might be time to show you a quick demo on Friday, but just in case:

- Is it worth adding a confirmation dialog for changing statuses/instruments, considering how selecting them is going to automatically trigger an email? I've already added it actually, but can remove it it's not desired.
- Do we want to make `Unsuccessful` similar to `Finished` in that it's irreversible and the status and instrument are both view only? We'll be sending an email to the PI to say it's unsuccessful after all.
- Is it fine if certain legacy proposals (the ones with decommissioned instruments) are mapped to a technique but have a blank instrument? I know we've said any proposals submitted before 2024 will be locked. So long as these proposals are assigned a technique, scientists will still be able to view them fine so it won't affect that.
- Is it clearer to have all statuses shown at all times, but greyed out when inaccessible, or only show the available statuses? I've gone with the former for now:
![image](https://github.com/user-attachments/assets/6da35784-c2b7-426e-a51d-a53ef60aae01)

**Comment by Cat-Lucifer** [comment]
@simonfernandes Responses for each below.  Thanks!

1. Sounds good to me.
2. Yep, I think this is a good idea.  I assume anybody with `User Officer` role can edit a proposal in these statuses if necessary?
3. Not really.  It would be good for these to have the instrument selected shown.
4. Yes, happy with greyed out statuses

**Comment by simonfernandes** [comment]
@Cat-Lucifer Sorry, just realised I didn't answer your question! 

2. Yes, the way it's been done is so that scientists are restricted on what they can do based on the above conditions, but user officers can always change the instrument and status.
3. I will make sure they're mapped over to an instrument then.
