### ISSUE TITLE
Could not submit proposal

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#1147]
We failed to submit a proposal in dev after importing the recent ISIS direct template from production .The database is failing with `Failed to reset proposal events`. This will affect all users .
`
[2024-08-07T14:54:41.538Z] ERROR - QUERY ERROR
 {"message":"\n        SELECT *\n        FROM proposal_workflow_connections AS pwc\n        JOIN status_changing_events\n        ON status_changing_events.proposal_workflow_connection_id = pwc.proposal_workflow_connection_id\n        WHERE pwc.proposal_workflow_connection_id >= (\n          SELECT proposal_workflow_connection_id\n          FROM proposal_workflow_connections\n          WHERE proposal_workflow_id = 5\n          AND proposal_status_id = 15\n        )\n        AND pwc.proposal_workflow_id = 5;\n       - more than one row returned by a subquery used as an expression","error":{"length":129,"name":"error","severity":"ERROR","code":"21000","file":"nodeSubplan.c","line":"1174","routine":"ExecSetParamPlan"},"obj":{"__knexUid":"__knexUid385","__knexTxId":"__knexUid385","method":"raw","sql":"\n        SELECT *\n        FROM proposal_workflow_connections AS pwc\n        JOIN status_changing_events\n        ON status_changing_events.proposal_workflow_connection_id = pwc.proposal_workflow_connection_id\n        WHERE pwc.proposal_workflow_connection_id >= (\n          SELECT proposal_workflow_connection_id\n          FROM proposal_workflow_connections\n          WHERE proposal_workflow_id = 5\n          AND proposal_status_id = 15\n        )\n        AND pwc.proposal_workflow_id = 5;\n      ","bindings":[],"options":{},"__knexQueryUid":"Ef4SqTGKlp391r9C08F3X"},"QueryName":"\n        SELECT *\n        FROM proposal_workflow_connections AS pwc\n        JOIN status_changing_events\n        ON status_changing_events.proposal_workflow_connection_id = pwc.proposal_workflow_connection_id\n        WHERE pwc.proposal_workflow_connection_id >= (\n          SELECT proposal_workflow_connection_id\n          FROM proposal_workflow_connections\n          WHERE proposal_workflow_id = 5\n          AND proposal_status_id = 15\n        )\n        AND pwc.proposal_workflow_id = 5;\n      "}
[2024-08-07T14:54:41.539Z] ERROR - Failed to reset proposal events proposalPk: 139080
 {"exception":{"name":"error","message":"\n        SELECT *\n        FROM proposal_workflow_connections AS pwc\n        JOIN status_changing_events\n        ON status_changing_events.proposal_workflow_connection_id = pwc.proposal_workflow_connection_id\n        WHERE pwc.proposal_workflow_connection_id >= (\n          SELECT proposal_workflow_connection_id\n          FROM proposal_workflow_connections\n          WHERE proposal_workflow_id = 5\n          AND proposal_status_id = 15\n        )\n        AND pwc.proposal_workflow_id = 5;\n       - more than one row returned by a subquery used as an expression","stack":"error: \n        SELECT *\n        FROM proposal_workflow_connections AS pwc\n        JOIN status_changing_events\n        ON status_changing_events.proposal_workflow_connection_id = pwc.proposal_workflow_connection_id\n        WHERE pwc.proposal_workflow_connection_id >= (\n          SELECT proposal_workflow_connection_id\n          FROM proposal_workflow_connections\n          WHERE proposal_workflow_id = 5\n          AND proposal_status_id = 15\n        )\n        AND pwc.proposal_workflow_id = 5;\n       - more than one row returned by a subquery used as an expression\n 
`

**Comment by simonfernandes** [comment]
Sprint planning notes:

This seems to be working now. @bashanlam tested on dev, and proposals have been created/submitted to Direct on prod.
