### ISSUE TITLE
Ensure BSD-3 clause licence in set for all code repos

### ISSUE THREAD

**Issue by srconway** [UserOfficeProject/user-office-project-issue-tracker#1166]
### What is the problem and why is it a problem

This repo correctly lists itself as using BSD 3 clause: [user-office-proposal-performance-tests](https://github.com/UserOfficeProject/user-office-proposal-performance-tests/blob/develop/LICENSE)

The others are a mix of either no licence or one that references similar terms but doesn't explicitly identify BSD- 3 Clause although most do have a copyright statement e.g [user-office-factory](https://github.com/UserOfficeProject/user-office-factory?tab=License-1-ov-file#readme)

This is needed for STFC legal and to reflect the Memorandum of Understanding between contributing parties

### Steps to reproduce (if it's a bug).

This is only essential for the following 4 repos at least in the first instance:

- [x] [user-office-core](https://github.com/UserOfficeProject/user-office-core)
- [x] [mock-uows](https://github.com/UserOfficeProject/mock-uows)
- [x] [user-office-factory](https://github.com/UserOfficeProject/user-office-factory)
- [x] [user-office-lib](https://github.com/UserOfficeProject/user-office-lib)

To be confirmed for...

- [ ] [user-office-scheduler](https://github.com/UserOfficeProject/user-office-scheduler)
- [ ] [user-office-cron](https://github.com/UserOfficeProject/user-office-cron)
- [ ] [user-office-gateway](https://github.com/UserOfficeProject/user-office-gateway)
- [ ] [connector](https://github.com/UserOfficeProject/connector)
- [ ] [ror-gateway](https://github.com/UserOfficeProject/ror-gateway)
- [ ] [user-office-helm](https://github.com/UserOfficeProject/user-office-helm)
- [ ] [user-office-visa-adapter](https://github.com/UserOfficeProject/user-office-visa-adapter)
- [ ] [ping-templates](https://github.com/UserOfficeProject/ping-templates)
- [ ] [user-office-development-authorization-server](https://github.com/UserOfficeProject/user-office-development-authorization--server)
- [ ] [user-office-scheduler-frontend](https://github.com/UserOfficeProject/user-office-scheduler-frontend)
- [ ] [user-office-scheduler-backend](https://github.com/UserOfficeProject/user-office-scheduler-backend)
- [ ] [issue-tracker](https://github.com/UserOfficeProject/issue-tracker)
- [ ] [user-office-frontend](https://github.com/UserOfficeProject/user-office-frontend)
- [ ] [user-office-backend](https://github.com/UserOfficeProject/user-office-backend)
- [ ] [ess-user-office-project](https://github.com/UserOfficeProject/ess-user-office-project)
- [ ] [user-office-kubernetes](https://github.com/UserOfficeProject/user-office-kubernetes)
- [ ] [user-office-develop](https://github.com/UserOfficeProject/user-office-develop)
- [ ] [userofficeproject.github.io](https://github.com/UserOfficeProject/userofficeproject.github.io)
- [ ] [user-office-localisation](https://github.com/UserOfficeProject/user-office-localisation)
- [ ] [user-office-validation](https://github.com/UserOfficeProject/user-office-validation)

**Comment by simonfernandes** [comment]
Sprint planning notes:

We think this is just a case of copying the BSD 3 licence from performance testing repo into the core, lib, factory and mock-uows.
