### ISSUE TITLE
ISIS Xpress users will be able to access legacy PDFs

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#1178]
We need to import the legacy PDFs for Xpress proposals and ensure that the current system in place to download them works as expected.

**Comment by deepaksftc** [comment]
This need to wait till https://github.com/UserOfficeProject/issue-tracker/issues/87 is completed

**Comment by deepaksftc** [comment]
@Cat-Lucifer, while testing the changes in local and dev, just realized that we don't actually generate or store Xpress proposal pdf's in legacy system. In production, out of 3861 proposals, there were around 1000 proposals that had a proposal blob data available in data base, but those were the files user uploaded containing summary, not proposal pdfs. So, we don't have any legacy Xpress pdfs to be imported into new system. Hope this won't be an issue in this case.
@simonfernandes

**Comment by Cat-Lucifer** [comment]
@deepaksftc Hmmm, I was not expecting that.  What can we do to show users their past submission info on their proposal system dashboard?  Also, does this affect migrating the legacy data to the new management page?

**Comment by deepaksftc** [comment]
As per the discussion in sprint planning meeting and confirming with Emma, we are deciding to make basic details to be available in the new system and legacy specific details will be provided as and when any user requests given.
