### ISSUE TITLE
We're making unnecessary requests on the user home page

### ISSUE THREAD

**Issue by ACLay** [UserOfficeProject/user-office-project-issue-tracker#1196]
When loading the users root page, the following graphql queries are made:

- getSettings
- getFeatures
- getUserProposals
- getPageContent - HOMEPAGE
- getCalls
- getPageContent - PRIVACYPAGE
- getPageContent - HELPPAGE
- getPageContent - FOOTERCONTENT
- getCalls

The privacy and help page content requests are unnecessary, and if you navigate to the help page from the sidebar it even makes a fresh requests for the HELPPAGE content.

One of the getCalls requests is used to pre-populate the New Proposal/Select a call page, which a user might not even navigate to, and the other getCalls I haven't yet found what it's used for, but unlike a user officer there's no call filter on this page that might use it.

**Comment by TCMeldrum** [comment]
The `getPageContent - PRIVACYPAGE` and  `getPageContent - HELPPAGE` are for inbuilt links at the bottom of the page. Currently, on prod we have a FAQ button linked to the HELPPAGE call, but we are not using the PRIVACYPAGE one. I think we can load them dynamically or just remove them if no one is using them. 

The second `getCalls` is coming from the `PageLayout.tsx` component that is getting the number of calls, then disabling the option to navigate to the new proposal page if there are no active calls. I think maybe the new get calls minimal would be fine, but we should probably change this as _none_ of the call data is used.

**Comment by TCMeldrum** [comment]
I am not too sure the best way to proceed around `getPageContent - PRIVACYPAGE` and `getPageContent - HELPPAGE`, the way the components are set up it checks whether there is anything to display then adds the link in the footer which kind of makes these calls necessary. I guess we should discuss this in the joint ESS meeting.
