### ISSUE TITLE
Add button to view proposal on Xpress management page

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#1205]
We are missing a "View proposal" button on each row of the Xpress management page. It should show the same information that is usually shown when clicking the button for a non-xpress proposal, but should include any extra, relevant Xpress information (technique, instrument, etc.).

In the modal pop up, we should also see if it's feasible to remove the review tabs which are not applicable to Xpress.

Originated from a call with Emma, Deepak and Simon on 25/10/2024.

---

![image](https://github.com/user-attachments/assets/fd8d1c45-ebaf-4771-a842-83174f2d2224)

![image](https://github.com/user-attachments/assets/62ce5ad7-e9e5-4e52-a599-190fa77e5599)

**Comment by deepaksftc** [comment]
Hi @Cat-Lucifer, from what I understood, the 'View Proposal' button is used to just show the information that the 'User' has added as part of filling the proposals. Therefore, as per current logic, all the questions and answers which was part of the template, including the technique details will be displayed, but not instrument details. It's the same for non Xpress proposals also. 
If we have to include instrument also, it would be an extra effort including adding STFC specific logics. Just wanted to confirm with you if it's is fine to go with the existing way. 

![image](https://github.com/user-attachments/assets/e6ef3ac3-0b7d-4541-8139-794c87c3fd28)

**Comment by Cat-Lucifer** [comment]
@deepaksftc Yes, this is fine.  Thanks.

**Comment by simonfernandes** [comment]
Closed via https://github.com/UserOfficeProject/user-office-core/pull/834
