### ISSUE TITLE
Calls to getProposalWorkflow are slow

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#1235]
### What is the problem and why is it a problem

Some of the calls to `getProposalWorkflow` are slow which will affect the performance of the system this can be shown with the grapgh below. This is mainly due to slowness when resolving `proposalWorkflowConnectionGroups` which does some computation in this function as shown.
```
groupProposalWorkflowConnectionsByDroppableArea(
    proposalWorkflowConnections: ProposalWorkflowConnection[]
  ) {
    const groupedProposalWorkflowConnections = this.getUniqueDroppableGroupIds(
      proposalWorkflowConnections
    ).map((item) => ({
      groupId: item.droppableGroupId,
      parentGroupId:
        proposalWorkflowConnections.find(
          (element) => element.proposalStatusId === item.prevProposalStatusId
        )?.droppableGroupId || null,
      connections: proposalWorkflowConnections.filter(
        (proposalWorkflowConnection) =>
          proposalWorkflowConnection.droppableGroupId === item.droppableGroupId
      ),
    }));

    return groupedProposalWorkflowConnections;
  }
```

### Steps to reproduce (if it's a bug).
![image](https://github.com/user-attachments/assets/f371b426-a436-4dd2-a9af-21b90adece45)

**Comment by ACLay** [comment]
Is this really a slow call? The trace in the screenshot only took 3 milliseconds.

**Comment by mutambaraf** [comment]
We are closing this for now then open in case we have degradation.
