### ISSUE TITLE
The "User Office" heading on each page is inaccurate and misleading

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#1236]
Users are getting confused by the "User Office" title at the top of each page and don't know how to refer to the site or a page.

Originated from George via support on [Teams](https://teams.microsoft.com/l/message/19:fbe05f2b9db74c42972d9d9188711a5a@thread.skype/1731411478885?tenantId=3f66361c-a87e-4158-8f61-99e82db3cac8&groupId=403a668a-985f-445b-a4e3-b3a3070bb25b&parentMessageId=1731411478885&teamName=ISIS%20Computing%20Division%20Staff&channelName=Reviews%20and%20Allocations&createdTime=1731411478885):

> Every page has "User Office" here. For almost all users of the site this is inaccurate and misleading.  This is contributing to me getting asked by users for help with stuff like "the reviewers proposal site thing."
>  
> Could we make this more relevant? I'm guessing this is just inherited from the ESS default.

![image](https://github.com/user-attachments/assets/e454e5a6-065a-4746-a489-1a09b4f529c8)

**Comment by simonfernandes** [comment]
Sprint planning notes:

If it's not a lot of work, put the role in place of "User Office". Otherwise, remove the text.

**Comment by ACLay** [comment]
I ran this past the ESS at the joint sprint planning, they don't mind if we just get rid of the "User Office" text.
