### ISSUE TITLE
Improve Xpress performance

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#1239]
I noticed when testing the Xpress legacy import (3600 proposals imported) that performance is pretty slow, especially as User Officer. It looks like we're overfetching in places and can optimise things quite a bit.

**Comment by joshhdawes** [comment]
@simonfernandes do you have any data to show the speedups that these optimisations generated?

**Comment by simonfernandes** [comment]
@joshhdawes Hmm sorry, I didn't think to do some before/after tests of speed for each of the different optimisations this contained. I only have the below, which doesn't account for everything. It'll be a bit fiddly but if it helps I could go back and get a before/after? I think it might be nice to do this actually, if you can bear with me.


|  | Before | After |
| -- | -------- | ------- |
| getTechniqueScientistProposals (loading table data) | 5.4s avg | 400ms avg     |

**Comment by joshhdawes** [comment]
@simonfernandes if it doesn't take too much time and you're happy to do it, I think it'd be interesting to see. Otherwise it's okay :)

Thank you!

**Comment by simonfernandes** [comment]
@joshhdawes Hope this helps 🙂

|  | Before (avg) | After (avg) |
| -- | -------- | ------- |
| getTechniqueScientistProposals (loading table data) | 4.86 s | 452 ms |
| getTechniquesMinimal (getting techniques) | 484 ms | 130.5 ms |
| getCallsMinimal (getting calls) | 156 ms | 122 ms   |
| getInstrumentsMinimal (getting instruments) | N/A (retrieved from techniques) | 12 ms   |

**Comment by joshhdawes** [comment]
@simonfernandes what was done to optimise the calls that were already more minimal than before?

**Comment by simonfernandes** [comment]
@joshhdawes Nothing was done to getCallsMinimal or getInstrumentsMinimal other than reworking the Xpress code to adopt them (thanks to Tom and Alex). getTechniquesMinimal was created in this work and getTechniqueScientistProposals was also optimised.

**Comment by joshhdawes** [comment]
@simonfernandes alright - thanks! Looks like getTechniqueScientistProposals has been sped up pretty significantly! :)
