### ISSUE TITLE
Proposal templates link to proposals tries to load all proposals

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#1252]
### What is the problem and why is it a problem
The link to proposals when selected tries to load all proposals linked to a proposal template at once .This is causing performance issues in the backend potentially crushing the system if the number is significant.

### Steps to reproduce (if it's a bug).
![image](https://github.com/user-attachments/assets/8b89737a-d935-4a40-a4fb-d751f6e30415)

**Comment by simonfernandes** [comment]
Sprint planning notes:

We could just show the first 5 proposals or similar when clicking the link. We could also consider removing it if it has limited usefulness.

**Comment by mehta-pooja123** [comment]
@Cat-Lucifer : Is this feature in use to get all the proposals using a particular template? If not, we would like to remove this link that fetches all the proposals and instead make it a normal number displayed.

**Comment by ACLay** [comment]
Looks like the template filter parameter just isn't being passed through to the API query. And also the query its using isn't optimised for the fields being shown.

And for the record, here's my log output from hitting this locally:
```
duo-backend-1  |
duo-backend-1  | <--- Last few GCs --->
duo-backend-1  |
duo-backend-1  | [36:0x7fb70d2cf290]  3976987 ms: Scavenge 2000.9 (2074.2) -> 1998.7 (2077.2) MB, 8.6 / 0.0 ms  (average mu = 0.849, current mu = 0.408) allocation failure;
duo-backend-1  | [36:0x7fb70d2cf290]  3977007 ms: Scavenge 2004.6 (2077.2) -> 2001.9 (2095.0) MB, 12.2 / 0.0 ms  (average mu = 0.849, current mu = 0.408) allocation failure;
duo-backend-1  | [36:0x7fb70d2cf290]  3978212 ms: Mark-sweep 2015.4 (2095.0) -> 2005.4 (2102.5) MB, 1181.7 / 0.0 ms  (average mu = 0.587, current mu = 0.110) allocation failure; scavenge might not succeed
duo-backend-1  |
duo-backend-1  |
duo-backend-1  | <--- JS stacktrace --->
duo-backend-1  |
duo-backend-1  | FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```

**Comment by ACLay** [comment]
The more I dig into this popup the more broken it is. Not only is the filter parameter not passed to the backend, but the backend doesn't implement it properly, joining on a misspelled table name, so adding the filter causes the API call to fail.

The proposals table popup was added to the page in https://github.com/UserOfficeProject/user-office-core/pull/419, just over a year ago, and the actual table name is unchanged since the start of the UOP, so the table name in the join has always been wrong, and this feature has never worked.

**Comment by Cat-Lucifer** [comment]
> @Cat-Lucifer : Is this feature in use to get all the proposals using a particular template? If not, we would like to remove this link that fetches all the proposals and instead make it a normal number displayed.

@mehta-pooja123 I never used it as it never worked.  It's a nice feature, but it's not stopping me do my job.
