### ISSUE TITLE
Proposal download is breaking if there is no answer provided for instrument picker question

### ISSUE THREAD

**Issue by deepaksftc** [UserOfficeProject/user-office-project-issue-tracker#1278]
Proposal pdf download is breaking if there is no answer provided for instrument picker question. Please find the logs below,
https://logs.devs.facilities.rl.ac.uk/app/discover#/doc/7e1733e0-d283-11ea-856e-3dc8c807c0b0/kubernetes-bisappslogs-7.13.2-2024.11.29?id=gOmOd5MBNbM6a2t5TvUK

Noticed for proposal 2200349. This proposal is not having any answers.

**Comment by mutambaraf** [comment]
The error message is also misleading .
