### ISSUE TITLE
Integrate with LSF FAP letters

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#166]
Part of https://github.com/UserOfficeProject/stfc-user-office-project/issues/11

The LSF FAP letters are generated by `CLFFAPMaster` - the legacy MSAccess tool (located `\\isis\shares\ULS\_2021_Published_Applications`).

This tool may require data from various sources:
 - LSF SharePoint site
 - CLF proposal database

Ideally, we shouldn't change the existing MSAccess tool but instead should make sure the data is available for the tool.

**Comment by TickleThePanda** [comment]
This assumes that we have the current core data in SharePoint through #169. It may need some additional data updated in SharePoint.

**Comment by simonfernandes** [comment]
Closed as we have https://github.com/isisbusapps/fap-results-letters/issues/2
