### ISSUE TITLE
Submitters will be able to load, save, and submit proposals quickly (especially when under load)

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#18]
Submitters will be able to load, save, and submit proposals quickly, especially when under load for a positive user experience and to allow for stricter deadlines

- [ ] #655
- [x] #656
- [x] #657
- [x] #661
- [x] #660

Impacted users: Submitters

Project requirement: [proposal-56](https://stfc365.sharepoint.com/sites/proposals-and-outcomes-transformation-programme/Lists/Proposal%20user%20stories/DispForm.aspx?ID=56)

**Comment by TickleThePanda** [comment]
This is just the identifying the load issues:
 - testing the questionnaires under load
 - gathering and analysing the information

**Comment by WhittyPM** [comment]
Hi Panda, as discussed yesterday I have moved this one forward so we can do some of this work for LSF. @TickleThePanda

**Comment by TickleThePanda** [comment]
We have tested this as far as we're going to for this round. The simultaneous usage during the documentation day simulated this.

**Comment by WhittyPM** [comment]
@TickleThePanda I will reflect this in yesterdays documentation

**Comment by mr-field** [comment]
I've opened a draft PR with my work so far. I'll be on leave for the next week, so this may need to be handed over at the next sprint planning.

**Comment by mr-field** [comment]
From a quick glance at the logs, we may want to repeat this with a call that has an instrument attached. This should let us know if there were any problems with submitting emails, which don't go out without an instrument.

While we do that, it may be good to keep an eye on the resource usage of the dev cluster to see if we're running out of RAM/CPU. It could be something as simple as running `kubectl top` in a loop and writing the result to a file:
```sh
while (true); do kubectl top node --no-headers=true <node ID>; sleep 10; done > log_file
```

**Comment by TickleThePanda** [comment]
> From a quick glance at the logs, we may want to repeat this with a call that has an instrument attached. This should let us know if there were any problems with submitting emails, which don't go out without an instrument.

I was thinking about this. I think it could be worth creating a general purpose test instrument which can send emails - that way we don't accidentally ingest anything into allocations.

> While we do that, it may be good to keep an eye on the resource usage of the dev cluster to see if we're running out of RAM/CPU.

Good idea. We'll need to set up the metric server on the dev cluster, but it shouldn't be too hard as I got it working on the load test cluster.

**Comment by TickleThePanda** [comment]
@ACLay. I've confirmed that allocations doesn't currently create proposals (as far as I can tell) as part of this. We'll need to make sure it doesn't as part of #655 and #661, which I've added to the descriptions.

**Comment by TickleThePanda** [comment]
I ran another 60 concurrent users test. Doesn't look like we hit the limit but it does significantly increase load on each image.
![image](https://user-images.githubusercontent.com/13658288/185655226-85eb87e6-3687-4db1-97a5-d74b9b41df8a.png)

**Comment by TickleThePanda** [comment]
Looks like users deployed at the same time as the original 20 concurrent users test. Trying again now.

**Comment by TickleThePanda** [comment]
Review:
 - https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/657
 - https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/18#issuecomment-1220672289
 - https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/656
 - https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/655

Do we need
 - https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/661

**Comment by TickleThePanda** [comment]
90th percentile limit for proposal submission: 90s

**Comment by TickleThePanda** [comment]
I've moved this to "Before close" now as I think we're happy with the level of performance to be able to release.

**Comment by mr-field** [comment]
I ran the load test again after making it a bit more robust and teaching the backend how to log errors properly. Each time, I ran 3x the amount of cuncurrent tests.

The results now form a clearer pattern:
| concurrent | successes | failures* | % failure | mean  | median | 90th  | duration | submissions/min |
| ---------- | --------- | --------- | --------- | ----- | ------ | ----- | -------- | --------------- |
| [10]       | 30        | 0         | 0         | 55.5  | 48.4   | 111.3 | 453      | 4               |
| [20]       | 60        | 0         | 0         | 71    | 64.8   | 124.1 | 497      | 7.2             |
| [30]       | 89        | 1         | 1.1       | 82.3  | 67.1   | 128.4 | 505      | 10.6            |
| [40]       | 113       | 7         | 5.83      | 90.2  | 75     | 135.6 | 566      | 12              |
| [50]       | 144       | 6         | 4         | 110.4 | 98     | 190.9 | 628      | 13.8            |
| [60]       | 164       | 16        | 8.9       | 121.4 | 114.5  | 196.2 | 655      | 15              |

[10]: https://ci.devs.facilities.rl.ac.uk/view/ProposalLoadTest/job/Dev_Execute_ProposalLoadTest/99/
[20]: https://ci.devs.facilities.rl.ac.uk/view/ProposalLoadTest/job/Dev_Execute_ProposalLoadTest/100/
[30]: https://ci.devs.facilities.rl.ac.uk/view/ProposalLoadTest/job/Dev_Execute_ProposalLoadTest/101/
[40]: https://ci.devs.facilities.rl.ac.uk/view/ProposalLoadTest/job/Dev_Execute_ProposalLoadTest/102/
[50]: https://ci.devs.facilities.rl.ac.uk/view/ProposalLoadTest/job/Dev_Execute_ProposalLoadTest/103/
[60]: https://ci.devs.facilities.rl.ac.uk/view/ProposalLoadTest/job/Dev_Execute_ProposalLoadTest/104/

## Failures
Details on the failures for each run:

### 30
- 1 "Network request failed" while submitting proposal

### 40
- 5 502 Bad Gateway when calling GraphQL API
- 1 test error (failed to click on call button)
- 1 strange application error

### 50
- 5 Unexpected loading icon when saving (unclear if this is a test error or the backend taking very long to respond)
- 1 502 Bad Gateway when calling GraphQL API

### 60
- 12 Unexpected loading icon when saving (unclear if this is a test error or the backend taking very long to respond)
- 4 test error (failed to click on call button)

**Comment by keiranjprice101** [comment]
For the loading icon errors, is it possible to increase the timeout in cypress to determine if the requests will eventually go through?  I am not sure if the default timeout could be set globally before the tests run.

**Comment by mr-field** [comment]
> For the loading icon errors, is it possible to increase the timeout in cypress to determine if the requests will eventually go through?

We're setting the default timeout to a whole minute in the [test config](https://github.com/isisbusapps/internal-scripts/blob/add41e41a220104dd47ff90ea2d1fe434e2aeb12/proposals-load-tester/components/test/cypress.config.js#L29), but we could try bumping it up further

**Comment by mr-field** [comment]
As I'm leaving in a few days, I'm unassigning myself from the issue.

The load test results indicate that the app should work well enough under load for now. We should try to profile the app(s) in more detail to check where we can improve performance, bearing in mind the analysis from the last test round.
