### ISSUE TITLE
Integrate with ISIS Rapid review process

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#182]
Part of #11

We will need to ensure that proposals submitted to Rapid are processed appropriately. This will involve ensuring that this works within the User Office and panel proceses.

**Comment by simonfernandes** [comment]
Issues identified from #505:

- As a member of the User Office, I need to know when Rapid Access proposals have been submitted #506

Questions:
- The User Office will need to download proposal PDFs from the new proposal site - do they require training for this?
