### ISSUE TITLE
Integrate with ISIS Rapid scheduling

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#183]
Part of #11

This will require the correct data to be available in SharePoint to be updated in the proposal list cache.

The proposal lookup service should be updated to support getting data from the new proposal software.

- [x] Integrate with Proposal Allocations
- [ ] Integreate with Proposal Lookup

**Comment by simonfernandes** [comment]
Closed, with https://github.com/isisbusapps/Schedule/issues/3491 remaining on the Scheduler side
