### ISSUE TITLE
Ensure the (old) ISIS FAP letters work for 23/1

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#184]
Part of https://github.com/UserOfficeProject/stfc-user-office-project/issues/11

We need to make sure that the reports used by the FAP letters work with the new proposal software and that all of the correct data is present. 

For the ISIS FAP letters process, we pull proposal data from SharePoint (that includes results) via the SPProposalListCache tool into the ISIS database. Using an existing database view, we then export the data and use it to mail merge users. See the [full process](https://github.com/isisbusapps/ISISBusApps/wiki/FAP-letter-process-overview).

For example, we may find that things like proposal titles are missing, where data is missing in SharePoint and required joins to the old Oracle proposal database. 

---
Possible solution:

- Use the proposal allocations database for getting data that is required in addition to the cache data, and create a new view from it.
- Continue to use the mail merge letter solution with the data exported from the view.

**Comment by simonfernandes** [comment]
Notes from meeting with Sukh, Simon and Philip 28/10/22:

- Letters will ideally be sent before Christmas, however may end up being pushed back to the first or second week of January

**Comment by TickleThePanda** [comment]
I believe we've sent these. Did the original queries just work as they were?

**Comment by EdwardHaynes** [comment]
> I believe we've sent these. Did the original queries just work as they were?

Just had a meeting with George to go over this. The queries and spreadsheets worked as intended with no changes. The only issues that popped up were the usual problems with data (missing fap 10, missing data, format changes from instrument scientists).

We did have to add the countries manually during the process but that's because it wasn't pulled through from the new proposals system.

**Comment by TickleThePanda** [comment]
Great! Can we open an issue in reporting to fix the countries issue for these reports and close this one, then?

**Comment by EdwardHaynes** [comment]
Sounds good! I think this issue that Simon created covers everything: https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/775
