### ISSUE TITLE
Ensure FAP booklet generator works with new proposal submission software

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#185]
Part of https://github.com/UserOfficeProject/stfc-user-office-project/issues/11

Booklets will be sent by post to FAP members in advance of the FAP meetings. 

We need to make sure that our replacement booklet software (https://github.com/isisbusapps/fap-booklet-generator) is ready to be used by the deadline.

**Comment by simonfernandes** [comment]
Notes from meeting with Sukh, Simon and Philip 28/10/22:

- Sukh to check with Emma Roberts when physical copy of booklet needs to be generated

**Comment by georgeflecknell** [comment]
CLosing as done
