### ISSUE TITLE
Integrate with ISIS scheduling

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#187]
Part of #11

This will require the correct data to be available in SharePoint to be updated in the proposal list cache.

The proposal lookup service should be updated to support getting data from the new proposal software.

We will need to consider that we can request multiple instruments as part of this.

**Comment by EdwardHaynes** [comment]
Need to fix https://github.com/isisbusapps/proposal-allocations/issues/233 as part of this issue

**Comment by simonfernandes** [comment]
Completed by S&O
