### ISSUE TITLE
Round managers will be able to specifiy questions with answers that have a PDF file upload with PDF page count limitations

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#19]
Round managers will be able to specifiy questions with answers that have a PDF file upload with PDF page count limitations to ensure that submitters are able to submit science cases and other requirements, with the existing length limits in place

~What maximum file size (e.g. bytes) should we support?~ We've answered this in #240.

Impacted users: Proposal round managers

Project requirement: [proposal-58](https://stfc365.sharepoint.com/sites/proposals-and-outcomes-transformation-programme/Lists/Proposal%20user%20stories/DispForm.aspx?ID=58)

**Comment by WhittyPM** [comment]
Following LSF requirements prioritisation meeting,  the minimum acceptance for this user story is: 

- Make it clear with text (prompt) that users will be rejected if they don't comply with page count/font size

For LSF: Science Case​


**Programme = 6 sides of A4 ​

Direct = 2 sides of A4​**


Further development of this feature is located in issue ((??)). Will need to review if it's in scope of this project or issue that can managed through BAU development.. Review upon completion of PHASE 2.

**Comment by WhittyPM** [comment]
Andy's email specified the business guidelines on PDF uploads

**Maximum two A4 page scientific case (direct access) ,** including all figures (include scale bars for microscopy images), references. **Font size no less than 10 pt.**

Maximum six A4 page scientific case (programme access)  - and as above.

**Comment by WhittyPM** [comment]
@TickleThePanda maybe this one needs exploring in more detail with Philip/Emma - is this needed for RAPID? or would direct be more appropriate?
