### ISSUE TITLE
Use facility-appropriate logo in STFC email footer

### ISSUE THREAD

**Issue by mr-field** [UserOfficeProject/user-office-project-issue-tracker#213]
All STFC emails currently use the same image in their footer. At the moment, the image [is set to](https://github.com/isisbusapps/docker-orchestration/blob/1c9aefb42d6d2895e0641e70f0b096d342379a23/docker-compose.yml#L175) the CLF logo, as we're going to release to CLF (LSF) first.

In the future, we should either use a different logo for each facility or use the same generic STFC logo for all of them.

**Comment by keiranjprice101** [comment]
Completed
