### ISSUE TITLE
HPL submitters to have clear descriptions associated to each access route (new continuation, direct etc)

### ISSUE THREAD

**Issue by WhittyPM** [UserOfficeProject/user-office-project-issue-tracker#215]
David Carroll from HPL reported that there have been some issues with users submitting proposals through the wrong route. Feedback from users was that the descriptions are not entirely clear. George in support had to rectify the issue. To help prevent this issue occurring again and improve the user experience we should consider this requirement for HPL release. Going forward the round manager will be able to make changes when required. Review with HPL core group once we are ready to start engaging. 

To note, we currently have this requirement for LSF. 

@TickleThePanda

**Comment by simonfernandes** [comment]
Closing this, as this has now been solved by always giving users a clearly labelled call to choose from.
