### ISSUE TITLE
File Upload is unrestricted

### ISSUE THREAD

**Issue by TeraMike** [UserOfficeProject/user-office-project-issue-tracker#226]
With the file upload widget, the person creating the questionary has the option to limit which files will be accepted.  
However, on the actual file upload, you can simply ignore this and select 'all files', uploading any file with no other verification.
![image](https://user-images.githubusercontent.com/57662035/137337676-e982a0fe-bcd9-4ae1-9031-9e909ff12a8a.png)

If no options are selected, then `All Files (*.*)` is the default behaviour. I'm not sure if this is also desirable -- `pdf, doc, docx, audio/*, video/* and image/*` should be sufficiently wide for almost all cases?
![image](https://user-images.githubusercontent.com/57662035/137338395-11947a0b-5ee7-4397-b44c-03cb88cc108f.png)

The former behaviour should have some sort of check to prevent circumventing the accepted file types, and possibly the latter behaviour altered too (as example: changing default from 'any' to 'all of the above'). It would also be worth checking for special characters in the filename (e.g.: `/ \ < > : ; *` to name a few) , and allowing only one dot (`.`) for the extension.

Identified as a possible (though admittedly low) risk during #205.

**Comment by simonfernandes** [comment]
# How it currently works
We only use the file type restrictions for the `accept` attribute on an `<input>`. This attribute is just a hint given to the user's browser that filters files in the file selection dialog. Depending on OS, there is usually a dropdown that allows you to remove this filter and select any file. We have no control over this, so we can't prevent which file the user selects, and there is no validation to check what type of file has been uploaded.

The software trusts and stores the MIME type from the `Content-Type` header in the request, which is determined from file extension.

# Using file-type to check files

Many file types can be identified from some of the bits in their binary (e.g. a GIF will always start with the same 4 bytes). This is apparently the best way to identify a file, though it isn't a guarantee, as malicious users could still insert some binary into a bad file to disguise it. It would require checking a file's contents against a reference of magic numbers. [file-type](https://www.npmjs.com/package/file-type) is an active library that will efficiently determine a file with this method.

Pros of using file-type:
- Provides a more accurate way of determining what the user is uploading
- Kept up to date, active, efficient (doesn't need to read the whole file) vs our own implementation

Cons:
- Method can be circumvented
- Not guaranteed to be accurate

## Possible use cases
### If the file type can't be determined
- We could reject the upload. With the possible risk that the file may be what it claims to be and the library database is outdated or incorrect.
- We could accept the upload and record its type as unknown or with the type that comes from the reponse. In this scenario we could record some risk associated with the file, although the same could be said for any file, and there is addded complexity.

### If we can determine the file type
- This should probably be recorded in the database in favour of the request type.
- We can ensure that the extension matches the file type.

**Comment by simonfernandes** [comment]
Design review outcome:

- Use file-type to try to determine the file. If it can't be determined or doesn't match any of the accepted file types, reject the upload. The user can try a different file or contact support.
- Check with the ESS first, but probably get rid of the option for any file to be uploaded.
- Open separate issue on whether we want to security scan files down the line

**Comment by simonfernandes** [comment]
Closed via https://github.com/UserOfficeProject/user-office-frontend/pull/803 and https://github.com/UserOfficeProject/user-office-backend/pull/586
