### ISSUE TITLE
Review the FAP PDF style, layout and content with ISIS FAP secretaries

### ISSUE THREAD

**Issue by WhittyPM** [UserOfficeProject/user-office-project-issue-tracker#249]
We need to review the two pages of PDF generated by the proposal submission software with the ISIS FAP secretaries to confirm content. We should design a proposed layout and confirm this with them.

**Comment by sukhsingh2525** [comment]
Emma G's email:
We will have a better idea of this once we have confirmed the additional technique specific questions.
Philip is in discussion with the Group Leaders about this, so hopefully in the next couple of weeks.

**Comment by sukhsingh2525** [comment]
A meeting has been scheduled with the appropriate stakeholders to review this on 2nd Aug

**Comment by sukhsingh2525** [comment]
We had a meeting with the appropriate FAP secretaries, Emma G, and PK. 
Attached is a copy of the changes they stakeholders have requested:

[FAP PDF style meeting minutes.docx](https://github.com/UserOfficeProject/user-office-project-issue-tracker/files/9252468/FAP.PDF.style.meeting.minutes.docx)

**Comment by simonfernandes** [comment]
Closed as we have the requirements now (see Sukh's reply above)
