### ISSUE TITLE
As a submitter I will be able to give more details about my samples through checkbox options

### ISSUE THREAD

**Issue by WhittyPM** [UserOfficeProject/user-office-project-issue-tracker#250]
**Comment from LSF tester** The Add Samples dialogue is also not very informative. I would think we need at least a multiple option checkbox for hazards associated with the sample, containment level, sample type (e.g. material, biological fixed, biological live) and biological sample origin. Perhaps a checkbox for GMO samples? 

This was discussed in LSF core group meeting with Emma G and Dave C present. This would be a "nice to have" for later in the project. Would need to understand LSF needs in more detail. 

Would having this in the same questionnaire across CLF be required? Can we have some standardisation?

**Comment by TickleThePanda** [comment]
This is possible in the software but we may need to help Sarah do this.

**Comment by TickleThePanda** [comment]
Should be done by the FAP secretary instead.
