### ISSUE TITLE
Add different instrument scientist usage contexts to support more use cases

### ISSUE THREAD

**Issue by IVlaD17** [UserOfficeProject/user-office-project-issue-tracker#257]
Currently, when opening the proposals table page while logged in as an Instrument Scientist, the page opens up with the `FEASIBILITY_REVIEW` Status filter selected, whereas we'd like it to open up with the `All` Status filter selected. This should be discussed with the ESS.

It would be useful to have something like the GitHub filtering for issues where you can choose a default filter:

![image](https://user-images.githubusercontent.com/13658288/151004760-ad849740-6521-4d92-b335-4aabb056175d.png)

The current use cases that would be useful:
 - All proposals
 - Review requests

**Comment by simonfernandes** [comment]
Closing this as the default filters have been fixed and instrument scientists seem happy with how it works for now.
