### ISSUE TITLE
Refactor external user authentication to use dependency injection

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/user-office-project-issue-tracker#279]
After [creating the log-out method](https://github.com/UserOfficeProject/user-office-backend/pull/446), Fredrik [suggested](https://github.com/UserOfficeProject/user-office-backend/pull/446#issuecomment-966168991) we should move some of the methods out of the `UserDataSource` (src\datasources\stfc\StfcUserDataSource.ts) to the `authenticators` (src/auth/UserAuthentization.ts) folder then we can use dependency injection to separate out functionality.

This will require some working knowledge of the dependency injection library [`tsyringe`](https://github.com/microsoft/tsyringe).

**Comment by AspectVI** [comment]
Current progress.  Completed research into Dependency injection and location of where items that need moving are and need to be moved to. Dependency for items in question still needs confirmation and examples of existing injection as well. Looking to get a meeting with someone today to talk through the systems and locate examples of DI within the code for help in the implementation stage.

**Comment by AspectVI** [comment]
Most relevant changes have been made but the auto-tests need fixing. 
As of right now, The only difference between the 2 authorisors is the functions moved from data sources. These functions are only used in 2 places across the codebase. The new authorisor injects into these places but the other places haven't been updated to use DI yet. Changing these to use DI will not change how the code works in any way, so should they be changed?
