### ISSUE TITLE
Generic templates split across pages in the proposal PDF

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#283]
In the proposal PDF, generic template answers are displayed in a grid format:

<img src="https://user-images.githubusercontent.com/14293717/141495511-52b24465-961d-4b89-b048-2973473fb4b2.png" alt="Your image title" width="250"/>

All of the information in a box should be kept on the same page so that it is not split between pages. In the example below, the third grid box should be displayed on its own page:

<img src="https://user-images.githubusercontent.com/14293717/141495713-834d0022-ff83-408d-8dc3-3f4cb11a8401.png" alt="Your image title" width="250"/>

I think this is because the CSS rule `page-break-inside: avoid;` isn't being respected. I tried various things with Bootstrap columns and rows, and also overriding that by using flex. The only way I could get it to work was with a single column, not multiple. It seems to be an older CSS rule and the only possible solution I could find was to put the layout in a table. I guess this would be fine since it's all rendered to PDF anyway, but I think it would require additional logic of when to insert new rows, which I wasn't sure was the right route.

**Comment by WhittyPM** [comment]
@TickleThePanda @simonfernandes  is this a bug fix needed for release?

**Comment by simonfernandes** [comment]
@WhittyPM It's lower priority so not needed for release. I've cleared the milestone but I'm not sure which it should come under. Possibly the next proposal release?

**Comment by WhittyPM** [comment]
@simonfernandes thank you. I have updated the milestone. I don't think we want to be changing the FAP pdfs during LSF round, but maybe I am wrong :)

**Comment by TickleThePanda** [comment]
No longer a problem as we have manual templates.
