### ISSUE TITLE
Investigate and trial set up RabbitMQ in kubernetes

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#298]
For integration with other services (including #169 and #166), we are likely to need RabbitMQ deployed to Kubernetes. This is so we can have other services reacting to events in the proposal submission software.

It looks like there's a way to [install the k8s RabbitMQ operator](https://www.rabbitmq.com/kubernetes/operator/quickstart-operator.html) to make it easier to manage RabbitMQ deployments.

**Comment by mr-field** [comment]
The cluster operator requires Kubernetes 1.18+, but we're on 1.16:

> ### Prerequisites
> Access to a Kubernetes cluster version 1.18 or above

We can use the [Helm package](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq) instead, or deploy the image from the Docker Hub.

**Comment by TCMeldrum** [comment]
Review of what has been done:

RabbitMQ is running on dev and the management UI be accessed on https://devkubernetes.devs.facilities.rl.ac.uk/rabbitmq/ using the username admin and with the password can found in the Kubernetes secrets in bisappsettings. It can be redeployed through this job: https://ci.devs.facilities.rl.ac.uk/job/Dev_Deploy_RabbitMQ/. Currently, it is being run in the default configuration, there is a myriad of options that we could be setting that I have looked at but am unsure what we might want: https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#parameters, but for instance, there may be a way to set up logging: https://www.rabbitmq.com/logging.html. 

One thing I haven't been able to figure out is how to connect to the queue from outside the cluster. Looking online from what I can see there might be some incompatibility with the [ingress](https://stackoverflow.com/questions/61127677/send-messages-to-rabbitmq-from-outside-kubernetes-cluster-using-nginx-ingress)?

**Comment by TickleThePanda** [comment]
I'm not sure (at the moment) we need the queue accessible from outside the cluster but it looks like there's options in the NGINX ingress for [exposing TCP/UDP services](https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/).

**Comment by TickleThePanda** [comment]
@UserOfficeProject/stfc-user-programme. It would be good to have one more comment here with anybody's thoughts (or a summary if it's happened offline).
