### ISSUE TITLE
Train the LSF FAP secretary to make template changes

### ISSUE THREAD

**Issue by WhittyPM** [UserOfficeProject/user-office-project-issue-tracker#304]
These changes include:
 - [ ] #270
 - [ ] #315
 - [ ] #250

**Comment by TickleThePanda** [comment]
@EdwardHaynes. As we discussed earlier, some of the work to make the rest of this round goes smoothly will involve this.

**Comment by TickleThePanda** [comment]
Sarah created and opened the calls for the new LSF rounds.
