### ISSUE TITLE
Round managers will be able to specify questions with answers which link to data from external sources for grants and publications

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#31]
Round managers will be able to specify questions with answers which link to data from external sources for grants and publications to reduce data error when users submit questions with external data

Impacted users: Proposal round managers

Project requirement: [proposal-35](https://stfc365.sharepoint.com/sites/proposals-and-outcomes-transformation-programme/Lists/Proposal%20user%20stories/DispForm.aspx?ID=35)

**Comment by simonfernandes** [comment]
**Notes from meeting with Sukh, Simon, Philip and Emma 12th Dec 2022:**

This requires further discussion between us all.

For this particular issue, we could integrate with Researchfish (for grants from other councils), STFC ePubs (for publications), or ORCID (grants and publications). This will take time and won't be available for ISIS Direct 23/2.

In the shorter term, we could implement users being able to link their ORCID iD with their accounts, although this will require resources from the Users team. In the even shorter term, we could ask the user for their ORCID iD in the questionnaire, but this may have limited usefulness.

**Comment by simonfernandes** [comment]
**Notes from team sprint planning 14th Dec 2022:**

The team agrees that adding a question to ask the user their ORCID iD wouldn't be very useful.

Another possible option may be to allow the user to choose from previously saved sub templates. Sukh is checking this with Emma.

**Comment by simonfernandes** [comment]
> Another possible option may be to allow the user to choose from previously saved sub templates. Sukh is checking this with Emma.

This would be useful, both to copy from a proposal in a previous round, and from a previous proposal in the same round.

See #779 for this feature.

**Comment by simonfernandes** [comment]
Closing this issue to split it up into smaller issues.

Shorter term features:

- https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/779
- https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/812

Slightly longer term features:
- https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/811
- https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/813
