### ISSUE TITLE
Project lacks a shared issue tracker

### ISSUE THREAD

**Issue by mr-field** [UserOfficeProject/user-office-project-issue-tracker#326]
This project currently has two separate issue trackers, one for the STFC and one for the ESS. The ESS tracker is private, so STFC cannot access it. While STFC's tracker is public, ESS has no reason to check it as they use their own.

As a result, STFC does not know about any bugs known to the ESS, each facility has to work on bugs on their own, and it's hard to know what people from different facilities are working on. If this project expands to more facilities in the future, this problem will become even more noticeable.

We need to set up some kind of shared tracker that all facilities can read and edit - ideally a public one, as the project is open-source.

**Comment by mr-field** [comment]
This issue was moved here from another repo. @TickleThePanda commented on 18/10/2021:
> We're going to create a shared JIRA instance with the ESS that can be made public. This, initially, will hold the bugs we're aware of but will have scope to evolve over time. It's on me now to do a few things to get that ready.

**Comment by ACLay** [comment]
We've migrated the STFC issues to this `user-office-project-issue-tracker` repo, and I believe the ESS have a jira sync in place now. Are we looking for further action on this?

**Comment by TickleThePanda** [comment]
I will close this for now. We can review whether this is effective going forward.
