### ISSUE TITLE
Create Message broker documention

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/user-office-project-issue-tracker#329]
We want to have a centralized place where we can list all the information relating to our message brokers. This should include:

- What queues/exchanges we are sending events too
- What events we are sending over to the broker
- What consumers we are running

**Comment by TCMeldrum** [comment]
https://user-office-project.atlassian.net/wiki/spaces/UOP/pages/86867969/Message+Broker

**Comment by simonfernandes** [comment]
These are some of the questions I have as someone learning about this for the first time, if it helps. When you mentioned "exchange" at the end I was (and am still) a bit unclear on where they fit in to this 🙂

> Within duo-message-broker there are 3 queues and 1 defined:

Is there a word missing here?

> Within duo-message-broker there are 3 queues and 1 defined:

Are these bindings of queues on the left to exchanges on the right?

> The data sent over the message queue:

Are these technically exchanges in the middle column?

> It is currently listening to the useroffice.fanout exchange

Would this be the broadcast queue?

**Comment by TCMeldrum** [comment]
Thanks for the feedback! I have updated it to give a quick overview of what an exchange is and provide a little more explanation of using the queue bindings.

Does that make it any clearer?

**Comment by simonfernandes** [comment]
It does - thanks for the extra info!

**Comment by TickleThePanda** [comment]
Looks good to me.
