### ISSUE TITLE
Searching for proposals with an exact date answer doesn't work

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#332]
When searching for proposals by an answer to a question, if you want to check that a date specified is the `Exact` date of a given question, the check doesn't work and no results are shown. If you instead change the search to use the `Before` and `After` operators, the  proposal will be found.

![image](https://user-images.githubusercontent.com/14293717/153030427-159f2ce3-87d6-4668-b6ac-51e01d3de503.png)

**Comment by ZenixTheHusky** [comment]
Closing as non-reproducible on local.

Data on DBs seem correct, and the code seems fine too. Seems to only be an issue with the calls/templates used to create simon's proposals on dev.
