### ISSUE TITLE
No validation on date question min/max when using picker

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#333]
If you create a date question (with time or without) that has a min or max date, the form validation only works when typing a date and not when you use the date picker to select one.

Picked date:
![image](https://user-images.githubusercontent.com/14293717/153038046-1e430047-853b-40fc-a528-e9261810501d.png)

Typed date:
![image](https://user-images.githubusercontent.com/14293717/153038114-b0d5b4fd-ebbd-49c3-954c-1bc380ea86ca.png)

**Comment by ACLay** [comment]
This may be related to #281

**Comment by simonfernandes** [comment]
No longer the case
