### ISSUE TITLE
Improve graphql error handling

### ISSUE THREAD

**Issue by ACLay** [UserOfficeProject/user-office-project-issue-tracker#334]
As discussed on slack a while back:

> [Alex Lay](https://app.slack.com/team/U019X5X6DU1)  [11:03 AM](https://ess-eric.slack.com/archives/C019J2U53U2/p1636455794008300)
Hi folks,
Myself and Tom have been looking at errors returned by the graphql api and were hoping you might be able to share some insight into why it's doing what it is.
The main error class we find is https://github.com/UserOfficeProject/user-office-backend/blob/develop/src/models/Rejection.ts
which is prominently used throughout the API, for reasons ranging from invalid authentication to not being able to find an object with the requested ID.
It seems odd to us though that this class used to flag errors doesn't extend GraphQLError.
This means that the Apollo Studio analytics won't interpret errors as actual errors.
Not using typing also means we have to check the `Rejection` instance in the frontend for hardcoded strings to tell what the problem is, which feels brittle and prone to failure if those strings ever change.
Finally, a lot of Rejection's come from the Authorized decorator which checks if a user is allowed to run a mutation/query.
https://github.com/UserOfficeProject/user-office-backend/blob/develop/src/decorators/Authorized.ts
Something we can't figure out is why mutations result in `Rejection` errors, but queries result in `null`.
Why are these treated differently?
This feels like it's hiding errors that should result in some action.
For instance, if a user is not logged in and requesting data, we'd want to send an error that can be used to redirect them to login, rather than respond with nothing.

> [Fredrik Bolmsten](https://app.slack.com/team/U010DNLLL95)  [2:22 PM](https://ess-eric.slack.com/archives/C019J2U53U2/p1636467731018200)
Hi [@Alex Lay](https://ess-eric.slack.com/team/U019X5X6DU1),
Many good points. After a brief discussion with Jekabs we can give some initial insight on why things are as they are.
> - Regarding the GraphQLError we agree that it should be used, probably just missed to use it before.
> - Regarding not using typings and just using strings this was done to keep it simple. Can you describe the use case you are having? Is it for logging or for showing the user information?
> - It was an active decision on our part to only return Rejection on mutation and not with queries. To put it short a user should not be able to query data that he is not allowed to, so instead of making a complex scheme to handle these cases in the frontend we decided to return the null/[] for easy of use.
>
> We would be happy to continue discussing these points and see if there is some refactoring that is needed.

**Comment by TickleThePanda** [comment]
This has been changed recently by the ESS - errors are native in graphql.
