### ISSUE TITLE
As a developer, I need easy access to all of a proposals answers in a single query

### ISSUE THREAD

**Issue by ACLay** [UserOfficeProject/user-office-project-issue-tracker#337]
When attempting to integrate the UOP proposal system with other STFC systems, it's proved very difficult to extract proposal information and question answers. It sounds as though there's currently no way to make a graphql query for a proposal that includes links to the nested template and question keys from the proposal's answers, meaning multiple queries are needed.

**Comment by simonfernandes** [comment]
It turns out that this is possible, but not necessarily easy to find. I've added some documentation to [Confluence](https://user-office-project.atlassian.net/wiki/spaces/UOP/pages/88047617/Querying+proposal+data+through+the+GraphQL+API).
