### ISSUE TITLE
Is the code coverage accurate?

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#341]
The were some concerns about whether the code coverage is accurate. We should investigate this.

**Comment by vyshnavi1605** [comment]
The code coverage of tests shown on GitHub does seem to be accurate. The lines shown in `uncovered lines` seem to not be covered by the current tests. 

![image](https://user-images.githubusercontent.com/72739242/176920889-b5317d54-1f0c-4f49-8c93-a8bed7acd35f.png)


[here](https://github.com/UserOfficeProject/user-office-backend/blob/develop/src/models/ProposalModelFunctions.ts#L98), the specified line doesn't seem to be covered by the associated test. And lines where a rejection error is returned aren't covered. Do we want those lines to also be covered in the tests?

**Comment by vyshnavi1605** [comment]
Opened issue to add more test coverage: https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/629
