### ISSUE TITLE
Cypress screenshot filenames are too long

### ISSUE THREAD

**Issue by keiranjprice101** [UserOfficeProject/user-office-project-issue-tracker#344]
Some of the filenames of screenshots captured by cypress are too long. 

If you are downloading the artefacts from the actions onto a windows machine, the extraction path of some of the files can be too long and wont extract. This can be worked around by extracting straight to `C:\` but this is not ideal.

Removing the spec name from each file would help, as they are asaved into a different folder per spec anyway.

**Comment by TickleThePanda** [comment]
I can see one of Keiran's initial suggest to remove the spec name from the file? I can see that the spec name is included in the file details in the screenshot API so could that be used to reduce it a little?

**Comment by simonfernandes** [comment]
@TickleThePanda 

The spec name is unfortunately just the filename (e.g. `calls.ts`), which isn't in the actual filename. 

Here's an example of a path:
`C:\Users\gho12479\Desktop\cypress-screenshots\calls.ts\2022-06-30T13.25.33.496Z -- Calls tests -- Call basic tests -- Should have different Question lables for different tables (failed).png`

**Comment by TickleThePanda** [comment]
Then I'm fine with us closing this as "not planned".
