### ISSUE TITLE
As a member of the User Office, I need to know how to process ISIS Rapid proposals for review, to be able to run the review process

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#507]
We need to define a process with the user office for how they should run this process.

Comments from elsewhere: https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/522#issuecomment-1102481263

> The process in the ideal world (as far as I'm aware):
> 1. Proposal is submitted
> 2. Submitted event goes into queue
> 3. Allocations reacts to event and puts the proposal into SharePoint
> 4. _UO processes happen_
> 5. The UO sets the allocations status in SharePoint
> 
> Whether this is the process, that depends on how well the integration has gone at this stage but can comment on that the best.
> 
> If we're a bit behind on the integration:
> 1. Proposal is submitted
> 2. _UO processes happen_
> 3. We manually put the proposal into SharePoint
> 4. The UO sets the allocations status in SharePoint

**Comment by TickleThePanda** [comment]
I think we've had a related discussion in https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/522#issuecomment-1102481263

**Comment by TickleThePanda** [comment]
I think #517 should be automatic now but we can highlight how it works as part of this.

**Comment by simonfernandes** [comment]
I've added documentation to the KnowledgeBase and emailed the User Office a link to it: https://stfc365.sharepoint.com/sites/ICD-UserProgrammeKnowledgeBase/SitePages/Processing-Rapid-Access-proposals.aspx
