### ISSUE TITLE
As a User Officer, I need to know how to download (Rapid Access) proposal PDF so that I can send them off for review

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#517]
The user office will need some basic training for how to access proposal PDFs in the new proposal submission software.

**Comment by TickleThePanda** [comment]
I'm not sure we need to download the proposals like we used to - this should automatically happen when the proposal is submitted as part of our integrations.

Unless I'm missing something?

**Comment by simonfernandes** [comment]
If Allocations puts the proposal PDFs into SharePoint then nothing needs to happen here - the User Office can download it from SharePoint and send it off for review as they normally would.

I had thought that the User Office would have to log onto the proposal site to download the proposal PDFs, in which case they might have needed some training/documentation in how to do so.

**Comment by TickleThePanda** [comment]
Ah, I understand what you mean now - you're right.

**Comment by simonfernandes** [comment]
I've added documentation to the KnowledgeBase and emailed the User Office a link to it: https://stfc365.sharepoint.com/sites/ICD-UserProgrammeKnowledgeBase/SitePages/Processing-Rapid-Access-proposals.aspx

**Comment by sukhsingh2525** [comment]
Having spoken to Emma, UO would like a live demo of this. 
Demo to be arranged with the following users:

Lisa Wiltshire
Emma Roberts
Kerry Larman
Marie Richer
Emma G (dependent on availability)

**Comment by simonfernandes** [comment]
Demo arranged for next Tuesday 28th

**Comment by simonfernandes** [comment]
Closing as done
