### ISSUE TITLE
Create test ISIS Rapid questionnaire on dev

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#520]
We have an proposed questionnaire documented in the [project documentation](https://stfc365.sharepoint.com/:w:/r/sites/ISISProject-1102/_layouts/15/Doc.aspx?sourcedoc=%7B7C2AAE0A-BC21-4849-ADB0-964FCDDBBEF3%7D&file=Proposed+questionnaires+V+1.0.docx&action=default&mobileredirect=true&isSPOFile=1).

**Comment by EdwardHaynes** [comment]
I've made the first pass over the existing questions on dev and made a questionnaire from the existing questions. 

There are several missing that I'll need to add based on the RA submission process on the old proposals system. They are as the following:

```
Questions that are missing:

- Special case for Rapid Access - Text

- Has this or a similar proposal been submitted to another facility recently? - Bool
- Indian researchers -  Checkbox
- PhD Students on this proposal

- Days requested - Currently weeks
- Would you like to specify a local contact? - Bool
- Have you discussed the experiment with the local contact? - Bool
- Special requirements of instrument - Currently laser
- Would you consider any other instrument to be suitable for your experiment? Bool
	- Instrument list id yes to above

- Samples - May be missing some fields

- Other facilities - Such as Diamond etc.

```

**Comment by simonfernandes** [comment]
Just a small thing on this @EdwardHaynes, since we'll be demoing it

The Rapid call that you create needs to have a workflow that doesn't allow the proposal to be editable after submission.
