### ISSUE TITLE
Test that a minimal ISIS SharePoint proposal will work for Rapid

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#522]

**Comment by TickleThePanda** [comment]
I have created a test ISIS proposal in the dev list that doesn't have a proposal in our legacy or new proposal submission software. Once the proposal list cache picks this up, we're able to schedule.

I think this confirms that we're able to run ISIS experiments, as long as SharePoint is updated with the correct information (without additional sync from).

This is not the ideal long term solution:
 - We haven't tested post-delivery integrations.
 - We want to get rid of SharePoint in the future.
 - Some of the information when creating the proposal is missing.

But I think it meets our minimum requirements to release to Rapid.

<html>
<body>


RB | 2300000
-- | --
FAP |  
RBno | 2,300,000
Principal Investigator |  
Access Route | Direct Access - New
Requested Time |  
Country |  
Round | 2023_0
Instrument |  
Alternative Instruments |  
Organisation |  
Department |  
FAP_Review |  
Notes |  
EU_Support_Request | No
User_Number | 1,085,279
User_Office_Note |  
UN | 1085279
Local_Contact |  
Local_Contact_UN |  
Proposal |  
Programme_Access_Ref |  
Allocated Time | 2
Rating |  
Feedback |  
Instrument_Allocated | ARGUS
Experiment_Contact |  
Experiment_Contact_UNno |  
EU_Accepted | No
Date_Submitted |  
Local_Contact_Allocated |  
Previous_Experiment |  
EU_Support_Country |  
EU_days |  
EU_Eligible | No
Sent | No
email_PI |  
email_Experiment_Contact |  
Abstract |  
Title | My test title.
Establishment_ID |  
AlignmentRequired | No
Report |  
EUFP |  
Resource |  
Country* |  
Year* | 2023
Rapid_Access_Case |  
Instrument Requested* | 0
ScienceProgramme |  
Newton_Funding_Requested | No
Newton_Funding_Accepted | No


</body>
</html>

**Comment by simonfernandes** [comment]
Seems fine to me if this is the minimum information that the Scheduler needs. 

Will it be instrument scientist schedulers that are responsible for adding this entry? Will they need documentation?

**Comment by TickleThePanda** [comment]
The process in the ideal world (as far as I'm aware):
1. Proposal is submitted
2. Submitted event goes into queue
3. Allocations reacts to event and puts the proposal into SharePoint
4. _UO processes happen_
5. The UO sets the allocations status in SharePoint

Whether this is the process, that depends on how well the integration has gone at this stage but I think @TCMeldrum and @ACLay can comment on that the best.

If we're a bit behind on the integration:
1. Proposal is submitted
2. _UO processes happen_
3. We manually put the proposal into SharePoint
4. The UO sets the allocations status in SharePoint

**Comment by ACLay** [comment]
We have the allocations-new proposals message queue integration set up on dev and all going well will be rolling it out to prod at noon tomorrow

**Comment by TickleThePanda** [comment]
Closed following discussion. Full process can be defined as part of #507
