### ISSUE TITLE
Disable and hide parts of the frontend

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#54]
This should disable or hide parts of the front-end that are either unusable or that we don't want our users to use.

Related to #44 and #45, there are parts of the software that STFC will not support in their running instance and are set to throw errors (for example, changing a user's password, granting a user roles, deleting a user). We should "disable" these parts to avoid confusion and make the UI more intuitive. This may involve disabling or hiding parts of the interface, and adding information or pointers directing to our facilities site.

/overwrite opened 2020-09-04

**Comment by TickleThePanda** [comment]
I think the fix for SWAP-756 has introduced a framework for this. We need to implement the same for the remaining features.

See https://github.com/UserOfficeProject/user-office-backend/pull/125 and https://github.com/UserOfficeProject/user-office-frontend/pull/183 for how that was done.

**Comment by TickleThePanda** [comment]
Consider also within this: disabling API methods.

**Comment by TheCyalex** [comment]
features we need: user submitting proposal, staff being able to create calls/rounds, questionnaires, we dont want any user management

**Comment by TickleThePanda** [comment]
Split into #508 and #523
