### ISSUE TITLE
Create a test call on prod for ISIS instrument scientists to use

### ISSUE THREAD

**Issue by sukhsingh2525** [UserOfficeProject/user-office-project-issue-tracker#583]
As part of testing the new proposal system for ISIS rapid we want to create a test site on prod:

- [x] Create a test call
- [x] Draft an email which will be sent out to the ISIS staff users
- [x] #610 
- [ ]  Update the workflow the test call is based on (see [reply below](https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/583#issuecomment-1158907823))
- [ ] Update the call end date once decided

**Comment by TickleThePanda** [comment]
Blocked by #526

**Comment by simonfernandes** [comment]
One of the remaining things we need to do (that I was hoping to take care of this afternoon before the downtime) is to change the workflow on the test call.

I believe we need to make the "Submitted (locked)" status an upcoming status that is triggered by the proposal_submitted event. Without this, the proposal will still submit fine and give the correct non-editable submit confirmation message, but it will show as "Draft" in the instrument scientist proposal table view which could be misleading.

More info: https://ess-eric.slack.com/archives/C019J2U53U2/p1655471315477889?thread_ts=1655469241.580719&cid=C019J2U53U2

Screenshots from local:

![image](https://user-images.githubusercontent.com/14293717/174311485-130c3f26-e6a6-4e9b-a1af-ee6ae084062b.png)
![image](https://user-images.githubusercontent.com/14293717/174311295-cf0fd488-f4c0-4548-a4a8-8cd7614c6cc9.png)

**Comment by TickleThePanda** [comment]
Sent email today.

> Dear all,
> 
> We have made the new proposal submission software available for you to submit and view test proposals. The deadline for testing is Friday 24th June at 5pm.
> 
> You will have the opportunity to [submit feedback](https://forms.office.com/r/WreS36zeZ3) after you have submitted a proposal. While we will not be able to address all feedback before opening the Rapid Access call, it will be valuable in helping us to plan and prioritise future development.
> 
> A brief summary of how to submit a test proposal and view other test proposals is included below. Further information is available via documentation on our [KnowledgeBase](https://stfc365.sharepoint.com/sites/ICD-UserProgrammeKnowledgeBase/SitePages/Proposal-system.aspx), which includes links to [guidance for users](https://stfc365.sharepoint.com/sites/ICD-UserProgrammeKnowledgeBase/SitePages/Proposal-system-for-users.aspx) (submitting a proposal) and [instrument scientists](https://stfc365.sharepoint.com/sites/ICD-UserProgrammeKnowledgeBase/SitePages/Proposal-System-for-Instrument-Scientists.aspx) (viewing proposals). If you have any issues accessing the site, please contact our support inbox [facilitiesbusinesssystem@stfc.ac.uk](mailto:facilitiesbusinesssystem@stfc.ac.uk).
> 
> We are aware of two issues and we will be working on a fix. They are related to filtering proposals:
> •	Showing all proposals that have requested a single instrument may involve having to search multiple questions.
> •	It is difficult/unclear how to search questions that ask for a numerical range (e.g. sample pressure range).
> 
> Moving to the new proposal system provides many benefits both for users and staff:
> •	The software is faster and more reliable.
> •	You will now be able to see all of the details of future proposals submitted to ISIS.
> •	You can filter proposals by the answers to questions.
> 
> The release for the ISIS Rapid call is due to take place over the coming weeks. The new site will be used for the Direct Access call which has a deadline of Wed 19th October.
> 
> Kind regards,
> Proposals and Outcomes team
> 
> ________________________________________
> To submit a test proposal
> (Detailed documentation available via [guidance for users](https://stfc365.sharepoint.com/sites/ICD-UserProgrammeKnowledgeBase/SitePages/Proposal-system-for-users.aspx))
> 1.	Access the new proposal system at https://proposal.facilities.rl.ac.uk/ and log in with your Facilities account if requested.
> 2.	Click the “New Proposal” tab on the left sidebar.
> 3.	Select the “Test for ISIS Rapid” call.
> 4.	Complete the questionnaire and submit the proposal.
> 
> To locate and view proposals
> (Detailed documentation available via [guidance for instrument scientists](https://stfc365.sharepoint.com/sites/ICD-UserProgrammeKnowledgeBase/SitePages/Proposal-System-for-Instrument-Scientists.aspx))
> 1.	Access the new proposal system at https://proposal.facilities.rl.ac.uk/ and log in with your Facilities account if requested.
> 2.	Switch your role by clicking on the account icon in the top right and selecting the “Instrument Scientist” role.
> 3.	Ensure you are on the “Proposals” tab on the left sidebar.
> 4.	Explore the different [filtering and searching](https://stfc365.sharepoint.com/sites/ICD-UserProgrammeKnowledgeBase/SitePages/Proposal-System-for-Instrument-Scientists.aspx#filtering) options
> 
> 
> To raise a support ticket for any of the User Programme software please email [facilitiesbusinesssystem@stfc.ac.uk](mailto:facilitiesbusinesssystem@stfc.ac.uk). 
> To receive notifications about the service please subscribe to one of our mailing lists, either for [our users](https://listserv.stfc.ac.uk/scripts/wa.exe?SUBED1=BUSINESS-APPLICATION-USERS&A=1) or [our web service API consumers](https://listserv.stfc.ac.uk/scripts/wa.exe?SUBED1=BUSINESS-APP-SERVICE-CONSUMERS&A=1)
