### ISSUE TITLE
Inconsistent GraphQL and UI behaviour when updating multiple choice question options

### ISSUE THREAD

**Issue by ACLay** [UserOfficeProject/user-office-project-issue-tracker#585]
- GraphQL retains references to their original options, as well as their current options  
  <details>
  <summary>Sample query and response (on devproposal.facilities.rl.ac.uk)</summary>

  ```
  query BlankQuestionarySteps($templateId: Int!)  {
    blankQuestionarySteps(templateId: $templateId) {
      fields {
        question {
          naturalKey
          question
          config {
            ...on SelectionFromOptionsConfig {
              options
            }
          }
        }
        config {
          ...on SelectionFromOptionsConfig {
            options
          }
        }
      }
    }
  }

  {
    "templateId": 28
  }
  ```
  ```
  {
    "data": {
      "blankQuestionarySteps": [
        {
          "fields": [
            {
              "question": {
                "naturalKey": "proposal_basis",
                "question": "Proposal basic information",
                "config": {}
              },
              "config": {}
            },
            {
              "question": {
                "naturalKey": "Multichoice_test",
                "question": "Are the graphql responses just using the first edit",
                "config": {
                  "options": [
                    "Initial option 1",
                    "Initial option 2. Will be removed"
                  ]
                }
              },
              "config": {
                "options": [
                  "Initial option 1",
                  "Newer 3rd option",
                  "New 4th option"
                ]
              }
            }
          ]
        }
      ]
    }
  }
  ```
  </details>
- Regardless of which options delete button gets pressed, only the final one will be deleted
  <details>
  <summary>Screenshots</summary>
  
  ![image](https://user-images.githubusercontent.com/2938284/171037073-827cefbc-dfbf-4c8e-ad98-98b5aa0791af.png)
  ![image](https://user-images.githubusercontent.com/2938284/171037117-3b307fa2-c476-43c5-ba79-d5f4bd1e1073.png)
  ![image](https://user-images.githubusercontent.com/2938284/171037147-eedb7968-14e9-4c01-99a3-3f05f300b34d.png)

  </details>

**Comment by ACLay** [comment]
Additional points of weirdness:
- In the question drawer of the proposal template editor you can successfully add new items to the base question, update the title, but you can't alter the value of an existing item.
- Altering those details in a template's question drawer updates the properties on the base question. This feels like editing for a template rather than the base question, which can also be updated in the Questions page. It doesn't seem clear which version is being edited.

**Comment by mutambaraf** [comment]
Will close this because it was fixed with this PR https://github.com/UserOfficeProject/user-office-frontend/pull/976
