### ISSUE TITLE
Train Emma Gozzard to modify the questionnaire

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#611]
Train Emma Gozzard on how to modify the questionnaire. Training for creation of it can be done at a later date.

We may want to include other people in this training, but we can ask Emma who she would like included.

We probably want this to be one-to-one training rather than documentation, as written documentation will likely be time consuming and not as effective.

**Comment by simonfernandes** [comment]
@EdwardHaynes I think you may have completed this with Emma already, recently? Emma mentioned she'd already had some training on this or similar. We can close if so

**Comment by EdwardHaynes** [comment]
> @EdwardHaynes I think you may have completed this with Emma already, recently? Emma mentioned she'd already had some training on this or similar. We can close if so

Yea I think we can. She knows the basics and knows who to contact if she has questions.

**Comment by TickleThePanda** [comment]
Just saw this - closing it now.
