### ISSUE TITLE
Implement the layout for ISIS in the proposal submission software

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#614]
Using the results of #249 and #613, implement the layout for ISIS.

We should consider whether we want to also add this to version control somewhere.

**Comment by TickleThePanda** [comment]
Can we delay the completion of this until October?

**Comment by TickleThePanda** [comment]
Defined layout: https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/249#issuecomment-1204044218

**Comment by TickleThePanda** [comment]
For documents, see [teams](https://stfc365.sharepoint.com/:f:/r/sites/isiscomputingdivision-staffsite/Shared%20Documents/Proposals%20and%20Outcomes/Proposal%20documents?csf=1&web=1&e=ZoeeGZ). I didn't upload to here for private info.

**Comment by TickleThePanda** [comment]
Tested in my local environment using an import of the prod questionnaire. Relies on:
 - https://github.com/UserOfficeProject/user-office-backend/pull/716
 - https://github.com/UserOfficeProject/user-office-backend/pull/721
 - https://github.com/UserOfficeProject/user-office-frontend/pull/988
 - https://github.com/UserOfficeProject/user-office-frontend/pull/996
 - https://github.com/UserOfficeProject/user-office-factory/pull/125

**Comment by mutambaraf** [comment]
The  documents looks great and very eligible .If possible we can also include page numbers , also some of the data can also be displayed as tables  and lastly separation may look nice with (:) colons .The above are just  minor cosmetics  .

> For documents, see [teams](https://stfc365.sharepoint.com/:f:/r/sites/isiscomputingdivision-staffsite/Shared%20Documents/Proposals%20and%20Outcomes/Proposal%20documents?csf=1&web=1&e=ZoeeGZ). I didn't upload to here for private info.

**Comment by mr-field** [comment]
I'd make titles a bit bigger compared to normal text. For example, the "Grants" title doen't look much bigger than the bold text under it, so it's hard to see that it's a title. Maybe some `<hr>`s under titles would also improve visual separation between sections, a bit like the title below?

## A title
Text under a horizontal line

Other than that, it looks good to me.

**Comment by TickleThePanda** [comment]
Updated following comments. I've not used tables everywhere as it makes the markup more complex. As these are combined further into a larger booklet, I'm not doing page numbers.

I've added a [version made on dev](https://stfc365.sharepoint.com/:b:/r/sites/isiscomputingdivision-staffsite/Shared%20Documents/Proposals%20and%20Outcomes/Proposal%20documents/2022_Attwood_523257%20(28).pdf?csf=1&web=1&e=q8JGoq) which has less info but shows the new style.

**Comment by mr-field** [comment]
Looks good to me 👍

**Comment by TickleThePanda** [comment]
Released onto prod: https://proposal.facilities.rl.ac.uk/PdfTemplateEditor/33
