### ISSUE TITLE
Multiple questions are used to ask which instrument is requested and we need only one

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#616]
I noticed that for the ISIS Rapid questionnaire, we now ask the user which scientific technique (Reflectometry, Imaging, etc.) they require, and depending on the answer to this question, we then ask them "What instrument?". 

Because "What instrument?" is a drop-down question and not all instruments are available for all techniques, this means that there are multiple of the same question in the questionnaire where only one will display to the user depending on the technique they pick.

The problem is that when you try to search for proposals based on how they've answered questions, all of those questions are displayed. There is no way of knowing which "What instrument?" question relates to which technique, so filtering proposals by instrument becomes difficult.

<img src=https://user-images.githubusercontent.com/14293717/174083800-d0217af2-fd64-430c-93ad-fbb2c936a2e5.png width=200>
<img src=https://user-images.githubusercontent.com/14293717/174084391-ed177a28-c69f-4818-bc92-e0e14cf25b91.png width=200>

**Comment by TickleThePanda** [comment]
Ah, good point. Do you think we could introduce a dependency that would filter available responses depending on another answer?

**Comment by keiranjprice101** [comment]
@simonfernandes Unless I am misunderstanding, this does not seem to be an issue in ISIS Rapid.
![image](https://user-images.githubusercontent.com/44777678/178957296-fd512da4-53b9-46f7-92ff-12a56df8019f.png)

**Comment by TickleThePanda** [comment]
Sorry, I fixed the question text for each. The problem is still that we have many "What <x> instrument?", we fixed the usability side a bit, here.

**Comment by TickleThePanda** [comment]
The question we're looking to use this is multi part.

Part 1 is the technique, which is a lis

**Comment by simonfernandes** [comment]
**Notes from meeting with Sukh, Simon, Philip and Emma 12th Dec 2022:**

The questionnaire will be changed so that we ask the user for the instrument and then the technique. I.e. the instrument will no longer be based on the chosen technique. P&O to discuss whether this will still be relevant for the next Direct round or have other future uses.

**Comment by simonfernandes** [comment]
We still need to go ahead with this questionnaire change. Emma will handle most questionnaire changes, but P&O will handle this one as it will have implications with Allocations.

The implementation should be:
> Emma:
> I think selecting the instrument and then the technique from the full list is fine here.

The reason for doing this is:

> Emma:
> There were a few complaints from submitters that the instrument they wanted to select wasn’t available for the technique they requested (which does happen as there are exceptions).  Also, having the questions this way around will allow instrument scientists to filter by an instrument and see all proposals, without worrying about doing this for multiple techniques.

**Comment by Scott-James-Hurley** [comment]
The ISIS Direct and ISIS Rapid proposal templates have been updated so that users are first asked what instrument they are using (from the full list) then what scientific technique they are using. PDF templates have been updated accordingly.
