### ISSUE TITLE
Not receiving confirmation email when proposal is submitted 

### ISSUE THREAD

**Issue by sukhsingh2525** [UserOfficeProject/user-office-project-issue-tracker#617]
Emma/Phillip didn't receive a confirmation email when they submitted a test proposal on the new system. Please can this be looked into as a matter of urgency?

**Comment by TickleThePanda** [comment]
Was to do with call names.

**Comment by TickleThePanda** [comment]
Needs some additional config released.

**Comment by TickleThePanda** [comment]
https://git.devs.facilities.rl.ac.uk/isisbusapps/BisAppSettings/pulls/2

**Comment by TickleThePanda** [comment]
Confirmed fixed now.
