### ISSUE TITLE
Review feedback from ISIS staff and make any changes to questionnaire

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#619]
We should consider doing any additional changes alongside Emma to start handing over questionnaire work.

**Comment by TickleThePanda** [comment]
We're going to do this iteratively over the next few months for Direct. I'm moving this across to Sukh as he's doing this at the moment.

**Comment by sukhsingh2525** [comment]
Have arranged a meeting with Ed/Simon to go through the changes and assess the priority for each. Will require involvement from Emma at some point.

**Comment by simonfernandes** [comment]
Issues created from feedback:
#631
#632
#633
#634
#635
#636

@sukhsingh2525 Do you think this covers everything so that it can be closed?

**Comment by simonfernandes** [comment]
@sukhsingh2525 Can this be closed now? I know the issue says to make the changes, but we have made all changes to the Rapid questionnaire, and for ISIS Direct we have opened new issues.

**Comment by sukhsingh2525** [comment]
We've gone through the feedback from the questionnaire that we did for the test call on prod as well as the feedback from the Muon group. As a result we've created issues on GitHub  with input from Emma, as per Simon's comment above.
