### ISSUE TITLE
PDF upload for Science Case Upload not working during Rapid testing

### ISSUE THREAD

**Issue by sc19ew** [UserOfficeProject/user-office-project-issue-tracker#625]
PDF upload gives `Error: "Can not answer topic because provided value is not satisfying constraint"` when completing Science Case Upload after uploading a pdf within the allowed size constraints.

**Comment by martin-trajanovski** [comment]
Hi @sc19ew I think I noticed the same issue and tried to fix it here: https://github.com/UserOfficeProject/user-office-backend/pull/668. Once we merge this PR it should be fixed but we can re-test 🧪. Thanks for bringing this up 💯

**Comment by simonfernandes** [comment]
I'm sorry, that's my fault. I couldn't see a fix in your PR @martin-trajanovski but maybe I missed it? [This commit here](https://github.com/UserOfficeProject/user-office-backend/compare/master...hotfix-fix-unlimited-pdf-pages?expand=1) is what I was going to release as a hotfix but all of us at STFC are unavailable today so it would have to wait until tomorrow. So maybe you can cherry-pick this commit into your PR. 

Until it's fixed, if you have any active calls on your production site that accept PDFs, please change the limit from 0 (supposed to be unlimited) to a high number instead. I have done this for STFC already.

**Comment by martin-trajanovski** [comment]
> I'm sorry, that's my fault. I couldn't see a fix in your PR @martin-trajanovski but maybe I missed it? [This commit here](https://github.com/UserOfficeProject/user-office-backend/compare/master...hotfix-fix-unlimited-pdf-pages?expand=1) is what I was going to release as a hotfix but all of us at STFC are unavailable today so it would have to wait until tomorrow. So maybe you can cherry-pick this commit into your PR.
> 
> Until it's fixed, if you have any active calls on your production site that accept PDFs, please change the limit from 0 (supposed to be unlimited) to a high number instead. I have done this for STFC already.

@simonfernandes thanks for your comment. I can wait for your fix and then pull into my branch no worries.
