### ISSUE TITLE
Release changes for ISIS Rapid

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#64]
Issue to release for ISIS Rapid. This needs to follow the comms plan for the area.

 - [x] Correct version of allocations is released to enable integration with SharePoint
 - [x] Correct version of RabbitMQ is released to enable integration with SharePoint
 - [x] Correct versions of UOP are released

At the moment, this should include rapid access for RIKEN.

/overwrite opened 2020-09-04

**Comment by ACLay** [comment]
We're gonna need to do a hotfix of Authenticate with this. The ESS changed the external auth login URL, so we'll need to update the prod auth homepage tile links

**Comment by mr-field** [comment]
Most of the Rapid changes have been released in https://github.com/isisbusapps/docker-orchestration/pull/256, which was done earlier than planned to fix an important security issue and a seruious bug. I'm not sure if we still need another release before Rapid opens.

**Comment by ACLay** [comment]
We need to do a bisappsettings release to get the updated email templates out so the ISIS user office will sign off on the system.

BisAppSettings PR is https://git.devs.facilities.rl.ac.uk/isisbusapps/BisAppSettings/pulls/1

**Comment by ACLay** [comment]
Cherry pick recreated PR: https://git.devs.facilities.rl.ac.uk/isisbusapps/BisAppSettings/pulls/2

**Comment by mr-field** [comment]
All Rapid code changes have been released. The only change left might be a tile in Auth when we actually open Rapid.
