### ISSUE TITLE
Find a solution for creating proposals that have been approved through Diamond's collaboration with ISIS

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#640]
Through a collaboration, Diamond is able to allocate time to ISIS. Users request beamtime to ISIS through the Diamond proposal submission software alongside their Diamond proposal. ISIS reviews the feasibility of each of these and then the experiment is reviewed by Diamond's FAP(s). If Diamond approves the proposal, we need to be able to schedule the proposal and provide some basic reporting on it (that it exists).

There was a unknown workaround in place for this before but we're currently unsure what this is.

Our initial suggested solution is for Emma/User Office to:
1. Create a new template for the Diamond
2. Use the template to create a short lived call with a new reference number pattern
3. Submit the proposals to the short lived call
4. Update the allocated time in SharePoint

This is needed early 2023 after the next Diamond call. We should consider the output of #622 for the solution of this.

**Comment by ACLay** [comment]
Everything in this route would be pre-approved, so I don't feel like it's a good fit for going through proposal submission. Given that the long term goal for #301 is a separate UI for adding pre-approved proposals directly to allocations, I think we should probably aim to have that also support these pre-approved diamond/isis proposals. That way we'd also avoid adding new processes that interact with sharepoint.

**Comment by ACLay** [comment]
Do we know what sort of volume of joint ISIS diamond proposals we might expect?

It will affect the needs of the web interface if we need to handle individual experiments or bulk submissions after diamond completes their proposal rounds.

**Comment by ACLay** [comment]
> If Diamond approves the proposal, we need to be able to schedule the proposal and provide some basic reporting on it (that it exists).

I've looked through the excel document containing the April 2022 shared ISIS/Diamond proposals sent to us by the user office. Of the 11 proposals detailed, 9 list ISIS as their lead facility and already have RB numbers. The two that originated at Diamond already exist in our proposal system, actually created by their PI's according to the modified_by column. Then in the sharepoint lists, they have rejections in the FAP feedback columns. It doesn't look like this is actually a route for pre-approved proposals. Or at least it doesn't seem to have been treated that way historically

**Comment by srconway** [comment]
Has Philip King mentioned this at all - it would be good to work out what the previous solution was - my understanding from Andrew Kaye (which I may be mis-remembering) was that it's been an issue for a while and they just submitted a normal ISIS proposal with some sort of note or tick box to highlight that it was linked to a Diamond proposal. Either way it sounds like it needs to go through an ISIS feasibility review if nothing else so whilst the tool in #301 probably doesn't need to know the background as to why something is pre-approved it would be useful to pin down the process (ICRD proposals are pre-approved and could go that route too)

**Comment by ACLay** [comment]
The plan is to allow these to be created via the new approved experiments webapp, due to release in the next sprint https://github.com/isisbusapps/approved-experiments/issues/35
