### ISSUE TITLE
As a user officer or instrument scientist, I need the PI name in the proposal table list

### ISSUE THREAD

**Issue by vyshnavi1605** [UserOfficeProject/user-office-project-issue-tracker#642]
User Officers and instrument scientists have said that they need additional information in the proposal table list so that they can more efficiently find and navigate proposals.

---

> Feedback from Emma G from [ISIS Direct feedback document](https://stfc365.sharepoint.com/:w:/r/sites/isiscomputingdivision-staffsite/_layouts/15/Doc.aspx?sourcedoc=%7BCAFB6AF8-EB88-4909-9BDC-D01E031780E0%7D&file=ProposalSystemFeedback.docx&action=default&mobileredirect=true&cid=01f1cc1f-a82f-4596-85c5-3339298ce341):
> Proposal system dashboard view needs to have columns showing:  PI, time requested (days for ISIS, weeks for CLF) and instrument (ISIS instrument, CLF facility – Vulcan, Octopus, etc.).  Without these headings, navigating proposals in the system is currently almost impossible for myself and instrument scientists from both facilities. 
---
> Anonymous user from [ISIS Direct feedback document](https://stfc365.sharepoint.com/:w:/r/sites/isiscomputingdivision-staffsite/_layouts/15/Doc.aspx?sourcedoc=%7BCAFB6AF8-EB88-4909-9BDC-D01E031780E0%7D&file=ProposalSystemFeedback.docx&action=default&mobileredirect=true&cid=01f1cc1f-a82f-4596-85c5-3339298ce341):
Secondly, a suggestion – when logged in as instrument scientist and viewing the proposals that are draft/submitted, it would be really helpful to have a column showing the PI for that proposal (perhaps in the dropdown as in the screenshot, below). Sometimes it’s far easier to scan for a person than it is to look through the titles. I’m also assuming that at some point it will be possible to filter by instrument using the “instrument” filter, rather than having to go through the “more” and finding a suitable question?
---
> Instrument scientist feedback:
For future rounds on the proposal system would it be possible to add to the show column feature the ability to show the Principle Investigator?
---
![image](https://user-images.githubusercontent.com/72739242/179769233-a47675bc-9873-4c27-91a5-ebf9abe993dd.png)

**Comment by georgeflecknell** [comment]
For Sarah Needham.

**Comment by simonfernandes** [comment]
I've amended this issue to include more than the PI name, based on additional ISIS Direct feedback.

**Comment by simonfernandes** [comment]
**Notes from meeting with Sukh, Simon, Philip and Emma 12th Dec 2022:**

As a minimum, we need the columns stated by Emma above (PI, time requested (days for ISIS, weeks for CLF) and instrument (ISIS instrument, CLF facility – Vulcan, Octopus, etc.).

**Comment by simonfernandes** [comment]
PI name in the first instance would be really useful for Emma. The rest of the info can be done via reporting: https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/775.
