### ISSUE TITLE
Reordering or adding multiple choice questions to proposal questionnaires doesn't work properly 

### ISSUE THREAD

**Issue by EdwardHaynes** [UserOfficeProject/user-office-project-issue-tracker#643]
When modifying (reordering and deleting) existing answers for multiple choice questions, answers are overwritten or duplicated. This makes working with these questions very difficult and often requires deleting and re-add all answers when trying to modify a single existing answer. See below for example:

Existing question and answer:
![image](https://user-images.githubusercontent.com/20170535/179986174-5865da3e-4e7d-436e-aa0f-a61eb3f1e969.png)

After reordering 'Option 1' down to the last position using down arrow:
![image](https://user-images.githubusercontent.com/20170535/179986528-d85c6d2c-c65c-44ea-a70b-724d900a52d7.png)

After trying to delete 'Option 3' using the bin (wrong answer - option 5 - deleted instead:
![image](https://user-images.githubusercontent.com/20170535/179986774-9766a916-c7f8-4dfc-94cb-7b329e1ab6e2.png)

I'll leave the question on the template editor for whoever picks this up.

**Comment by simonfernandes** [comment]
@EdwardHaynes Is this the same as https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/626?

**Comment by TickleThePanda** [comment]
Duplicate of #626 and #644
