### ISSUE TITLE
Ensure PI proposal confirmation emails are sent

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#648]
(Separate from https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/630, which we agreed will be a more substantial issue to solve)

We need some way of ensuring PIs confirmation emails are sent. This may involve adding additional logging or some other checks so that we're aware of when they have failed to send, and a system in place to resend (even if manual).

**Comment by TickleThePanda** [comment]
Logging, at minimum, when:
 - Template not found
 - Nodemailer fails to send email to recipient
 - On success

**Comment by simonfernandes** [comment]
By a new view, I think we mean something like a new [Dashboard](https://logs.devs.facilities.rl.ac.uk/app/dashboardsv) that we could check each morning:

![image](https://user-images.githubusercontent.com/14293717/184107285-2ef9542e-c201-4409-a3d2-07dbe1854387.png)

**Comment by mutambaraf** [comment]
Proposal emails logs view for dev and prod servers 
Dev Server: [Proposal submission emails dev](https://devlogs.devs.facilities.rl.ac.uk/app/dashboards#/view/bd17cc10-1a2c-11ed-9c72-67a3fca0a452?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1y,to:now)))
Prod Server: [Proposal submission emails prod](https://logs.devs.facilities.rl.ac.uk/app/dashboards#/view/93ab7340-1a31-11ed-9e06-25fcef67cd85?_g=h@c823129)

**Comment by TickleThePanda** [comment]
I'm happy with these views. I'd recommend we add prod to a new list on our wiki page to check during proposal submission periods.

**Comment by ACLay** [comment]
The prod link defaults to the last 15 minutes for me. Can it be adjusted to show the whole of the last day

**Comment by mr-field** [comment]
Looks good to me. The link may need adjusting though, I get an warning on Elastic when i click it ("Unable to completely restore the URL, be sure to use the share functionality."). To be safe, it would be best to generate the link using the "Share" -> "Permalink" option (assuming it doesn't do weird things with the time interval).

**Comment by mr-field** [comment]
:+1

**Comment by mutambaraf** [comment]
> I'm happy with these views. I'd recommend we add prod to a new list on our stand-up wiki page to check during proposal submission periods.

Given the above reviews the production view will be added to the morning stand-up meeting and l will proceed to close this issue.
