### ISSUE TITLE
As a PI I want a message pop up after submitting a proposal

### ISSUE THREAD

**Issue by sukhsingh2525** [UserOfficeProject/user-office-project-issue-tracker#652]
When a proposal is submitted it would be good to have a message pop up when a proposal is submitted something like "Your proposal has been submitted successfully. You will receive a confirmation email in due course". 

This is to avoid PIs submitting multiple submissions who do not get an immediate email confirmation. 

This is not a Must have for release but it would be good if we can.

**Comment by TickleThePanda** [comment]
This is possible, we just need to make sure the real call has the right text. Work with Emma G on this.

**Comment by TickleThePanda** [comment]
Short term, use the submission message and clarify "editable before call", longer term add a new popup/notification after submission.
