### ISSUE TITLE
Amending the questionnaire based on feedback

### ISSUE THREAD

**Issue by sukhsingh2525** [UserOfficeProject/user-office-project-issue-tracker#654]
These are some of the questionnaire changes 

- [x] On the first page '[summary information available](https://www.clf.stfc.ac.uk/Pages/Submit-a-proposal.aspx) this links to CLF page rather than an ISIS page.

 ![image](https://user-images.githubusercontent.com/55693331/185154149-c434d9f1-adef-4eb7-ba5d-3d852fa60d3d.png)

- [x] On step 3 I could progress without adding any publications – this may be by design but just thought I would check in case it wasn’t. Add a wording- 'Your publication record from previous ISIS experiments is taken into account'

- [x] On step 4 I select Direct Access – New and I am still asked for the reference number of my previous proposal and I wasn’t sure if this was right (it is required)

**Comment by TickleThePanda** [comment]
This is complete.

**Comment by TickleThePanda** [comment]
This is complete.
