### ISSUE TITLE
Release for ICRD

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#66]
Issue to release for ICRD. This needs to follow the comms plan for the area.

 - [ ] Create and test workflow for area
 - [ ] Create and test questionnaire
 - [ ] Test permissions
 - [ ] Test integrations

/overwrite opened 2020-09-04

**Comment by Cat-Lucifer** [comment]
@sukhsingh2525 @georgeflecknell I have had a meeting with Chris Frost and agreed to use the `Approved experiments` tile to get ICRD experiments in the system and pushed to the scheduler.  This should allow us to cease entering of ICRD experiments via the legacy system.

The tile wasn't working for me until recently, so I have a demo planned for Chris and the ISIS industry PA to talk them through the data entry, with a view that the PA will enter and create ICRD going forward.

If all is well with this meeting (I'm fully expecting it to be) then I will action for the PA to have permission to use the tile.
