### ISSUE TITLE
Generic templates don't show friendly message if you don't add one and it's required

### ISSUE THREAD

**Issue by sukhsingh2525** [UserOfficeProject/user-office-project-issue-tracker#662]
On tab 5 when press I Save and Continue without having added any samples, I get a slightly unintuitive red message saying “Please add at least 1 genericTemplate(s)” whereas “Please add at least one sample” would be more helpful or just “Please add at least 1” (i.e. scrap the “genericTemplate(s)” bit

**Comment by simonfernandes** [comment]
**Notes from meeting with Sukh, Simon, Philip and Emma 12th Dec 2022:**

It's important to have friendly error messages so that we look professional.

**Comment by simonfernandes** [comment]
Is this now complete @bashanlam? Can you close it off if so?

**Comment by bashanlam** [comment]
Fix has be released with https://github.com/UserOfficeProject/user-office-core/pull/229.
