### ISSUE TITLE
Generic templates don't show nice errors if they don't meet constraints

### ISSUE THREAD

**Issue by sukhsingh2525** [UserOfficeProject/user-office-project-issue-tracker#664]
> When adding a journal article I clicked "Save and Continue" on the popup, and got a red box error "Can not answer topic because provided value is not satisfying constraint." Clicking "Save" did not cause an error.
> 
> Then, if I tried to move forwards from the Journal Article page I got the error "All genericTemplates must be completed" and had to delete the added article to move forward.

**Comment by simonfernandes** [comment]
**Notes from meeting with Sukh, Simon, Philip and Emma 12th Dec 2022:**

It's important to have friendly error messages so that we look professional.

**Comment by bashanlam** [comment]
The error message is updated to “Please enter a valid input for the ‘QUESTION’”. 
![FixedErrorMsg](https://user-images.githubusercontent.com/114708346/231132908-8ad73194-2444-48c0-8725-3e3deb26954b.jpg)
