### ISSUE TITLE
Sometimes a subtemplate doesn't show in the table after saving

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#665]
Feedback from user:

> On step 2 I added a gran “Super Grant” from “Super Grants R Us” and clicked Save and continue but it didn’t appear in table – if I hit refresh it still didn’t appear but when I then clicked on the dashboard link on left and then edited the proposal and jumped to second step, then it appeared.- This seems to be glitch

Another user gave similar feedback: 

> From: Cottrell, Stephen (STFC,RAL,ISIS) <[stephen.cottrell@stfc.ac.uk](mailto:stephen.cottrell@stfc.ac.uk)>
> Sent: 28 September 2022 13:14
> To: Facilities Business Systems & Support <[FacilitiesBusinessSystem@stfc.ac.uk](mailto:FacilitiesBusinessSystem@stfc.ac.uk)>
> Cc: Gozzard, Emma (STFC,RAL,ISIS) <[emma.gozzard@stfc.ac.uk](mailto:emma.gozzard@stfc.ac.uk)>
> Subject: Problem with New Proposal system 
>  
> Hi,
>  
> I recently submitted proposal RB2310011 (attached). I returned to it today to edit the ‘Publication’ list and change details in the sample list. However, ‘viewing’ the proposal and using ‘back’ to find the right page in the proposal submission, I find these lists randomly disappear (‘This list is Empty’). However, they’re still listed when viewing the proposal and seem to reappear after returning to the dashboard and starting again. Seems to me this is a bit of a problem,
>  
> Steve

**Comment by voduguwa** [comment]
There has been no success with attempts to replicate the apparent bug. Identically formatted sub-templates were created with no issue, after submitting the proposal and after using ‘back’ to navigate to where they were listed, they were still appeared in the list. This method of testing was used in multiple browsers (Chrome, Firefox and Microsoft Edge) and there was no abnormal behaviour. More information has been requested from the second user that provided feedback but until they get back to us the issue cannot be resolved.
