### ISSUE TITLE
Use embellishments to show fields as public

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#666]
The fields which we may make public are:
- Expt title
- Expt abstract
- PI and Co-I names and institutions
- Technique and instrument applied for, and no. days applied for
- Technique and instrument allocated, and no. days allocated.

**Comment by georgeflecknell** [comment]
Added single embellishment above the proposal basis:

_Please note that responses to the following questions will be made publicly viewable:

Title
Abstract
PI and Co-I names and institutions
Technique and instrument applied for, and no. days applied for
Technique and instrument allocated, and no. days allocated._
