### ISSUE TITLE
Modify submission message for editable proposals

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#667]
Modify the message that appears when you click submit on a proposal that will be editable after submission:

"... proposal will be editable after submission **until the proposal deadline**"

**Comment by georgeflecknell** [comment]
@TickleThePanda This one looks straightforward but I believe is a code change. I'd rather not touch the actual code! Simon I think might be also assigned but is off sick. Just want to make sure this one isn't missed. The UO were very insistent on it.

**Comment by TickleThePanda** [comment]
Ah, a bit of confusing with these issues then. There's a 3rd issue which is to make sure the new ISIS call has the right text in it, in the short term.

**Comment by TickleThePanda** [comment]
As a workaround until we do this and #652.

**Comment by simonfernandes** [comment]
Closed as we have https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/652
