### ISSUE TITLE
Make sure there's a way for instrument scientists to see all proposals for their instrument

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#682]
Because we aren't releasing #616 now, we need to make sure there's a way for instrument scientists to see all proposals for their instrument before the peak usage.

**Comment by simonfernandes** [comment]
Approach:
- Encourage scientists to use the proposal filtering that already exists on the site, by sending them a how-to email (below).
- If they have problems doing this, ask them to get in touch with us and we can tell them how they can view their proposals in SharePoint, and possibly set up a SharePoint view for them. All proposals for their instrument will show in a single list, but proposal PDFs are not available in SharePoint.

--- 

Dear all,

This email provides details on how you can view proposals for your instruments in the 2023_1 round.

You can utilise the question filtering on the proposal system to do this:
 1. Log in as Instrument Scientist and go to the "Proposals" page.
 2. Choose ISIS Direct 2023_1 from the "Call" dropdown.
 3. Click the "more" button.
 4. Choose the question that asks the user which instrument they would like for their technique.
 5. Choose your instrument in the answer dropdown.

For more detailed instructions, please see the [documentation available on our KnowledgeBase](https://stfc365.sharepoint.com/sites/ICD-UserProgrammeKnowledgeBase/SitePages/Proposal-System-for-Instrument-Scientists.aspx#filtering-by-answers-to-questions).
 
Please note that if your instrument is used for more than one technique, you will need to view proposals for each question separately. In future rounds we will be improving this by using a single question.

If this method is unsuitable for your instrument, please get in touch with us and we can explore possible alternatives.

Kind regards,
Proposals and Outcomes team

**Comment by georgeflecknell** [comment]
This will be ideal. I've just followed the instructions myself and this will work absolutely fine for Instrument Scientists.

**Comment by simonfernandes** [comment]
Email has been sent from the support inbox.

**Comment by georgeflecknell** [comment]
User confirmed (Svemir Rudic) that this was an appropriate way to find proposals.
