### ISSUE TITLE
Ensure ISIS Direct submission message is filled in correctly

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#687]
We need to make it clear to users, in the submission box:
 - that the submission will be received when they click "submit"
 - that they may need to wait for the email

**Comment by TickleThePanda** [comment]
Short term workaround until #667 and #652

**Comment by georgeflecknell** [comment]
Hi Emma,

In our conversation and the SPRINT meeting, we discussed the submission confirmation boxes when a user submits a proposal. There is an issue  (code change) in to make the submission box prominent. In the meantime however the Submission Message box will need to be used to specify:

that the submission will be received when they click "submit"
that they may need to wait for the email




This might become more optional in later calls if we all feel that a submission confirmation box popup does the same job.

Thanks,
George
