### ISSUE TITLE
When date fields do not meet validation requirements in subtemplates, the subtemplate hangs

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#689]
Steps to reproduce on prod:
1. Start to create a proposal for ISIS Rapid or Direct
2. Get to the "Research Support" step
3. Click "Add a grant"
4. Fill out all fields except one or both of the dates, or set them to bad dates
5. Click "Save" or "Save and Continue"

The page will now hang, showing a loading symbol.

**Comment by ACLay** [comment]
Playing around with this on prod, it seems like the modal's `save` is successfully adding the incomple/invalid, and `save and continue` causes the modal to show a neverending loading spinner. However when that happens I can just click off of the modal to close it, I don't seem able to replicate the page hanging.

**Comment by ACLay** [comment]
Also seems that you can only progress off the page with the generic template if for each filling of the template you've clicked the `save and continue`. Filling out a template response, clicking `save` and closing the modal will result in an 
> All genericTemplates must be completed

error message when you try to `save and continue` from the questionnaire page.
