### ISSUE TITLE
Demo software to HPL

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#713]
We need to demo the software to relevant people (organised by Sukh) at HPL, prior to their first call on the new system.

We should demo features in all roles, for example:
- [x] User role (questionnaire)
- [x] Instrument scientist role (different ways of searching/filtering proposals)
- [ ] User Officer role (creating calls/workflows, creating a proposal template - and previewing it in the editor, system notices, etc.)

Demoing the User Officer role features will likely be done in a separate, smaller meeting.

**Comment by mutambaraf** [comment]
Does this need to change l recently created this issues template

**Comment by Cat-Lucifer** [comment]
Who do we need to demo to?  David Carroll (HPL FAP Sec) and Rob Clarke have seen the system.

**Comment by simonfernandes** [comment]
It was really anyone who needed/wanted to see the User Officer role from their side. If David and Rob have seen it then it's perhaps just Cristina who is missing.

A while ago I think we said in sprint planning that this probably isn't necessary for the rollout as setup and support will come through you/us.

**Comment by Cat-Lucifer** [comment]
Cool.  I think we're okay with just David C and Rob C then.

**Comment by simonfernandes** [comment]
Sprint planning notes: Fine to leave, we can always demo on request down the line

**Comment by simonfernandes** [comment]
In the HPL sign off, they requested that we demo again to a list of given names

Roles to demo:

- User (@ellen-wright)
- Experiment Scientist (@mutambaraf)
