### ISSUE TITLE
Make PDFs linkable from outside the proposals system

### ISSUE THREAD

**Issue by EdwardHaynes** [UserOfficeProject/user-office-project-issue-tracker#716]
Part of: https://github.com/isisbusapps/Schedule/issues/3618

**Comment by ACLay** [comment]
While we probably could link by the proposal system's internal ids at the moment, our other systems will need a way to link that's based on RB instead

**Comment by simonfernandes** [comment]
Notes from meeting with Sukh, Simon and Philip 28/10/22:

- Scheduling could take place as soon as before Christmas.
- Now that we need proposals available in the ProposalList (#734), we can keep the same link to the ProposalList (so possibly nothing needs doing here?)

**Comment by simonfernandes** [comment]
Needed for:

- The scheduler https://github.com/isisbusapps/Schedule/issues/3618
- Adding a link to the ProposalList https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/739

**Comment by TickleThePanda** [comment]
This might relate to https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/751, too.
