### ISSUE TITLE
Enable cross-database querying between Oracle and Postgres

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#721]
When we set up the heterogeneous connection between Oracle and Postgres, we only tested that we could select data, but we have since found that there is an issue when selecting data from Postgres and joining it to Oracle tables (cross database querying).

For example, the following query does not work:

```
SELECT * FROM "03_pis_cois"@duo d
JOIN isisuserdb.person p ON p.user_number = d."User Number"
```

```
ORA-02025: all tables in the SQL statement must be at the remote database
02025. 00000 -  "all tables in the SQL statement must be at the remote database"
*Cause:    The user's SQL statement references tables from multiple databases.
           The remote database is not Oracle V7 or above, and can perform
           updates only if it can reference all tables in the SQL statement.
*Action:
Error at Line: 1 Column: 8
```

Options
---
### Executing queries from Oracle
We'd need to do this if we plan to add queries to the Reporting Tool. We had planned to create views in Postgres (to work around https://github.com/isisbusapps/reporting-tool/issues/668), but it looks like this may actually not be possible at all:

> From: Lopez Fernandez, Miguel (STFC,RAL,SC) <[miguel.lopez-fernandez@stfc.ac.uk](mailto:miguel.lopez-fernandez@stfc.ac.uk)> 
> Sent: 10 October 2022 13:11
> To: Fernandes, Simon (STFC,RAL,ISIS) <[simon.fernandes@stfc.ac.uk](mailto:simon.fernandes@stfc.ac.uk)>
> Cc: DATABASE SERVICES <[DATABASESERVICES@stfc.ac.uk](mailto:DATABASESERVICES@stfc.ac.uk)>
> Subject: RE: Referencing Postgres/Oracle databases in the same query
> 
> Not sure if it’s possible to join tables from Oracle and Postgres from the Oracle side.

> From: Lopez Fernandez, Miguel (STFC,RAL,SC) <[miguel.lopez-fernandez@stfc.ac.uk](mailto:miguel.lopez-fernandez@stfc.ac.uk)> 
> Sent: 10 October 2022 15:49
> To: Fernandes, Simon (STFC,RAL,ISIS) <[simon.fernandes@stfc.ac.uk](mailto:simon.fernandes@stfc.ac.uk)>
> Subject: RE: Referencing Postgres/Oracle databases in the same query
> 
> The joining of tables from mixed RDBMS is not related to the Oracle version, is more like a systemic restriction.

> From: Lopez Fernandez, Miguel (STFC,RAL,SC) <miguel.lopez-fernandez@stfc.ac.uk> 
> Sent: 11 October 2022 08:20
> To: Fernandes, Simon (STFC,RAL,ISIS) <simon.fernandes@stfc.ac.uk>
> Subject: RE: Referencing Postgres/Oracle databases in the same query
> 
> As far as I know, mixed database table joins are not allowed by the heterogeneous connection feature. The semantics is that tables accessed together frequently should belong to the same database.  You should double-check if the current schema design is adequate. 
> If the business need is still there, some of the usual solutions are:
> 
> •	Usage of session temporary tables (they are NOT regular tables). 
> •	Manipulating the data from both local and remote tables using a stored procedure instead of a SQL query.  
> 
> You should provide more details about the business requirement for this “link” so I can give you more precise advice.

### Executing queries from Postgres
We can instead do the link the other way. I believe this would work with something like [Metabase](https://www.metabase.com/) (which the ESS use for reporting), but would mean that we couldn't put queries in the Reporting Tool. This route would require some setup:

> From: Lopez Fernandez, Miguel (STFC,RAL,SC) <[miguel.lopez-fernandez@stfc.ac.uk](mailto:miguel.lopez-fernandez@stfc.ac.uk)> 
> Sent: 10 October 2022 13:11
> To: Fernandes, Simon (STFC,RAL,ISIS) <[simon.fernandes@stfc.ac.uk](mailto:simon.fernandes@stfc.ac.uk)>
> Cc: DATABASE SERVICES <[DATABASESERVICES@stfc.ac.uk](mailto:DATABASESERVICES@stfc.ac.uk)>
> Subject: RE: Referencing Postgres/Oracle databases in the same query
> 
> From the Postgres side, you might need to define foreign data wrappers (CREATE FOREIGN TABLE) in Postgres so the remote Oracle tables can be joined with the local tables.  The foreign data wrapper is a Postgres extension and is not installed in your Postgres environment.

> From: Lopez Fernandez, Miguel (STFC,RAL,SC) <[miguel.lopez-fernandez@stfc.ac.uk](mailto:miguel.lopez-fernandez@stfc.ac.uk)> 
> Sent: 10 October 2022 15:49
> To: Fernandes, Simon (STFC,RAL,ISIS) <[simon.fernandes@stfc.ac.uk](mailto:simon.fernandes@stfc.ac.uk)>
> Subject: RE: Referencing Postgres/Oracle databases in the same query
> 
> The joining of tables from mixed RDBMS is not related to the Oracle version, is more like a systemic restriction.  Installing the Postgres extension is not straightforward and it will take time, it has to be compiled from the source to create a library and the functionality must be tested on development before implementing it in production. A quicker workaround would be creating a temporary table to extract the Postgres data into it and then joining it with the Oracle table.

**Comment by srconway** [comment]
Does this "just" affect reporting or are there other scenarios where we need a cross-database join? Also is there a specific query that can't be completed because of this, i.e. it's a urgent problem or something we need to deal with at some point in the future?

**Comment by simonfernandes** [comment]
Closing this as it we will not be using the heterogeneous connection anymore and will instead be using Trino. Relevant issues:

- https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/755
- https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/805
- https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/806
