### ISSUE TITLE
Adding duplicate co-proposers causes a proposal to have no co-proposers

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#724]
It's possible to add duplicate co-proposers in the experiment team proposal step. This can result in two scenarios:

- The co-proposer appears twice in the submitted proposal – this is what was originally observed and why issue was created. When I looked into it the problematic proposal it seemed to resolve itself, and I've been unable to replicate this myself. See below for more info on this.
- None of the co-proposers (including non-duplicated co-proposers) are actually added to the proposal, with no indication to the user at the time. This is the behaviour I'm seeing and it means the proposal is submitted with the PI only. This was problematic in ISIS Direct 23/1 as we had to contact all PIs who had no co-investigators to check this was intended. Some (a few?) got back to us that the proposal should have included co-investigators. See the [first reply](https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/724#issuecomment-1290248731) for more info.
  - Anonymous instrument scientist feedback on this: 

    >   The co-investigator information got lost repeatedly. Then it magically re-appeard. In the end I ended up with co-investigators appearing twice on my proposal.

## Which role does this affect.
User
## What needs to change.
Investigate whether it's somehow possible to add duplicate co-proposers and fix
## What is the events it is needed for or affected by.
Unsure
## Why it needs to change.
Results in query errors in logs, and might cause problems down the line in reporting/scheduling if left
## Steps to reproduce (if it's a bug).
Unknown
- Tried adding different emails associated with user
- Tried whitespace/capitalisation changes when adding the email of a co-proposer that was already added
## Who requested it and when.
- Seen in [logs](https://logs.devs.facilities.rl.ac.uk/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-10-20T07:51:00.000Z',to:'2022-10-20T07:54:00.000Z'))&_a=(columns:!(message),filters:!(),index:'7e1733e0-d283-11ea-856e-3dc8c807c0b0',interval:auto,query:(language:kuery,query:'application.name:%20%22proposal-backend%22%20and%20log_level:%22ERROR%22%20'),sort:!(!('@timestamp',desc))))
- Seen as a duplicate user in the proposal overview as user officer
- Seen as a duplicate when editing the proposal as a user officer and looking at the proposer step
- Unsure whether it caused the user any errors/problems
## Other helpful details like screenshots or email content from.
It strangely seems to have fixed itself after I edited the proposal to look at the proposer step, even though I didn't fix anything. So this is a screenshot from it being fixed. Proposal pk is 14718 and Carla A showed twice.

![image](https://user-images.githubusercontent.com/14293717/196917509-03cb622b-e722-46e1-b5a1-45c6e6565874.png)

**Comment by simonfernandes** [comment]
Think I've partly figured this out but not completely:

If you search for someone's email address and click "Find User", in addition to ticking them from the list of your previous collaborators, and then click "Update", it adds two of the same user. You can progress to the next step without error, but it does log the query error that we are seeing. 

However, the duplicate experimenter in question, and any others you happened to have added, won't actually be added to the proposal, along with any other people you added at the same time. You can only see this if you click back or view the proposal as user officer. So this doesn't answer how I was able to see a duplicate co-proposer when viewing the proposal in the original post.

![image](https://user-images.githubusercontent.com/14293717/197735703-0cd4f6de-9075-4f74-825e-a8e943de3fbd.png)
![image](https://user-images.githubusercontent.com/14293717/197735719-fc9806b4-0be2-4e50-828d-771dcf6970bf.png)

**Comment by mutambaraf** [comment]
This can be stopped from the database and backend but stopping duplicate entries for co-investigators. We can also stop duplicate entries from ever appearing in the co-proposer box. I once opened an issue about that #651

**Comment by simonfernandes** [comment]
**Notes from meeting with Sukh, Simon, Philip and Emma 12th Dec 2022:**

It's very important that all co-proposers are listed, as they are sometimes taken into consideration by reviewers when allocating resources.

**Comment by simonfernandes** [comment]
Some more anonymous instrument scientist feedback (added above too):

> The co-investigator information got lost repeatedly. Then it magically re-appeard. In the end I ended up with co-investigators appearing twice on my proposal.

**Comment by Scott-James-Hurley** [comment]
With regards to the first scenario, I couldn't recreate the co-proposers appearing twice bug and I can't see anything in the front-end code that could cause co-proposers to disappear. All of the proposal details are fetched at the same time so if it had trouble getting co-proposers I would've thought it wouldn't be able to get all the other proposal details either. I don't see how the back-end could manifest the bug either. The `proposal-user` table, which the backend queries to get co-proposers, has a primary key of `proposal_pk` and `user_id` so that should disallow multiple rows of the same user and proposal.

**Comment by TickleThePanda** [comment]
Closed as we think Scott has fixed all of the issues here. If we hear any more problems from users, we'll open a new issue for it.
