### ISSUE TITLE
Changing the status of a submitted experiment causes "Something went wrong" although the change is made

### ISSUE THREAD

**Issue by georgeflecknell** [UserOfficeProject/user-office-project-issue-tracker#725]
This problem affects the User Officer role when updating the status of submitted proposals in the ISIS Direct Access 2023_1 call. The call closed for external users on 24/10/2022.

The action itself (status: submitted(locked) to editable_submitted) does take place. However this isn't reflected in the browser and a "Something went wrong" error message appears.

![image](https://user-images.githubusercontent.com/75302934/197761131-41bc5bc9-c5b5-4b9e-a824-2202f587da9e.png)

Refreshing the browser shows the proposal with the correct changed status.

A fix is required to remove the irrelevant error and/or to fix an error that is occuring.

Problem reported by User Office 25/10/2022

**Comment by simonfernandes** [comment]
**Notes from meeting with Sukh, Simon, Philip and Emma 12th Dec 2022:**

This isn't too much of an issue so long as the change is still actually made. It's a bit annoying but so long as it works Emma and George are used to the behaviour.

**Comment by simonfernandes** [comment]
Closing as we believe it's fixed. We can reopen if it's still an issue.
