### ISSUE TITLE
The next button is not working when updating a call

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#729]
## Which role does this affect.
User officer
## What needs to change.
As a user officer l must be able to set the call end date and press the next button.
## What is the events it is needed for or affected by.
N/A
## Why it needs to change.
User officer should be able to use next button when the is no validation errors
## Steps to reproduce (if it's a bug).
Role: User Officer
1. Select Calls from the menu
2. Go to any call in the table click edit.
3. In the dialog box edit End date.
4. Then click the next button 

## Other helpful details like screenshots or email content from.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/71100224/198299988-2eeac36d-c3c8-4bae-9ee9-fd2291870222.png)

**Comment by simonfernandes** [comment]
Closed via https://github.com/UserOfficeProject/user-office-core/pull/100
