### ISSUE TITLE
After updating call end or call end internal dates, either call ended or call ended internal must be retriggered when the new dates expire.

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#731]
## Which role does this affect.
N/A
## What needs to change.
CALL_ENDED or CALL_ENDED_INTERNAL events must be retriggered when either call end date or call end internal dates are updated. This can be provided as an option to the user offer when updating the call dates or must be automatic.
## What is the events it is needed for or affected by. 
CALL_ENDED or CALL_ENDED_INTERNAL 
## Why it needs to change.
When the user officer opens a call after it has previously been closed and triggered the CALL_ENDED event.  Proposals submitted after the call end date is updated will not have their workflow updated by the CALL_ENDED event because it would have been triggered already and will not be triggered when the new call ended date expires. The same issue also applies to CALL_ENDED_INTERNAL event.
Both CALL_ENDED or CALL_ENDED_INTERNAL event must be retriggered at the new dates after call dates updates.

**Comment by simonfernandes** [comment]
@mutambaraf I'm a bit confused by this issue and all of the call/date stuff, since we had to use some workarounds last round. Do you think this issue will need to be resolved for the next ISIS Direct round?

**Comment by mutambaraf** [comment]
Yes l think so we will need it
