### ISSUE TITLE
Principal Investigator receiving email with wrong details when submitting to ISIS Rapid because call not picking the right proposal submission email template.

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#732]
## Which role does this affect.
Users
## What needs to change.
Update how rapid email templates are associated with a call.
## Why it needs to change.
Users are receiving proposal submission emails with the wrong details.
## Who requested it and when.
Support ticket
## Other helpful details like screenshots or email content from.
![image](https://user-images.githubusercontent.com/71100224/198542437-468c4432-0590-4843-8ea7-11178d978ca7.png)

`You or any of the experimenters listed above may view or edit this proposal. Visit our [proposal submission site](https://proposal.facilities.rl.ac.uk/) to make changes to this proposal.
If you wish to withdraw your involvement with this proposal or you wish your name to be removed from the database, please contact the [ISIS User Office](mailto:isisuo@stfc.ac.uk).
By submitting this proposal the submitter has agreed to the [terms and conditions](https://www.isis.stfc.ac.uk/Pages/Terms-and-Conditions-for-Access.aspx).`

**Comment by simonfernandes** [comment]
This has now been resolved @Cat-Lucifer
