### ISSUE TITLE
Inform Dylan when data is ready for proposal scoring site

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#737]
Dylan has created a [panel scoring SharePoint site](https://stfc365.sharepoint.com/sites/fap-scoring-portal) that secretaries will use prior to the FAPs to look at proposals and score them in advance. During the meeting, they will still use our spreadsheets, but refer back to Dylan's site.

We need to:
- Tell Dylan when secretaries/Emma/George have finished modifying proposals in the ProposalList, so that he can then import all of the up-to-date data, including the PDFs, into the new site.

**Comment by TickleThePanda** [comment]
Done - site is running with data now.
