### ISSUE TITLE
A proposal can cause a reference number gap if the submit button is clicked multiple times

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#740]
When you submit a proposal, you can keep clicking the submitted button to submit the proposal multiple times. In calls with reference number formats, this causes the proposal to be submitted with the next number in the sequence each time.

## Which role does this affect.
User
## What needs to change.
The submitted button should probably be disabled after the first click, to prevent a user pressing it again.
## Why it needs to change.
- In calls with reference numbers we don't want gaps in the sequence when a user has submitted their proposal multiple times through accident. 
- There may be some user confusion as to whether the proposal has been submitted.

## Steps to reproduce (if it's a bug).
Create any call (or use the default one locally). Create a proposal, submit the proposal, and keep pressing the button

## Who requested it and when.
Found through support by noticing a missing proposal in the sequence and finding that it was seemingly submitted twice.
## Other helpful details like screenshots or email content from.
![be3b7a58e3ecde4583ca95d41e6b0b51](https://user-images.githubusercontent.com/14293717/199193155-ca6e291d-1da9-4900-9d01-261427c81dfe.png)

**Comment by TickleThePanda** [comment]
It should be blocked on the backend, too, I think.

**Comment by mutambaraf** [comment]
When that tick appears that button should be disabled

**Comment by simonfernandes** [comment]
**Notes from meeting with Sukh, Simon, Philip and Emma 12th Dec 2022:**

This isn't a dealbreaker for Emma and Philip, as the gaps in reference numbers that this causes doesn't cause any problems for them.

**Comment by TickleThePanda** [comment]
This lead to duplicate proposals in Allocations and SharePoint in the last round.

**Comment by mutambaraf** [comment]
In addition we can also explore showing submitted text rather that showing the button on submitted proposals.

**Comment by bashanlam** [comment]
I added two re-submission checking for the fix. One is in backend and the other in frontend.
