### ISSUE TITLE
Make direct PDF links easier to access

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#741]
When you access a direct PDF link in the software, it isn't easy, as you have to log in and switch role first. Even then, it is sometimes unreliable with errors showing. These are the instructions being used:

1.	Possibly switch to an incognito window or clear your browser cache due to this ongoing issue: https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/718
2.	Log in to https://proposal.facilities.rl.ac.uk/ (I think you’ll get an “Internal Server Error” without this)
3.	Change role to User Officer or Instrument Scientist (I think you’ll get a “Proposal not found” error without this)
4.	Open link in same browser you just logged in with

## Which role does this affect.
STFC User Officer, instrument scientist
## What needs to change.
Can the links redirect back to the login page if you're not logged in? Why do errors occasionally show?
## What is the events it is needed for or affected by.
Access a direct PDF link e.g. https://proposal.site/download/pdf/proposal/123456789
## Why it needs to change.
User officers and instrument scientists need to view proposals this way by clicking on a link.
## Who requested it and when.
Emma G, 31st October 2022.
## Other helpful details like screenshots or email content from.

> From: Gozzard, Emma (STFC,RAL,ISIS) 
> Sent: 31 October 2022 17:46
> To: Fernandes, Simon (STFC,RAL,ISIS) <[simon.fernandes@stfc.ac.uk](mailto:simon.fernandes@stfc.ac.uk)>
> Cc: Facilities Business Systems & Support <[FacilitiesBusinessSystem@stfc.ac.uk](mailto:FacilitiesBusinessSystem@stfc.ac.uk)>; Singh, Sukhvinder (STFC,RAL,ISIS) <[sukhvinder.singh@stfc.ac.uk](mailto:sukhvinder.singh@stfc.ac.uk)>; King, Philip (STFC,RAL,ISIS) <[philip.king@stfc.ac.uk](mailto:philip.king@stfc.ac.uk)>
> Subject: RE: All proposal PDFs in a single place issue 
> 
> Hi Simon,
> 
> Sorry, I should have said, I always work in a new incognito tab for anything to do with the new proposal system at the moment.  I got the error from an incognito tab after logging in.  I still the internal error, in both instrument scientist and user officer role.  Sorry, George will concur that nothing is ever straight forward with my account and access to stuff!
> 
> To add to the never ending workload, it would be good if the hyperlink could just be clicked and a log in prompt popped up and then you could just download.  Especially as the system times you out very quickly – and I can see how that may easily get annoying.  Not for this round, and we can discuss what’s possible around this another time.
---
> From: Gozzard, Emma (STFC,RAL,ISIS) <[emma.gozzard@stfc.ac.uk](mailto:emma.gozzard@stfc.ac.uk)> 
> Sent: 01 November 2022 08:00
> To: Fernandes, Simon (STFC,RAL,ISIS) <[simon.fernandes@stfc.ac.uk](mailto:simon.fernandes@stfc.ac.uk)>
> Cc: Facilities Business Systems & Support <[FacilitiesBusinessSystem@stfc.ac.uk](mailto:FacilitiesBusinessSystem@stfc.ac.uk)>; Singh, Sukhvinder (STFC,RAL,ISIS) <[Sukhvinder.Singh@stfc.ac.uk](mailto:Sukhvinder.Singh@stfc.ac.uk)>; King, Philip (STFC,RAL,ISIS) <[philip.king@stfc.ac.uk](mailto:philip.king@stfc.ac.uk)>
> Subject: RE: All proposal PDFs in a single place issue 
> 
> ...
> 
> But, these hyperlinks are probably the most important for future rounds.
> 
> ...

**Comment by mutambaraf** [comment]
This must have been solved by this PR https://github.com/UserOfficeProject/user-office-core/pull/88
