### ISSUE TITLE
PDFs with invalid filenames (additional period characters) fail to upload with unhelpful error messages

### ISSUE THREAD

**Issue by georgeflecknell** [UserOfficeProject/user-office-project-issue-tracker#742]
## Which role does this affect.

User mostly but potentially all

## What needs to change.

Science cases (and/or) other PDF uploads with invalid filenames (eg: additional periods beyond the file extension) need to be detected and correctly handled. Currently they just prevent file upload with no reason given.

eg: Ba2Fe0.5Co0.5ReO6-MUSR -ProposalDP_noabsv2.pdf fails to upload. However it is fairly common practice for scientisits to use period separation in substance formulae.

## What is the events it is needed for or affected by.

Science cause upload for proposal submission

## Why it needs to change.

It blocks proposal submission as the user can't progress past Science Case upload

## Steps to reproduce (if it's a bug).

Attempt to upload a pdf with title such as Ba2Fe0.5Co0.5ReO6-MUSR -ProposalDP_noabsv2.pdf

**Comment by simonfernandes** [comment]
**Notes from meeting with Sukh, Simon, Philip and Emma 12th Dec 2022:**

If we can't fix this in time, it's important to at least give a sensible error the user via #663

**Comment by bashanlam** [comment]
I am fixing the file upload to accept any file name as long as it is supported by the browser.
