### ISSUE TITLE
Make sure that instrument scientists can edit draft proposals created before the external call close

### ISSUE THREAD

**Issue by RasmiaKulan** [UserOfficeProject/user-office-project-issue-tracker#743]
Currently, proposal left in draft during external deadline are automatically set to `expired` and when submitted during internal call appear as expired.

**Comment by simonfernandes** [comment]
Suggestion from @mutambaraf on Teams:

> [Yesterday 15:47] Mutambara, Farai (STFC,RAL,ISIS)
>
> I think the best solution is to stop submission of proposals with expired status from both internal and external users. The challenge was when the call is open any proposal can be submitted despite its status so that is when the proposal was submitted .Just checked the proposal reach the last status then stopped making workflow updates.
> The proposal workflow goes one way can not go back only manually .We should really stop submission of expired proposals or allow proposal workflow to flow both directions.

**Comment by simonfernandes** [comment]
@RasmiaKulan Do you know any more about the problem that you could expand on? Proposals in draft were expired, but do you know whether it was the case that either: 

- a scientist could complete the proposal on the user's behalf and submit it, but the status didn't change from expired
- a scientist was unable to complete the proposal or submit it because the proposal was expired

**Comment by simonfernandes** [comment]
**Notes from meeting with Sukh, Simon, Philip and Emma 12th Dec 2022:**

We weren't completely sure what the issue was here (see above reply), but either way it is important to resolve. May need to be considered with #745 (Clarify and determine how we use statuses).

**Comment by TickleThePanda** [comment]
- Make sure that `expired` means a proposal is no longer editable
 - Set the workflow to be `call ended` event leads in `draft` and then `call ended internal` leads to `expired`

**Comment by RasmiaKulan** [comment]
> * Make sure that `expired` means a proposal is no longer editable

`Expired` does make the proposal no longer editable

> * Set the workflow to be `call ended` event leads in `draft` and then `call ended internal` leads to `expired`

Within the workflow the proposal system requires `EDITABLE_SUBMITTED_INTERNAL` to be triggered by `CALL_ENDED_INTERNAL` in order for the user officer to set an internal deadline. However, because of this, after the internal deadline the status appears as `EDITABLE_SUBMITTED_INTERNAL` regardless of what status is called upon after that.
Adding up to that, after the external deadline is passed, the status does not change to `DRAFT`. Instead, remains as `EDITABLE_SUBMITTED`.
 As shown below:
![image](https://user-images.githubusercontent.com/69144386/213730299-dcbbcfc2-6538-4ceb-9c84-d12abbaa1bb4.png)

**Comment by RasmiaKulan** [comment]
I'm guessing we cannot go back to `DRAFT` as it defines the initial state of a proposal and although `EDITABLE_SUBMITTED` allows the user to edit the proposal, that proposal's state is not the same as the initial unsubmitted one.

**Comment by mutambaraf** [comment]
I think we can use CALL_ENDED to get proposals into EDITABLE_SUBMITTED_INTERNAL then use CALL_ENDED_INTERNAL to get proposals to DRAFT/ or any other final status.

**Comment by RasmiaKulan** [comment]
> I think we can use CALL_ENDED to get proposals into EDITABLE_SUBMITTED_INTERNAL then use CALL_ENDED_INTERNAL to get proposals to DRAFT/ or any other final status.

But then what state do we want the proposal to be in after submission i.e., `PROPOSAL_SUBMITTED` ?

**Comment by RasmiaKulan** [comment]
@mutambaraf I applied the following workflow:
![image](https://user-images.githubusercontent.com/69144386/214040346-97cf2e34-b105-4e7f-bed5-3fdd16874258.png)

### Before Deadline
- User submits proposal and `submitted` status appears
- User Office is able to see the `editable_submitted` status
- Instrument Scientist is able see the `editable_submitted` status

### After Application Deadline
- User is still able to edit the proposal
- User Office still views the `editable_submitted` status
- User Office still views the `editable_submitted` status

### After Internal Deadline
- User is unable to create proposal
- User Officer still views the `editable_submitted` status
- Instrument Scientist is able see the `editable_submitted` status

### Issues
- The `editable_submitted_internal` status does not appear after application deadline
- The status does not update to `draft` after external deadline
- The User Office or Instrument are unable to edit the proposal

**Comment by RasmiaKulan** [comment]
@Cat-Lucifer Looking at the proposal system currently, instrument scientists can edit proposals if they are on the experiment team when logged in as a user but not within the instrument scientist role. Does this sound fine to you?

**Comment by Cat-Lucifer** [comment]
@RasmiaKulan Yes, thanks!  Sorry, I should have replied earlier.
