### ISSUE TITLE
Viewing logs on the proposal site sometimes doesn't work

### ISSUE THREAD

**Issue by RasmiaKulan** [UserOfficeProject/user-office-project-issue-tracker#744]
The logs for some proposals do not load successfully.

![image](https://user-images.githubusercontent.com/69144386/199452770-b5b68b4d-c9b5-4657-a9ba-5f6d4c2f405e.png)

Console output:

![image](https://user-images.githubusercontent.com/69144386/199454512-349bde0f-c279-4212-857a-2373fa52c24f.png)

**Comment by simonfernandes** [comment]
@Cat-Lucifer As a user officer, do you use access proposal logs much?

---

For developers we have a workaround of being able to retrieve these logs from the database

**Comment by Cat-Lucifer** [comment]
> @Cat-Lucifer As a user officer, do you use access proposal logs much?
> 
> For developers we have a workaround of being able to retrieve these logs from the database

@simonfernandes How do I do this?  Which is another way of saying no, I guess!

**Comment by simonfernandes** [comment]
@Cat-Lucifer Thanks - it's one of the tabs along the top when you view an individual proposal as user officer 🙂

**Comment by simonfernandes** [comment]
Closing in favour of https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/925
