### ISSUE TITLE
Clarify and determine how we use statuses

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#745]
We need to be clear on what each of the statuses in the proposal software are and how they work and impact proposals. We should then agree on and document how we deal with proposals in certain scenarios, e.g. how we should withdraw a proposal.

## Why it needs to change.
It's confusing what the statuses are, the impact they'll have behind the scenes, and how we should be using them.
## Who requested it and when.
@georgeflecknell  and @Cat-Lucifer, in recent support issues arising from the close of ISIS Direct. Also mentioned in sprint planning 2nd Nov 2022.

**Comment by simonfernandes** [comment]
We may need to consider https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/743 as part of this.

**Comment by georgeflecknell** [comment]
From the User Office side I believe the following points are important:

Changing proposals status can affect their downstream behaviour, it is not always clear which statuses are valid to continue
Changes in proposal call status can affect proposal status, it is not always clear how and what this means
Remedial work done by P&O during ISIS 2023_1 changed the statuses of proposals (network outage), it was not clear why this occurred and what effect it would have on proposals
Proposal status should only be visible to proposal submitters if there is a clear explanation of what that status actually means

I think of the above, most points are resolvable by educating proposal system users on what statuses mean. A small technical guide including a flowchart would probably be most helpful. For reference also we should probably display in the proposals system what a status actually means. That way we arent asking people in time pressured situations to go off and read a technical document. Finally if workflows can be simplified and/or number of statuses reduced, this would help avoid confusion.

Going forward we should probably review 
a) our current guidance on statuses and improve it
b) our current guidance on workflows and improve it
c) meet with the user office after the above to ensure no confusion remains
d) if doing remedial work, avoid changing proposal statuses

**Comment by georgeflecknell** [comment]
All of the above points a-c are referenced in Rasmia's new document explaining statuses and workflows, which is being made available for reference.
Point d may need a new issue. Withdrawn proposals (those that the user would like to discontinue AFTER submission and end of round) are currently switched to EXPIRED status. This retains a copy of proposal in the proposal system which we probably want, rather than just deleting. There are two questions though;

Do we want EXPIRED to mean a specific thing and therefore this status isn't appropriate for withdrawn proposals?
Does setting EXPIRED on a SUBMITTED_LOCKED proposal ensure its removal from SharePoint lists via allocations?

**Comment by simonfernandes** [comment]
~It would be great if we could copy what's in the document over to the [KnowledgeBase](https://stfc365.sharepoint.com/sites/ICD-UserProgrammeKnowledgeBase) for this, as it'll mean one less document floating around and a central place for all proposal software documentation.~

I re-read your teams message @RasmiaKulan and realised you're already on top of this and were already planning to do this so never mind 😋

**Comment by RasmiaKulan** [comment]
I have now added the documentation to clarifying and determine workflows and statuses.
https://stfc365.sharepoint.com/sites/ICD-UserProgrammeKnowledgeBase/SitePages/Creating-a-call.aspx
