### ISSUE TITLE
On calls table call create button will show previous call update, when previous call update modal was closed with close Icon. .

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#747]
## Which role does this affect.
User officer
## What needs to change.
N/A
## What is the events it is needed for or affected by.
N/A
## Why it needs to change.
Switch between update and create needs to be consistent.
## Steps to reproduce (if it's a bug).
As User Officer:
- Go to call table.
- Click edit on any call.
- User the close icon to close the modal.
- Bellow the call table click create
- The previous call update modal is shown, instead of call create modal.

**Comment by martin-trajanovski** [comment]
@mutambaraf here is a fix for this specific issue that I noticed as well. https://github.com/UserOfficeProject/user-office-core/pull/97

**Comment by mutambaraf** [comment]
Thanks very much will close this issue.
