### ISSUE TITLE
Make it easier for a developer to download the generated PDFs for proposals

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#751]
Make the download more API friendly.

Here are a few of my ideas:
 - Add the download URL to the `Proposal` on the GraphQL API
 - Allow API tokens to be used for the download URL (possibly with a new "download" permission)
 - Accept the API token as an `Authorization` header

**Comment by mutambaraf** [comment]
Will address https://github.com/isisbusapps/Schedule/issues/3618  and https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/716

**Comment by mutambaraf** [comment]
Solution

- Allow API tokens to be used for downloading proposals pdf.

Possible option 1
- User exiting ProposalQueries.getProposalById permission for token access validation. 
- (Option) Allow proposals to be dowloaded using proposal IDs

Pros and Cons

> Existing tokens will now be able to download proposal pdfs with little modifications.
> We will not be able to control proposal downloads without losing access to getProposalById. 

Possible option 2

- Create a GraphQL API for pdf download that will return a URL to call for pdf download. e.g `https://devproposal.facilities.rl.ac.uk/download/pdf/proposal/2345`
- User the new API permission for token access validation.

Pros and Cons

> Existing tokens will need to be updated for them to download proposal pdfs.
> We will be able to control access to proposal downloads separately from getProposalById permission.
> New GraphQL proposal download pdf API will predominantly be used for API token validation

**Comment by mutambaraf** [comment]
Design review outcome.

- Users will require token authentication and validation to download a given proposal(s). 
- Instead of creating two routes we can use query strings
- API Tokes failure logging will require token name and any other relevant information. The logs must include the reason for the failure.
- API Toke permission can be included in the frontend on a separate tab [Others]. This will get its information from the database as other services and assignable to an API token as permission.

**Comment by mutambaraf** [comment]
To download pdf using RB number or proposal ids you will need to set the filter to use id by passing in query parameter  `?filter=id`. Example `/download/pdf/proposal/567122?filter=id`. Multiple ids can be passed by separating them with a comma `,`
.Example /download/pdf/proposal/56711,56712?filter=id`.

**Comment by mutambaraf** [comment]
Will also add information on downloading pdfs on confluence.
