### ISSUE TITLE
Co-Investigators and samples can intermittently disappear, causing them to be re-added manually, then later reappear as duplicates

### ISSUE THREAD

**Issue by ACLay** [UserOfficeProject/user-office-project-issue-tracker#757]
Possibly related to #724 

## Which role does this affect.
Users & Instrument scientists
## Who requested it and when.
One of our instrument scientists, Aleks Krajewska:

> Hi,
> 
> I would like to report a problem I found with the new proposal system.
> 
> While submitting my own proposal, I found that the co-investigators I entered would sometimes disappear. I would refresh the page and check again, and they would be still gone. So I would add the particular co-investigator again. But then, after some time the entry that vanished would appear again, and I would end up with two identical entries in my proposal. I found the same behaviour for entering “sample”.
> 
> I thought it is some temporary anomaly that only I experienced, but it’s not the case. My colleagues from the Excitations Group had the same experience. Furthermore, now in the proposal books, we see that many proposals have duplicate co-investigator entries, and I guess this is a result of same behaviour I experienced. (that is, users probably noticed that the co-investigator entry disappeared, added it again, and then the old entry re-surfaced, resulting in two identical entries).
> 
> This is a quite annoying bug, and it gives the person processing the proposals for technical review additional work due to many duplicate entries.
> 
> Can this issue be fixed please?
> 
> Thanks very much.
> 
> Best wishes,
> Aleks

**Comment by mutambaraf** [comment]
Will test this after close these issues https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/724 and https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/763

**Comment by mutambaraf** [comment]
I have tested looks it is now solved will be closing this issue.
