### ISSUE TITLE
Show units for crystal cell fields in ISIS Direct PDF

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#762]
In the ISIS Direct PDF, we don't show the unit for crystal cell parameters. This is defined in the ISIS Direct PDF template.

We should also check if similar fields require units, and possibly apply the same fix to the ISIS Rapid PDF.

> Having entered values for the crystal’s cell parameters, the resulting PDF shows no units. Since some people report values in nanometres and others in angstroms, it would be beneficial for the document to be clear on the units. 

Originates from [ISIS Direct feedback document](https://stfc365.sharepoint.com/:w:/r/sites/isiscomputingdivision-staffsite/_layouts/15/Doc.aspx?sourcedoc=%7BCAFB6AF8-EB88-4909-9BDC-D01E031780E0%7D&file=ProposalSystemFeedback.docx&action=default&mobileredirect=true&cid=01f1cc1f-a82f-4596-85c5-3339298ce341).

![image](https://user-images.githubusercontent.com/14293717/205632990-db2dbfaf-3afe-4f47-9fc2-71b0bee57c3c.png)

**Comment by simonfernandes** [comment]
Marked as friendly as it hopefully just requires a bit of extra data in the PDF template.

**Comment by simonfernandes** [comment]
We will need to be mindful of https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/777 (making crystallographic data non-compulsory).

**Comment by simonfernandes** [comment]
@Cat-Lucifer Do you know which question(s) this relates to? I can't figure it out!

**Comment by Cat-Lucifer** [comment]
@simonfernandes I don't know who submitted this feedback, but I assume it relates to the cell parameter Qs under the powder / single crystal technique specific Qs.  BUT, the answers to these aren't shown on the pdf, so I'm not sure what they're going on about!

I think, as long as corresponding units for parameters are pulled across in the technique Q query (which Chi Kai was working on) then we are fine here.

Also, this was feedback from round 23-1 and we did not have the same issues for round 23-2.

**Comment by simonfernandes** [comment]
@Cat-Lucifer Perfect, let's close this off then! Thanks for checking, glad it wasn't just me equally confused!

Tagging @bashanlam to ensure units are reported for those questions
