### ISSUE TITLE
Removed sample retains values from cloned proposal

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#763]
When a user cloned a proposal, but then removed their sample, the old data was still present in the cloned proposal.

Probably applies to all generic template type questions (samples, grants, publications).

> We have tried to use the cloned proposal as a start for the new proposal. 
> 
> The original proposal required a deuteration facility, and we had to specify the deuterated samples, including the jpeg figures of structural formulas of the deuterated samples. 
> 
> Upon cloning the proposal and changing the samples (removing the old and adding new) in the cloned proposal, and submitting the new/cloned proposal, we have found that the now spurious information about the deuterated samples (including the jpeg figures) was still present in the new proposal that has been modified from the cloned one, despite the complete removal of the deuterated samples and answering No for the need to use the deuteration facility. 
> 

Originates from [ISIS Direct feedback document](https://stfc365.sharepoint.com/:w:/r/sites/isiscomputingdivision-staffsite/_layouts/15/Doc.aspx?sourcedoc=%7BCAFB6AF8-EB88-4909-9BDC-D01E031780E0%7D&file=ProposalSystemFeedback.docx&action=default&mobileredirect=true&cid=01f1cc1f-a82f-4596-85c5-3339298ce341).

**Comment by simonfernandes** [comment]
**Notes from meeting with Sukh, Simon, Philip and Emma 12th Dec 2022:**

Although this only seemed to affect one user this time, many more users will be cloning proposals in the next round and so this could be an important issue to fix.

**Comment by mutambaraf** [comment]
Managed to recreate this bug but it is affecting editing of proposals when you add new samples information in publication answers are being cleared such that when you get to publication it will show empty table but data will still be in the proposal. Will address this bug and see if this will happen again.

**Comment by simonfernandes** [comment]
We will need to check whether this affects all generic template questions.
