### ISSUE TITLE
As a user, I would like it to be clearer when I update (re-submit) an already submitted proposal

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#764]
When a user submits a proposal, they get a nice submission confirmation message. If they amend their proposal (if it's in a call that allows it), they only get messages that the proposal has been "saved", which isn't clear that it has been re-submitted.

This has been mentioned twice, and also suggested that all proposers should be notified of this resubmission (presumably via email).

> User 1:
> In the old system, one could press the submit button as many times as one wanted before the deadline in order to submit the ever newer versions of the proposal. With the new system, we can only hope this is the case (as it should be). We were trying to make some changes in the already submitted proposal, but apart from pressing ‘Save and Continue’ and getting note in green ‘Saved’, I am not quite sure if the edited proposal has been resubmitted. 

> User 2:
> If a proposal is submitted and then edited again any changes are automatically included and the proposers are not notified, i.e. submit button is greyed out and the does not need to be pressed again. I am not sure if this is an intentional feature but it is a little dangerous. 

Originates from [ISIS Direct feedback document](https://stfc365.sharepoint.com/:w:/r/sites/isiscomputingdivision-staffsite/_layouts/15/Doc.aspx?sourcedoc=%7BCAFB6AF8-EB88-4909-9BDC-D01E031780E0%7D&file=ProposalSystemFeedback.docx&action=default&mobileredirect=true&cid=01f1cc1f-a82f-4596-85c5-3339298ce341).

**Comment by simonfernandes** [comment]
Easiest fix would be to change the wording on the button to something like "Save and Resubmit" and adjusting the message to say something other than "Saved".

**Comment by mutambaraf** [comment]
> Easiest fix would be to change the wording on the button to something like "Save and Resubmit" and adjusting the message to say something other than "Saved".

Will implement the above solution and will also adjust the message to users. Will also explore showing submitted text rather that showing the button on submitted proposals.

**Comment by mutambaraf** [comment]
Fix to submit button will leave it to this issue https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/740

**Comment by simonfernandes** [comment]
@mutambaraf Hope you're okay with keeping this open for now, so that it's clearer to stakeholders that not all functionality associated with this issue has been implemented yet.

Are you able to add something to #740 so that @bashanlam knows about the submit button?

**Comment by mutambaraf** [comment]
For this l thought getting the messaging right was more important to inform them the proposal is resubmitted no extra steps are required. Changing text on buttons was just an after thought that may not be that critical. We can monitor it if  need be make extra additions.

**Comment by TickleThePanda** [comment]
Agreed at sprint planning this is done for this round - we will review again if we get feedback.
