### ISSUE TITLE
As a user, I would like my preferred first name to display

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#766]
A user would like their preferred first name to show in the principal investigator field, as that is what they are known as.

> I have just tried out your new system for proposals and notice that User Names use First name. I am ____ ____ ____ and am known as ____. 
> 
> When I was in charge of the ISIS databases I fought bitterly to stop this Americanisation and use the term 'known as'. 
> 
> I searched the names database & discovered that at least 10% of principal users did not use first name. 
> 
> In epubs, which I was also involved with developing, this is taken into account. 
> 
> When I first looked at this page I just saw my name as ____ and then First Name in the box below. Didn't notice the Preferred Name input! So that input could be Ok. 
> 
> On my User Office account I have given my Preferred Name but that is not used. 
> I’d like that line to show Preferred first name 

![image](https://user-images.githubusercontent.com/14293717/205666745-876dd5b4-0b74-4a77-afe8-16eeb213c68a.png)

Originates from [ISIS Direct feedback document](https://stfc365.sharepoint.com/:w:/r/sites/isiscomputingdivision-staffsite/_layouts/15/Doc.aspx?sourcedoc=%7BCAFB6AF8-EB88-4909-9BDC-D01E031780E0%7D&file=ProposalSystemFeedback.docx&action=default&mobileredirect=true&cid=01f1cc1f-a82f-4596-85c5-3339298ce341).

**Comment by simonfernandes** [comment]
We need to review where we're using first name instead of preferred name and change it.

**Comment by ellen-wright** [comment]
Closed by https://github.com/UserOfficeProject/user-office-core/pull/365
