### ISSUE TITLE
Creating a new call modifies info from the last viewed call

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#773]
### What is the problem and why is it a problem
Creating a new call can show information from a previously viewed call. Then, when changing details in the "new" call, it can actually modify the previously viewed call.

### Steps to reproduce (if it's a bug).

View a call, then click the "Create" button.

> From: Gozzard, Emma (STFC,RAL,ISIS) <emma.gozzard@stfc.ac.uk> 
> Sent: 09 January 2023 12:02
> To: Facilities Business Systems & Support <FacilitiesBusinessSystem@stfc.ac.uk>
> Subject: RE: V Quick: ISIS Rapid
> 
> ...
> 
> I clicked the “Create” button to crate the 2023 Rapid call and it brought up all of the details for the currently open 2022 Rapid call.  When I overwrote these it changed the current 2022 Rapid call details!  I obviously went straight back in to amend to the original details.  However, there is clearly a bug in the system that opens up the details of the last call you looked at if you click the “Create” button in the same session.  This is a problem.

**Comment by mutambaraf** [comment]
This might have been fixed with https://github.com/UserOfficeProject/user-office-core/pull/97 but we can monitor it again.

**Comment by simonfernandes** [comment]
**Notes from meeting with Emma, Philip, Sukh and Simon 13/01/2023**

We do need to fix this further for future use, but it's low impact for ISIS Direct 2023_2 as it's something Emma/George are aware of and know how to work around.

**Comment by TickleThePanda** [comment]
We're going to test if this is still a problem following https://github.com/UserOfficeProject/user-office-core/pull/97

**Comment by simonfernandes** [comment]
Closing as it seems to have been fixed (see Farai's comment above). Tagging @Cat-Lucifer and @georgeflecknell for awareness.
