### ISSUE TITLE
Create reports that can pull out key information for instrument scientists and CLF FAP Secretaries

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#775]
Instrument scientists and FAP secretaries need access to proposal data via reporting that isn't readily available through the site.

For instrument scientists:
> Ideally we would want:  PI, PI country, Organisation, Time requested, Instrument, Title, Local contact, Submitted or in-draft status.  If these aren’t possible then just PI, Time requested and instrument will do.

For FAP secretaries:
> More proposal information needs to be populated in the ProposalList database, then there currently is for 23-1.  Extra info required, at minimum: Local contact, Country, Organisation, Department, Abstract.  I cannot do my job effectively without these.

We'll need to separate reports for ISIS and each CLF facility.

**Comment by TickleThePanda** [comment]
For ISIS Instrument Scientists, I had a request to have a report to get aggregated information about proposals (sum of days+count of proposals, for submitted and unsubmitted) so they can understand how requested an instrument is. We used to provide this in SharePoint but it no longer works.

**Comment by simonfernandes** [comment]
> For ISIS Instrument Scientists, I had a request to have a report to get aggregated information about proposals (sum of days+count of proposals, for submitted and unsubmitted) so they can understand how requested an instrument is. We used to provide this in SharePoint but it no longer works.

I'll have these for submitted proposals, and I can go back and add them in for unsubmitted.

**Comment by simonfernandes** [comment]
Closed via https://github.com/isisbusapps/reporting-tool/pull/696 and https://github.com/isisbusapps/reporting-tool/pull/693
