### ISSUE TITLE
As a user, I would like to be able choose units for certain values

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#776]
The questionnaire doesn't allow users to use preferred units in some questions:

> Pressure in Pascals is not useful for neutron scattering (kbar is more common)

> It would be useful to be able to select the units (as we could before) for the temperature, pressure and magnetic field conditions of the proposed experiment. For example, it’s preferable to be able to write 5 GPa for the maximum pressure rather than 5000000000 Pa. You could provide free text boxes as in the sample description section. 

We can modify the question in the questionnaire to allow the user to select from predefined units for their value.

We will need to make sure to include the unit when reporting.

Originates from the [ISIS Direct feedback document](https://stfc365.sharepoint.com/:w:/r/sites/isiscomputingdivision-staffsite/_layouts/15/Doc.aspx?sourcedoc=%7BCAFB6AF8-EB88-4909-9BDC-D01E031780E0%7D&file=ProposalSystemFeedback.docx&action=default&mobileredirect=true&cid=01f1cc1f-a82f-4596-85c5-3339298ce341).

**Comment by Cat-Lucifer** [comment]
mK (for temp), MPa and GPa (for pressure) and gauss (for magnetic field strength) are not available to select as additional units.  @EdwardHaynes Is there a way these can be added in please?

**Comment by EdwardHaynes** [comment]
> mK (for temp), MPa and GPa (for pressure) and gauss (for magnetic field strength) are not available to select as additional units. @EdwardHaynes Is there a way these can be added in please?

Hi @Cat-Lucifer, you can add these units using the 'Units' page under the settings tabs (https://proposal.facilities.rl.ac.uk/Units). I looked into adding them but it requires some technical info that I don't have. Happy to help if you run into any issues.

**Comment by Cat-Lucifer** [comment]
> > mK (for temp), MPa and GPa (for pressure) and gauss (for magnetic field strength) are not available to select as additional units. @EdwardHaynes Is there a way these can be added in please?
> 
> Hi @Cat-Lucifer, you can add these units using the 'Units' page under the settings tabs (https://proposal.facilities.rl.ac.uk/Units). I looked into adding them but it requires some technical info that I don't have. Happy to help if you run into any issues.

Done.
