### ISSUE TITLE
As a user filling in the questionnaire, I do not always have mandatory crystallographic data to provide

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#777]
Users have to provide mandatory crystallographic data when it isn't always applicable. We should make it non-compulsory instead.

> It appears that entering crystallographic data (symmetry, cell parameters) is mandatory (it wasn’t before). However, there are experiments in which we are aiming to determine the structure of an unknown material, so these data are not known in advance. It should be possible to skip these data, or have a drop-down where one selects “known” or “unknown” with the first option then prompting the user to enter values.  It may also be the case that a material will undergo a change from one structure to another and it might be useful to enter more than one set of values…

Originates from the [ISIS Direct feedback document](https://stfc365.sharepoint.com/:w:/r/sites/isiscomputingdivision-staffsite/_layouts/15/Doc.aspx?sourcedoc=%7BCAFB6AF8-EB88-4909-9BDC-D01E031780E0%7D&file=ProposalSystemFeedback.docx&action=default&mobileredirect=true&cid=01f1cc1f-a82f-4596-85c5-3339298ce341).

**Comment by Cat-Lucifer** [comment]
Crystal sub template Qs now not mandatory.
