### ISSUE TITLE
As an instrument scientist, I would like better guidelines for users' abstracts

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#778]
Users could do with better abstract guidelines so that they equally provide enough information but don't write too much.

> The data entry for the abstracts seems to be much better, in that I think there’s no longer a word limit. However, we don’t want people writing vast abstracts so it may be an idea to have a recommended word count (and provide a counter) but then not necessarily prevent people from over-running the count if they need to finish a sentence. 

In the first instance we should add some guidance text and monitor it. If we start to see excessive abstracts, we should possibly add a counter.

Originates from the [ISIS Direct feedback document](https://stfc365.sharepoint.com/:w:/r/sites/isiscomputingdivision-staffsite/_layouts/15/Doc.aspx?sourcedoc=%7BCAFB6AF8-EB88-4909-9BDC-D01E031780E0%7D&file=ProposalSystemFeedback.docx&action=default&mobileredirect=true&cid=01f1cc1f-a82f-4596-85c5-3339298ce341).

**Comment by Cat-Lucifer** [comment]
Also, add some text for selection of continuation proposals - re submission of experimental report dependent.

**Comment by Cat-Lucifer** [comment]
Remove student text at start of Q

**Comment by Cat-Lucifer** [comment]
I couldn't work out how to edit the proposal_basis in the questionnaire, so I added some text on expected abstract word count in the embellishment ISIS_Public_Info_Emb
