### ISSUE TITLE
As a user, I would like to copy a sub template value from a previous proposal, so that I don't have to duplicate inputting it

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#779]
As an interim measure for https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/31, we should allow users to select from previous grants and publications (etc.) in any previous proposal, so that they can easily re-use the template information without adding it again.

**Comment by mutambaraf** [comment]
Monitoring  marking of templates as complete in `topic_completenesses` we might reconsider using raw sql query

**Comment by mutambaraf** [comment]
Tested with new call proposal template and generic template working fine.
