### ISSUE TITLE
Alter proposal PDF to include more details of publications

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#782]
Requires #810 

### What is the problem and why is it a problem

The title of the publication is not printed in the proposal PDF. There may be other information that instrument scientists would like that is also missing.

We have to work around space limitations in the PDF.

We should investigate whether we can include the extra information. We discussed possibly shortening the authors to "... et al." which may help.

### Steps to reproduce (if it's a bug).
Download the PDF of an ISIS Direct 2023_1 and compare it to the publication info provided.

See quote from the [ISIS Direct feedback document](https://stfc365.sharepoint.com/:w:/r/sites/isiscomputingdivision-staffsite/_layouts/15/Doc.aspx?sourcedoc=%7BCAFB6AF8-EB88-4909-9BDC-D01E031780E0%7D&file=ProposalSystemFeedback.docx&action=default&mobileredirect=true&cid=01f1cc1f-a82f-4596-85c5-3339298ce341):
> The details of the publications arising from the neutron work of the users are not printed out, despite quite detailed information input into the system.

**Comment by simonfernandes** [comment]
This is important as panels need this information and don't want to have to look up every publication DOI individually.

**Comment by simonfernandes** [comment]
**Notes from sprint planning 25/01/2023**

We should ask the user for the first author of each publication so that this can be used in the PDF

**Comment by RasmiaKulan** [comment]
### Changes Made

- Updated the Publication section within the ISIS PDF template to show `title` , `year` , `first author` , `journal name` and `DOI`.
- Amended the Publication section to show `et al.` if the user inputs additional authors.

### Before
![image](https://user-images.githubusercontent.com/69144386/220302349-5e9e25c5-f2d4-48ed-94f9-281b8c29379f.png)

### After
![image](https://user-images.githubusercontent.com/69144386/220302938-c4ee31ed-95ab-4955-9740-77849108b8d4.png)

How does this look @Cat-Lucifer? These changes are applied to the ISIS Direct template, do we need to apply this to ISIS Rapid as well?

**Comment by Cat-Lucifer** [comment]
@RasmiaKulan This looks great, thanks!  Yes, please also apply to Rapid Access and Dutch Access proposal pdfs

**Comment by Cat-Lucifer** [comment]
P.S.  And I though Brian May was the only musician with a science background 😉
