### ISSUE TITLE
As an instrument scientist, I would like the wording around research grants to be clearer

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#783]
An instrument scientist would like the wording around research grants to be changed:

> In general, the proposal system has many more steps, some of them are not obvious, and their role in the evaluation process is unclear. For example, on the page "2. Research Support" I am asked about my research grants, but it is unclear if I should list all my active research grants, only those relevant to the present proposal, or only those from which this particular research is funded.

Notes from discussion:

> Change wording from “research grants” to “grants relevant to this proposal”.

**Comment by Cat-Lucifer** [comment]
Done
