### ISSUE TITLE
As an instrument scientist, I would like it to be clearer how proposal data is used

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#784]
An instrument scientist thinks it should be made clearer how we use data:

> Also, to my understanding, this information is collected for statistical purposes alone, and should not influence the evaluation of the proposal. This should be clearly stated.

Notes from discussion:

> Add a disclaimer that data is to be used for statistical purposes, enabling us to run the proposal, and assessment of the proposal. 

Originates from the [ISIS Direct feedback document](https://stfc365.sharepoint.com/:w:/r/sites/isiscomputingdivision-staffsite/_layouts/15/Doc.aspx?sourcedoc=%7BCAFB6AF8-EB88-4909-9BDC-D01E031780E0%7D&file=ProposalSystemFeedback.docx&action=default&mobileredirect=true&cid=01f1cc1f-a82f-4596-85c5-3339298ce341).

**Comment by Cat-Lucifer** [comment]
Done
