### ISSUE TITLE
As a FAP secretary, I want to explore proposals' related experimental reports (or lack of reports), so that I can make FAP decisions based on the outcomes of previous experiments

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#785]
Instrument scientists need a way of being able to see which proposals have submitted experimental reports:

>It would be helpful if I could see in the same table, for which proposals the experimental reports have already been submitted and for which not. Currently I have to know the proposal ID to upload the experimental report, so it is easy to overlook some proposals, especially those that were submitted by other group members.

Agreed shorter term solution – this doesn't necessarily have to be integrated in the proposal software or visible to users, so long as we have some way of giving this data to scientists. 

Longer term solution - this will be part of the User Dashboard project.

Originates from the [ISIS Direct feedback document](https://stfc365.sharepoint.com/:w:/r/sites/isiscomputingdivision-staffsite/_layouts/15/Doc.aspx?sourcedoc=%7BCAFB6AF8-EB88-4909-9BDC-D01E031780E0%7D&file=ProposalSystemFeedback.docx&action=default&mobileredirect=true&cid=01f1cc1f-a82f-4596-85c5-3339298ce341).

**Comment by simonfernandes** [comment]
**Notes from meeting with Emma, Philip, Sukh and Simon 13/01/2023**

This information is already available to instrument scientists each round. We should make it clearer by adding a link to the instrument scientist quick links on the intranet which we can then direct scientists to.

**Comment by Cat-Lucifer** [comment]
Most reliable database for reports identified.  @TickleThePanda to explore a reporting option for experimental reports linked to a PI's (and Co-I's too???) name, to be in place for call end.

**Comment by simonfernandes** [comment]
Closed via https://github.com/isisbusapps/reporting-tool/pull/711 (not yet released)
