### ISSUE TITLE
As an ISIS user, I sometimes need to insert more than 3 samples

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#786]
> The new proposal system works well, but there are still some minor points which could be improved, namely: 
> 1.  possibility to insert more than 3 samples 

Agreed solution from discussion: 

We can add a message to add to proposal case if more than 3.

However, if we ever need to pull out sample information reporting, this could cause an issue.

Originates from the [ISIS Direct feedback document](https://stfc365.sharepoint.com/:w:/r/sites/isiscomputingdivision-staffsite/_layouts/15/Doc.aspx?sourcedoc=%7BCAFB6AF8-EB88-4909-9BDC-D01E031780E0%7D&file=ProposalSystemFeedback.docx&action=default&mobileredirect=true&cid=01f1cc1f-a82f-4596-85c5-3339298ce341).

**Comment by Cat-Lucifer** [comment]
Text added to included additional samples in the science case.
