### ISSUE TITLE
As an ISIS user, I would like the acquisition time per sample to be in hours

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#787]
> The new proposal system works well, but there are still some minor points which could be improved, namely: 
> 2. the acquisition time per sample should in hours (not in days) 

Agreed solution from discussion:

Change this to hours.

Originates from the [ISIS Direct feedback document](https://stfc365.sharepoint.com/:w:/r/sites/isiscomputingdivision-staffsite/_layouts/15/Doc.aspx?sourcedoc=%7BCAFB6AF8-EB88-4909-9BDC-D01E031780E0%7D&file=ProposalSystemFeedback.docx&action=default&mobileredirect=true&cid=01f1cc1f-a82f-4596-85c5-3339298ce341).

**Comment by Cat-Lucifer** [comment]
Done
