### ISSUE TITLE
As a user, I would like it to be simpler to change PI/Co-I on a proposal

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#788]
Users would like to be able to easily switch users on a proposal to different roles. Something akin to the simplicity of radio buttoms in the legacy software:

> Having a tick box selection to assign / reassign which investigator is the PI and Co-I – like we had in the old system – would save me a lot of time during and after the call.  I know some submitters would like this too. 

Originates from the [ISIS Direct feedback document](https://stfc365.sharepoint.com/:w:/r/sites/isiscomputingdivision-staffsite/_layouts/15/Doc.aspx?sourcedoc=%7BCAFB6AF8-EB88-4909-9BDC-D01E031780E0%7D&file=ProposalSystemFeedback.docx&action=default&mobileredirect=true&cid=01f1cc1f-a82f-4596-85c5-3339298ce341).

**Comment by simonfernandes** [comment]
**Notes from meeting with Emma, Philip, Sukh and Simon 13/01/2023**

PIs and Co-Is usually need switching around because a student has done something they shouldn't have (e.g. submitted a proposal as PI when they're not supposed to). Because students will be allowed to submit proposals as PIs in the next round, this is therefore not as important for Direct 2023_1. However, it is still something that would be useful and beneficial in future.

**Comment by TickleThePanda** [comment]
Have a button in the "actions" for the co-is that makes the Co-I the PI

**Comment by RasmiaKulan** [comment]
### Assigning PI mock-ups

1![image](https://user-images.githubusercontent.com/69144386/226306428-1117a22e-47d9-498d-9065-5297bac1cc22.png)

2![image](https://user-images.githubusercontent.com/69144386/226306822-31cd2eb5-2d48-4f94-98d4-1e530d2ef768.png)

3![image](https://user-images.githubusercontent.com/69144386/226307169-a964bae0-a7a8-4ca1-8fc3-7c384746a317.png)

4![image](https://user-images.githubusercontent.com/69144386/226307725-2f0ed9ca-7469-4cc3-a650-8952fdf201e5.png)

Any suggestions on which one looks appropriate? (I prefer the forth one personally)

**Comment by RasmiaKulan** [comment]
Could also add a custom button saying "Assign Principal Investigator" but it doesn't look appealing 😄
![image](https://user-images.githubusercontent.com/69144386/226315210-8b2e350a-0cb6-4c80-952f-5ddb4bf344fe.png)

**Comment by ACLay** [comment]
I don't think the icons with hover text are obvious enough at a glance to what they do. Bin is a standard icon for delete, so makes sense as an action button icon to remove a proposer, but I don't know that anything would be as instantly understandable for assign PI. And I agree that the big yellow button doesn't look nice.

If we're adding a column for principal investigator though (which I think is new in those screenshots) would it work to add an "Assign" button in a similar white & blue style to the "Add" one below?
![image](https://user-images.githubusercontent.com/2938284/226344876-dd156b37-68f0-4588-b3a5-8bedf6ef6877.png)

**Comment by RasmiaKulan** [comment]
I added the Principal Investigator column to potentially add a button like you mentioned but wasn't sure

**Comment by mutambaraf** [comment]
What happened to the up arrow like we previously discussed.

**Comment by simonfernandes** [comment]
> What happened to the up arrow like we previously discussed.

This could possibly be confused by users thinking it's related to the ordering of the Co-Is. It would require people hovering over the button to know what it is like the others I feel

> I added the Principal Investigator column to potentially add a button like you mentioned but wasn't sure

Not sure that the column makes sense if its purpose is just to house the button. What about keeping it in the actions column and just shortening it to something like 'Assign as PI' or even 'Assign PI'. That might look better?

**Comment by RasmiaKulan** [comment]
@simonfernandes Something like this?
![image](https://user-images.githubusercontent.com/69144386/226375527-02d50bef-c0d8-405b-b9ba-b1c1f6577e6a.png)

**Comment by simonfernandes** [comment]
That's what I had in mind, but with the styling that Alex suggested. But it still looks a bit odd. And I think it does probably need to say 'Assign **as** PI'.

I'm thinking that they both might need to be icon buttons or both text buttons. Something like this looks more normal to me (if you imagine the buttons on the left):

![image](https://user-images.githubusercontent.com/14293717/226388348-afbf7394-2440-4ffa-b050-23bd7db9fcc4.png)

**Comment by ACLay** [comment]
Maybe "Make PI"? It's even shorter, and I think doesn't come with the "does this sound right with(out) a word inbetween" of assign.

**Comment by RasmiaKulan** [comment]
What about "Set Pi"? It's even shorter than that.
![image](https://user-images.githubusercontent.com/69144386/226555671-b4266a87-d0ff-4ae4-8328-81bf2dd1a6a1.png)

**Comment by TCMeldrum** [comment]
Not a big fan of having a button next to the icon maybe we could somehow label the PI and Co-P with icons (excuse the MS paint):  
![image](https://user-images.githubusercontent.com/81559866/226570868-21353642-d0c2-4852-a4d3-fc6add2b9ee4.png)

**Comment by RasmiaKulan** [comment]
> I'm thinking that they both might need to be icon buttons or both text buttons. Something like this looks more normal to me (if you imagine the buttons on the left):

I think this is a good idea!
![image](https://user-images.githubusercontent.com/69144386/226571621-5102cb7c-6e3e-4cc6-8eef-55b8981a69ed.png)
What do people think about it?

**Comment by RasmiaKulan** [comment]
> Not a big fan of having a button next to the icon maybe we could somehow label the PI and Co-P with icons (excuse the MS paint): ![image](https://user-images.githubusercontent.com/81559866/226570868-21353642-d0c2-4852-a4d3-fc6add2b9ee4.png)

As Alex mentioned, I do think icons could be confusing for the users as we already have one to add a Co-Proposer. Although it would be a good idea to add icons next to PI and Co-I to differentiate between them but that could possibly confuse the users even more? I think?

**Comment by simonfernandes** [comment]
Closed via https://github.com/UserOfficeProject/user-office-core/pull/320
