### ISSUE TITLE
As an instrument scientist, I need users to be able to specify whether their proposal is an ALF request

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#789]
> ALF request (Y/N) needs adding in the sample addition Qs.  I know we asked for the result to be removed from the proposal pdf, but I didn’t realise it was missing from the questionnaire altogether.  This needs to be selectable Q under “more” on the dashboard please. 

Outcome from discussion:
> Needs adding back to questionnaire somewhere sensible and reportable 

Originates from the [ISIS Direct feedback document](https://stfc365.sharepoint.com/:w:/r/sites/isiscomputingdivision-staffsite/_layouts/15/Doc.aspx?sourcedoc=%7BCAFB6AF8-EB88-4909-9BDC-D01E031780E0%7D&file=ProposalSystemFeedback.docx&action=default&mobileredirect=true&cid=01f1cc1f-a82f-4596-85c5-3339298ce341).

**Comment by Cat-Lucifer** [comment]
Done.  @EdwardHaynes the question name for reporting purposes is "alf_request"

The system would not let me add a hyperlink to the work "here" in the ALF Info embellishment I added.  @EdwardHaynes Please can you look into this?  The link to add is https://www.isis.stfc.ac.uk/Pages/Alf.aspx and needs to be opened in a new window.  Thanks!

**Comment by EdwardHaynes** [comment]
> Done. @EdwardHaynes the question name for reporting purposes is "alf_request"
> 
> The system would not let me add a hyperlink to the work "here" in the ALF Info embellishment I added. @EdwardHaynes Please can you look into this? The link to add is https://www.isis.stfc.ac.uk/Pages/Alf.aspx and needs to be opened in a new window. Thanks!

Hi Emma, I'm having the same issue and can't find a workaround for it. It's also not clear what it doesn't like about it. This might need a new issue to address. @simonfernandes Have you come across this before?

**Comment by Cat-Lucifer** [comment]
> > Done. @EdwardHaynes the question name for reporting purposes is "alf_request"
> > The system would not let me add a hyperlink to the work "here" in the ALF Info embellishment I added. @EdwardHaynes Please can you look into this? The link to add is https://www.isis.stfc.ac.uk/Pages/Alf.aspx and needs to be opened in a new window. Thanks!
> 
> Hi Emma, I'm having the same issue and can't find a workaround for it. It's also not clear what it doesn't like about it. This might need a new issue to address. @simonfernandes Have you come across this before?

@simonfernandes to create new issue for the hyperlink problem

**Comment by simonfernandes** [comment]
Opened https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/830 for the hyperlink problem.
