### ISSUE TITLE
When editing generic template type questions  sub templates reset button has no effect on the table. 

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#795]
### What is the problem and why is it a problem
When you add, update or delete sub templates questions on a proposal and click reset button it has no effect on  the list

Affect : Users
The reset button needs to be fully implemented or disabled when a user is adding, updated or deleting sub template  questions.
### Steps to reproduce (if it's a bug).
![image](https://user-images.githubusercontent.com/71100224/212643211-1c000a8d-92bf-429f-aeb6-8a16dae85f6c.png)

![image](https://user-images.githubusercontent.com/71100224/212643511-62159bea-6c46-4199-875c-212534d4e3e1.png)

![image](https://user-images.githubusercontent.com/71100224/212643693-64e71052-21ea-4c3e-9d2b-6d0f633f9b2d.png)

No effect on the proposal.

![image](https://user-images.githubusercontent.com/71100224/212643886-8c84cd4b-b9f2-427e-a84b-464e9c8778fd.png)

**Comment by Scott-James-Hurley** [comment]
When adding a sub template, should there be a `continue` instead of a `save and continue` button?

![image](https://user-images.githubusercontent.com/44348929/230066762-ae9b95f9-6237-4e3a-acce-f8d3eec298ef.png)

**Comment by Scott-James-Hurley** [comment]
Also, the fallback when the questionary doesn't have an item id reverts all changes since the user started editing the proposal. Is this ideal behaviour?

**Comment by mutambaraf** [comment]
Just to add more context the rest was for form level reset so when mixed with the generic template it cant row back those changes. 
![image](https://user-images.githubusercontent.com/71100224/231136376-c8727c3e-7b3e-4aad-a73f-9fc78f97f6d4.png)
