### ISSUE TITLE
Hide statuses not applicable to STFC proposals

### ISSUE THREAD

**Issue by RasmiaKulan** [UserOfficeProject/user-office-project-issue-tracker#797]
### Description
The proposal system displays statuses that do not apply to STFC proposal workflows.
Although the statuses can be viewed by all three: `users` , `user officer` and `instrument scientist`, the list of all statuses can only be seen when a user officer creates the workflow or when a user officer and instrument scientist filters proposals by status. (as shown below)

![image](https://user-images.githubusercontent.com/69144386/212884782-5e50ad6a-e41e-466c-99ef-bb9bf038c876.png)

![image](https://user-images.githubusercontent.com/69144386/212885038-951b97b3-6e45-4b69-9d69-cca48f00125c.png)

**Comment by RasmiaKulan** [comment]
Based on current workflows, I believe the statuses that are relevant include:

- Draft
- EDITABLE_SUBMITTED
- EXPIRED
- Submitted (locked)

**Comment by RasmiaKulan** [comment]
This issue could be split into two where one could be about removing them from filtering and the other could be about removing them from workflow creation.

**Comment by mutambaraf** [comment]
We can also include EDITABLE_SUBMITTED_INTERNAL because we might be using it in the next call .The formatting of statues can also be standardised l think.

**Comment by simonfernandes** [comment]
Backlog pruning notes with Emma and George:

It's not that important and we might need new statuses in the future with FAP reviews and Xpress
