### ISSUE TITLE
Downloaded proposals PDFs with API  missing co proposers information through RB number

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#798]
### What is the problem and why is it a problem
When you download PDFs with an API token using proposal RB number the co proposers information is missing.

### Steps to reproduce (if it's a bug).
Download proposal PDF using its RB Number

- Example /download/pdf/proposal/567122?filter=id.
- Example /download/pdf/proposal/56711,56712?filter=id`.

**Comment by simonfernandes** [comment]
@mutambaraf Is this fixed by https://github.com/UserOfficeProject/user-office-core/pull/159 and can be closed? 🙂

**Comment by mutambaraf** [comment]
Yes closing it.
