### ISSUE TITLE
It is unclear how to set more than one deadline (eg internal/external) for a call

### ISSUE THREAD

**Issue by georgeflecknell** [UserOfficeProject/user-office-project-issue-tracker#799]
Emma Gozzard raised the question of how to set an internal and external deadline for a call.

1. How is this done, please could we have a screenshot and small explanation for how an ISIS Direct workflow with 2 deadlines should appear.
2. If an external and internal deadline is set, what is to stop submitters from re-accessing their proposals and editing after the external deadline passes? We might have an internal and external presentation of the proposals portal but it seems the proposal site itself is always accessible.

This is required for all ISIS Direct rounds. As such needed ahead of the next ISIS round in March 2023.

**Comment by simonfernandes** [comment]
Documentation should be added to the KnowledgeBase so that User Officers can take charge of this in future: https://stfc365.sharepoint.com/sites/ICD-UserProgrammeKnowledgeBase/SitePages/Creating-a-call.aspx

**Comment by RasmiaKulan** [comment]
The documentation explaining how workflows work for calls with an internal deadline have now been added to https://stfc365.sharepoint.com/sites/ICD-UserProgrammeKnowledgeBase/SitePages/Creating-a-call.aspx
