### ISSUE TITLE
Test that users can clone 23/1 proposals into the new 23/2 questionnaire

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#801]
Various questionnaire changes will take place for 23/2. It is crucial that users are still able to clone proposals from the 23/1 round into the new 23/2 round.

**Comment by simonfernandes** [comment]
See some [discussion on Teams](https://teams.microsoft.com/l/message/19:f0afa005ea5b474e83109a55c93c16f2@thread.skype/1674132411057?tenantId=3f66361c-a87e-4158-8f61-99e82db3cac8&groupId=403a668a-985f-445b-a4e3-b3a3070bb25b&parentMessageId=1674132411057&teamName=ISIS%20Computing%20Division%20Staff&channelName=Proposals%20and%20Outcomes&createdTime=1674132411057&allowXTenantAccess=false) about this.

**Comment by TickleThePanda** [comment]
According to Scott's comment, yes for ISIS 23/1.

> You can clone a proposal to another call if the other call uses the same (modified) questionnaire,
