### ISSUE TITLE
We need a new facility to export all PDFs from a round to the preFAP scoring site

### ISSUE THREAD

**Issue by georgeflecknell** [UserOfficeProject/user-office-project-issue-tracker#802]
Possibly linked to:

https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/774

The ISIS XFAP site https://stfc365.sharepoint.com/sites/FacilityAccessPanels-External and the preFAP https://stfc365.sharepoint.com/sites/fap-scoring-portal site are merging. After a meeting with Emma Gozzard and with Dylan Chambers we have some clearer requirements on where and when these PDF downloads are required. Previously we downloaded to a folder and then used that folder to give Emma Gozzard a copy and to provision the XFAP site.

NEW REQUIREMENTS:
- [ ] Make sure that PDF export scripts can put the proposal PDF files straight on the preFAP website. They should:
  - Make a new document library titled eg: 2023_2_Proposals
  - For each PDF file we need the RB number isolated either as a meta field or as file title. This is essential for the Flows on the SharePoint site to correctly allocate files.
For further clarification here please speak to Dylan Chambers.

- [ ] Create a copy of all proposal PDFs in a network folder for Emma. Usually this is to: \\isis\shares\FAPs_ISIS\FAP_YYYY_R

FUTHER CHANGES TO XFAP
- [x] Remove ancillary documents from XFAP(GEORGE TO DO)

- [x] Make sure that FAP booklets go to the preFAP review site (Dylan creating a drop point) as well as being copied to a network folder. (new issue?)

- [x] Convert XFAP site to private site for internal ISIS use (GEORGE TO DO)

Deadlines:
ISIS 2023_2 Final deadline is 5PM Tuesday 25/APR/23 for ISIS 2023_2
8th May finalised FAP allocation detail is set.

**Comment by TickleThePanda** [comment]
We need to work with Dylan and document how we're going to manually do this for this round.

**Comment by TickleThePanda** [comment]
Some documentation was written as part of #808

**Comment by TickleThePanda** [comment]
Agreed we can achieve this now manually (with the exporting script) - automation could be explored in the future.
