### ISSUE TITLE
Deploy Trino to local and dev

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#805]
After we decided to go with trino for cross-database querying between Oracle and Postgres (investigation issue: https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/755), we need to deploy it to our local docker-compose and dev kubernetes cluster.

**Comment by simonfernandes** [comment]
### Running locally

I added this to my `docker-compose.yml`:

```yaml
  trino:
    image: trinodb/trino:405
    ports:
      - 4014:8080
    volumes:
      - ${WIN_REPOS_ROOT_DIR}/trino/catalog/:/etc/trino/catalog/
```

Each database is added as a  `.properties` file:

```
C:\Programming\trino\catalog\postgresql.properties

connector.name=postgresql
connection-url=jdbc:postgresql://serverurl:port/proposal_submission
connection-user=username
connection-password=password
```

```
C:\Programming\trino\catalog\isisuserdb.properties

connector.name=oracle
connection-url=jdbc:oracle:thin:@hostname:port/servicename
connection-user=username
connection-password=password
```

### Testing queries using the Trino CLI
1. Exec into the running Trino container (`fba-compose exec trino bash`).
2. Execute the CLI using  `trino --catalog postgresql --schema public`.

2. Paste in a query:

	```sql
	SELECT prop.proposal_id,
		   per.display_name
	  FROM postgresql.public.proposals prop

		   LEFT JOIN isisuserdb.isisuserdb.reporting_person per
		   ON per.user_number = CAST(prop.proposer_id AS VARCHAR)

	 WHERE prop.proposal_id LIKE '231____';
	 ```

### Testing queries using requests

Send a POST to `localhost:4014/v1/statement` with the query in the body. To get paginated data, keep sending GET requests to the `nextUri` attribute that you get back in each response.

### Exporting query results

This probably isn't useful for this issue, but writing here for reference:

1. Exec into the Trino container as admin: `fba-compose exec -u 0 trino bash`.
2. Create a file `cat > myquery.sql` and paste in the query you want to run.
3. Run the Trino CLI specifying the previously created file to read from, and an output file (doesn't have to exist): `trino --catalog postgresql --schema public --output-format CSV_HEADER --file=myquery.sql > result.csv`
4. Copy the results file out of the Trino container into WSL: `docker cp containername:result.csv .`

**Comment by TickleThePanda** [comment]
Thank you! Much appreciated. 😄

**Comment by TickleThePanda** [comment]
@Scott-James-Hurley. You may already be planning on this but, just to make sure, when you do set this up please don't push any database passwords or secrets to GitHub, make sure they're in BisAppSettings.

One thing I'm going to be assuming (as part of https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/807) is that you're going to be setting up the service to have some form of authentication on the REST service. I'll assume `Basic` but let me know if that's going to be anything different.

**Comment by TickleThePanda** [comment]
Okay, it looks like authentication might be more difficult than that. I'll ignore it for now and we can chat about it in the future.

**Comment by TickleThePanda** [comment]
> One thing I'm going to be assuming (as part of https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/807) is that you're going to be setting up the service to have some form of authentication on the REST service. I'll assume Basic but let me know if that's going to be anything different.

In the end, I assumed no authentication but I know we'll need that for dev and prod (and possibly for local, too).

**Comment by TickleThePanda** [comment]
Now Trino is running on dev with the right creds, FITBAWEBDEV is unable to connect due to an error:
```
System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at ReportingTool.Service.Data.Trino.TrinoDatabaseReader.MakeTrinoRequest(HttpRequestMessage nextRequest) in C:\Jenkins\workspace\Dev_Build_ReportingTool\ReportingTool\ReportingTool\Service\Data\Trino\TrinoDatabaseReader.cs:line 87
   at ReportingTool.Service.Data.Trino.TrinoDatabaseReader.FetchDataFromTrino(Query query, Dictionary`2 parameters) in C:\Jenkins\workspace\Dev_Build_ReportingTool\ReportingTool\ReportingTool\Service\Data\Trino\TrinoDatabaseReader.cs:line 68
   at ReportingTool.Service.Data.Trino.TrinoDatabaseReader.RunQuery(Query query, Dictionary`2 parameters) in C:\Jenkins\workspace\Dev_Build_ReportingTool\ReportingTool\ReportingTool\Service\Data\Trino\TrinoDatabaseReader.cs:line 52
   at ReportingTool.SQLView.ExecuteQuery() in C:\Jenkins\workspace\Dev_Build_ReportingTool\ReportingTool\ReportingTool\SQLView.aspx.cs:line 666
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---<---
```

Debugging using Wireshark on `FITBAWEBDEV`, I can see that the handshake fails immediately after "Client Hello". I've compared the cipher list and it seems to have shared ciphers and so I'm a bit stuck.

Ngnix doesn't log errors by default so I will increase it to see if I can gather any more information.
