### ISSUE TITLE
Questionnaire Changes Affect Visible Proposal Information

### ISSUE THREAD

**Issue by Scott-James-Hurley** [UserOfficeProject/user-office-project-issue-tracker#809]
If a questionnaire is changed, the view screen of any proposal submitted using that questionnaire will also change. This means if a question is removed from a questionnaire, its answer will be not be visible when reviewing it. This prevents users from seeing all of a proposals information.

A potential solution could be the view screen of a proposal reflecting the questionnaire when the proposal was submitted, not the questionnaire as it currently is. Further discussion of what the solution should be and how it could be achieved should be had.

To reproduce:

- Create a call
- Submit a proposal for the call
- Remove a question from the proposal template the call uses
- View the submitted proposal
- The information from the deleted question is gone

![image](https://user-images.githubusercontent.com/44348929/215515387-f3d08d0c-1a2f-4c79-a051-6d355ed683ec.png)
Proposal with missing instrument information after its questionnaire was changed

**Comment by mutambaraf** [comment]
Another  alternative solution is to version questionnaire changes.

**Comment by mutambaraf** [comment]
There is already a solution which l think will work .

- We archive the old template.
- Export it to a file.
- Import it to create a new template current.

**Comment by TickleThePanda** [comment]
In the short term, we could look at migrating the old question data in to the new question field for the ISIS instruments - which has the highest impact.

Longer term, we should consider versioning and improved documentation.

**Comment by TCMeldrum** [comment]
For migrating the old question data for ISIS instruments I think we have 2 options run a DB script or do it through the graphql API.  I think the DB script is going to be much simpler to write but we would have to run against the DB which could be riskier. The graphql API is going to be more "proper" but requires a more complex script as we will need to get the questionary answers to add the new answer and call the answer topic method for each of the affected proposals which I think is about ~800.

Happy to have a go at implementing either option.

**Comment by TCMeldrum** [comment]
Wrote up a SQL script here: 
```
INSERT into answers (questionary_id, question_id, answer)
    SELECT an.questionary_id, 'selection_from_options_1674830891328' as question_id, an.answer from 
	answers as an join questionaries as qu 
		on an.questionary_id = qu.questionary_id 
		where an.question_id in (
			SELECT question_id from questions where natural_key in (
                                'instrument_small_angle_scattering', 
				'instrument_defraction', 
				'instrument_engineering', 
				'instrument_electronics_irradiation', 
				'instrument_reflectometry', 
				'instrument_liquid_defraction', 
				'instrument_excitations', 
				'instrument_vibrational_spectroscopy', 
				'instrument_imaging', 
				'instrument_muon', 
				'instrument_inelastic_scattering', 
				'instrument_quasi_elastic_scattering'
			)
		) 
		and template_id in (17, 30);
```
I think I have all the effected questions.

**Comment by ACLay** [comment]
I'm happy with the database approach for this instance. Might want to try and find some way of adding a UI/endpoint to simplify data migration in the future, as I doubt this'll be the only time we need to do something like this.

**Comment by simonfernandes** [comment]
Forgot to say - database approach seems fine to me to. The script also looks good as best I can tell too.

**Comment by TCMeldrum** [comment]
Cool going to go ahead with the database script and will do some more checks that my script works. Would we like the script in git anywhere maybe internal scripts

**Comment by TCMeldrum** [comment]
Scripts run successfully opened #832 #833 for template versioning
