### ISSUE TITLE
Ask users for the first author of each publication

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#810]
To enable adding more publication information in the proposal PDF (https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/782), we decided to ask the user for the "first author" and "others" of each publication. This will enable us to shorten the list of authors to "first author et al." to save space.

**Comment by Cat-Lucifer** [comment]
@simonfernandes I can't add in a first author text box as I can't see how to edit this sub template - see image.  There doesn't seem to be any info to edit.  I'm sure I'm doing something wrong, but I haven't had this issue with other sub templates.

![image](https://user-images.githubusercontent.com/108054517/217486673-e6230a06-b7d7-455b-83ae-21460a52630c.png)

**Comment by simonfernandes** [comment]
@Cat-Lucifer To get to that screen, you will have already clicked edit on the publication, and this is the window to edit it now. You can edit existing questions by clicking on them or click the 3 dot button in the top right for more options. Also, I think you should be on ISIS Publications instead:

![image](https://user-images.githubusercontent.com/14293717/217495585-2cfbd82f-36c1-4f60-8f7e-70557836f57d.png)

**Comment by Cat-Lucifer** [comment]
Thanks @simonfernandes I was on the incorrect sub template!

**Comment by Cat-Lucifer** [comment]
Done.  @EdwardHaynes @simonfernandes the Q name for reporting purposes is "first_publication_author"

**Comment by Cat-Lucifer** [comment]
@RasmiaKulan
