### ISSUE TITLE
Unwanted term “Instrument” and “Instrument Scientist”

### ISSUE THREAD

**Issue by sukhsingh2525** [UserOfficeProject/user-office-project-issue-tracker#814]
Whilst doing the demo for the IS role - stakeholders suggested that on the system there were terms such as “Instrument” and “Instrument Scientist” which are not associated with HPL. 

An more appropriate name to replace would be "Facility".  A facility would include areas such as Vulcan, Gemini and EPAC in the future potentially, across the whole system.

**Comment by TCMeldrum** [comment]
Possible options we should consider:

### Setting table:

We set some add strings in the settings table and pull them in the settings table and then pull them in from the settings context wherever they are needed. 

Advantages:

- Small changes 
- No new technologies
- Can be setup to be edited in the frontend

Disadvantages:

- Not very expandable if we have more than just the change language in this PR 
- Could get lost in all the other settings as well as bloating the settings with all variations like plurals and singulars

### Some new localization tables:
We create some localization table and use it like the context of the setting and pull out the starings where needed. 
Advantages:

- No new technologies
- Pretty simple
- Can be setup to be edited in the frontend

Disadvantages:

- Could be unwheledy
- Duplicating setting and features 

### Some kind of localization package
These are normally used for having multiple languages in one website and being able to toggle between them. The popular one seems to be: react-i18next alothough there are others like react-localization

Advantages:

- Does all the heavy lifting for us
- Easy to expand
- Could use it for other langauges in the future if we want that

Disadvantages:

- Would need to hardcode the options in the frontend or would still need to read them from the backend

**Comment by simonfernandes** [comment]
@TCMeldrum Re-opening this as while I think we have the framework in place, the terms still need to be changed.

**Comment by TCMeldrum** [comment]
No worries let me know if you need any clarification on what I did. I changed all of the instances of instrument, and instrument scientist I found. What further changes are needed sorry?

**Comment by simonfernandes** [comment]
I think you've done all of the heavy lifting and groundwork required, and we just need to now change the two terms in https://github.com/UserOfficeProject/user-office-core/blob/develop/apps/user-office-frontend/public/locales/override/translation.json 🙂

**Comment by TCMeldrum** [comment]
They should be hosted here: https://git.devs.facilities.rl.ac.uk/isisbusapps/BisAppSettings/src/branch/develop/secret-config/base/proposals/locales/translation.json and mounted on through a config map the ones in the core repo are the default for the ESS and probably shouldn't be changed.

**Comment by simonfernandes** [comment]
Oh I seee, sorry - looks perfect then! I will reassign you and close. Thanks for clearing that up :)

**Comment by TCMeldrum** [comment]
No worries, sorry if it was unclear before
