### ISSUE TITLE
Populate consumables automatically from the new proposal submission software

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#818]
### Context

Since we have moved to the new software, we have lost the ability for approved proposals to request consumables. A user can only make a consumable if there is an entry for the proposal if the correct consumable tables are filled in, in the `IOPS_V4` database. The user office used to follow a workflow in the ISIS consumables MS Access tool to load the allocated proposals with UK investigators (not sure if it's just with UK PIs) into the consumable tables.

At the moment, we are manually populating the consumables tables whenever a user can't access it.

In the long term, we will replace consumables with something not built using Struts which is aware of the new proposal submission software.

### Suggested short term solution

A script that we can run after the FAPs have completed that will automatically populate the consumable tables with the correct values.

**Comment by EdwardHaynes** [comment]
To add a consumable to the system you need to add entries to the following tables in IOPS_V4:

- NEW_CONSUMABLES_USER: Add an entry to this table with the RB Number and User number.
- NEW_CONSUMABLES_REQUEST: Add an entry filling in all the fields but leaving SUBMITTED_BY and SUBMITTED_DATE blank. NOTE: The ID in NEW_CONSUMABLES_REQUEST is the same as the RB number and may not work if it's different.

**Comment by mutambaraf** [comment]
This are the two jobs for prod and dev  respectively `Prod_Execute_XFap.ProposalPopulateConsumables and Dev_Execute_XFap.ProposalPopulateConsumables`.
