### ISSUE TITLE
As a user l can not answer generic template questions on the first step

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#819]
### What is the problem and why is it a problem
When we use a template with a generic question on the first page users will not be able to answer the question without clicking save first.

This will affect users.

### Steps to reproduce (if it's a bug).

- Create a proposal template with a generic template on the first page.
- Create a call using the template.
- As a user try to answer the questions from the top before clicking save button

![image](https://user-images.githubusercontent.com/71100224/217779303-85598a45-2984-4d4a-9387-0a18c61898ee.png)

**Comment by simonfernandes** [comment]
Backlog pruning notes:

We don't currently have a need to put it on the first topic.
