### ISSUE TITLE
Error on logout

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#829]
### What is the problem and why is it a problem
Error on logout on local dev.
`{"error":"{\"userMessage\":\"Something went wrong!\",\"error\":{\"response\":{\"errors\":[{\"message\":\"Cannot return null for non-nullable field Mutation.logout.\",\"locations\":[{\"line\":2,\"column\":3}],\"path\":[\"logout\"],\"extensions\":{\"code\":\"INTERNAL_SERVER_ERROR\",\"stacktrace\":[\"Error: Cannot return null for non-nullable field Mutation.logout.\",\"    at completeValue (/app/node_modules/graphql/execution/execute.js:594:13)\",\"    at /app/node_modules/graphql/execution/execute.js:486:9\",\"    at runMicrotasks (<anonymous>)\",\"    at processTicksAndRejections (node:internal/process/task_queues:96:5)\",\"    at execute (/app/node_modules/@apollo/server/src/requestPipeline.ts:528:31)\",\"    at processGraphQLRequest (/app/node_modules/@apollo/server/src/requestPipeline.ts:427:26)\",\"    at internalExecuteOperation (/app/node_modules/@apollo/server/src/ApolloServer.ts:1283:12)\",\"    at runHttpQuery (/app/node_modules/@apollo/server/src/runHttpQuery.ts:232:27)\",\"    at runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/src/httpBatching.ts:85:12)\",\"    at ApolloServer.executeHTTPGraphQLRequest (/app/node_modules/@apollo/server/src/ApolloServer.ts:1058:14)\"]}}],\"data\":null,\"status\":200,\"headers\":{\"map\":{\"access-control-allow-origin\":\"*\",\"cache-control\":\"no-store\",\"content-length\":\"1106\",\"content-type\":\"application/json; charset=utf-8\",\"date\":\"Tue, 21 Feb 2023 12:15:23 GMT\",\"etag\":\"W/\\\"452-PdU1aNhpu0vdBdCcBxRQAWeME9o\\\"\",\"x-powered-by\":\"Express\"}}},\"request\":{\"query\":\"mutation logout($token: String!) {\\n  logout(token: $token)\\n}\",\"variables\":{\"token\":\"`

### Steps to reproduce (if it's a bug).
Login to the system.
Press logout

Error logs from developer tools.
![image](https://user-images.githubusercontent.com/71100224/220343307-d6fbd168-eb9a-4618-a3fd-d126041d92bc.png)

**Comment by simonfernandes** [comment]
Closing as we're not sure this is still an issue
