### ISSUE TITLE
As a user officer, I cannot add links/images to embellishment questions

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#830]
When adding an embellishment question, you cannot interact with any of the embellishment pop up windows. This stops you from being able to click/type in it to add things like links, images, etc.

Issue found in #789.

![image](https://user-images.githubusercontent.com/14293717/220896927-3f5ba2b8-21cd-472f-8216-d4cb0298779a.png)

**Comment by simonfernandes** [comment]
Seems resolved

**Comment by simonfernandes** [comment]
@Cat-Lucifer We're closing this as it seems to be resolved.

**Comment by Cat-Lucifer** [comment]
@simonfernandes Thanks Simon.  I'm still having the same issue for sub-templates though (when I tried to set a link in the embellishment "alf_info"

**Comment by simonfernandes** [comment]
@Cat-Lucifer Ah damn it's the same for me, in that case I'll reopen! I only tested it with a notice ("Pages" section).

**Comment by Cat-Lucifer** [comment]
@simonfernandes Please can we bump this one up - can look at workload and discuss tomorrow.  Thanks

**Comment by zvailanu98** [comment]
4AEE18F83AFDEB23
