### ISSUE TITLE
Questionnaire setup setting incorrectly  empty string to min/max values

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#831]
There is something in the questionnaire setup that incorrectly gives an empty string to min/max values, and then this affects both viewing the template as a user officer (this issue) and accessing the call as a user (Scott's issue)

### What is the problem and why is it a problem

This  issue prevent proposals from being created through the new proposal system for ISIS Rapid. When you select the call to create a new proposal a dialogue appear saying "Something went wrong". 

### Steps to reproduce (if it's a bug).
For context some changes to some of ISIS proposal questions in the Rapid and Dutch Access routes this morning. This may or may not have some bearing on the issue

Logs
` INFO - GraphQL response contained error(s) {"errors":[{"message":"Int cannot represent non-integer value: \"\"","locations":[{"line":143,"column":5}],"path":["blankQuestionarySteps",1,"fields",3,"config","min"]},{"message":"Int cannot represent non-integer value: \"\"","locations":[{"line":144,"column":5}],"path":["blankQuestionarySteps",1,"fields",3,"config","max"]}]}`

More logs
`{    
    "errors": [
        {
            "message": "Int cannot represent non-integer value: \"\"",
            "locations": [
                {
                    "line": 143,
                    "column": 5
                }
            ],
            "path": [
                "blankQuestionarySteps",
                1,
                "fields",
                3,
                "config",
                "min"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        },
        {
            "message": "Int cannot represent non-integer value: \"\"",
            "locations": [
                {
                    "line": 144,
                    "column": 5
                }
            ],
            "path": [
                "blankQuestionarySteps",
                1,
                "fields",
                3,
                "config",
                "max"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ],
    "data": ...
}`

Current solution:
@simonfernandes  db script `SELECT *  FROM questions WHERE default_config::json->>'max' = '' OR default_config::json->>'min' = ''`

Might be related to issue: https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/746

**Comment by simonfernandes** [comment]
Related issue I posted in Teams today:

> [This report](https://office.facilities.rl.ac.uk/reporting/SQLView.aspx?category=isis-proposals&query=proposals-not-yet-submitted&instruments=%2A&start_date=01%2F01%2F2020) I wrote is failing to execute where the days requested can't be cast as an integer. One proposal is causing the problem because it somehow has an answer with an empty string instead of null. It looks like a bug very similar to [this one](https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/831). I can protect against it in the SQL but it seems in this case we'd do better to adjust the value for this proposal in the database and fix the root problem in the software. What do people think?

Here is the problematic answer's JSON:

```json
{
    "value": {
        "unit": null,
        "value": ""
    }
}
```

We'd expect to see a number for the inner value if the question has been answered, or `null` for the entire answer if it hasn't (i.e. is an unsubmitted proposal).

**Comment by simonfernandes** [comment]
Agreed with Farai that we can close this now as it hasn't been an issue for a long while.
