### ISSUE TITLE
Failed to initialize db

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#835]
### What is the problem and why is it a problem
Dev is failing to start backend is crashing.

`{"message":"DO\n$$\nBEGIN\n    IF register_patch('AddTimedLogoutWarningfeature.sql', '****', 'Create STFC idle warning feature', '2023-02-14') THEN\n\n    INSERT INTO features(feature_id, description) VALUES ('STFC_IDLE_TIMER', 'STFC idle warning popup');\n    INSERT INTO settings(settings_id, description) VALUES ('IDLE_TIMEOUT', 'Timeout for Idle timer in milliseconds');\n\n    END IF;\nEND;\n$$\nLANGUAGE plpgsql; - duplicate key value violates unique constraint \"settings_pkey\"","error":{"length":399,"name":"error","severity":"ERROR","code":"23505","detail":"Key (settings_id)=(IDLE_TIMEOUT) already exists.","where":"SQL statement \"INSERT INTO settings(settings_id, description) VALUES ('IDLE_TIMEOUT', 'Timeout for Idle timer in milliseconds')\"\nPL/pgSQL function inline_code_block line 6 at SQL statement","schema":"public","table":"settings","constraint":"settings_pkey","file":"nbtinsert.c","line":"527","routine":"_bt_check_unique"},"obj":{"__knexUid":"__knexUid1","__knexTxId":"__knexUid1","method":"raw","sql":"DO\n$$\nBEGIN\n    IF register_patch('AddTimedLogoutWarningfeature.sql', 'Thomas Cottee Meldrum', 'Create STFC idle warning feature', '2023-02-14') THEN\n\n    INSERT INTO features(feature_id, description) VALUES ('STFC_IDLE_TIMER', 'STFC idle warning popup');\n    INSERT INTO settings(settings_id, description) VALUES ('IDLE_TIMEOUT', 'Timeout for Idle timer in milliseconds');\n\n    END IF;\nEND;\n$$\nLANGUAGE plpgsql;","bindings":[],"options":{},"__knexQueryUid":"phYZhnhH0EDLVhPMGMWN8"},"QueryName":"DO\n$$\nBEGIN\n    IF register_patch('AddTimedLogoutWarningfeature.sql', 'Thomas Cottee Meldrum', 'Create STFC idle warning feature', '2023-02-14') THEN\n\n    INSERT INTO features(feature_id, description) VALUES ('STFC_IDLE_TIMER', 'STFC idle warning popup');\n    INSERT INTO settings(settings_id, description) VALUES ('IDLE_TIMEOUT', 'Timeout for Idle timer in milliseconds');\n\n    END IF;\nEND;\n$$\nLANGUAGE plpgsql;"}`

![image](https://user-images.githubusercontent.com/71100224/221876040-049f6b3c-2bd4-404d-a7b7-f75892b6bd29.png)

**Comment by simonfernandes** [comment]
Fixed by Tom in https://github.com/UserOfficeProject/user-office-core/pull/200
