### ISSUE TITLE
Proposal links in portal  routing to local host. 

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#836]
### What is the problem and why is it a problem
New proposal system in both dev and prod  reroutes users to local host through settings in database. When this happens users will not be able to access the new proposal system. 

All system users are being affected.

**Comment by mutambaraf** [comment]
Current solution manually setting values in both prod and dev each time this happens. We also have a medium term solution waiting for release https://github.com/isisbusapps/proposal-submission/pull/1723 .A long term solution is to investigate system logs in the database.

**Comment by simonfernandes** [comment]
Closing as we now use the launchpad

@mutambaraf Please re-open if this is still an issue
