### ISSUE TITLE
Error while trying to remove either min or max value from a question

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#837]
### What is the problem and why is it a problem

When you try to remove max or min values when updating  Rich Text Input or Text Input the system produces an Error. 
This is affecting user officer role. 
### Steps to reproduce (if it's a bug).
(As a user officer)
1. Go to any template.
2. Create a Rich Text Input or Text Input and set the min or max values and save.
3. Select the same question and remove either max or min value and try to save.

![image](https://user-images.githubusercontent.com/71100224/223117593-d7f59036-1154-4c92-85a0-6616f9223f60.png)
`An unhandled error was caught from submitForm() Error: Int cannot represent non-integer value: "": {"response":{"errors":[{"message":"Int cannot represent non-integer value: \"\"","locations":[{"line":108,"column":5}],"path":["updateQuestion","config","min"],"extensions":{"code":"INTERNAL_SERVER_ERROR","stacktrace":["GraphQLError: Int cannot represent non-integer value: \"\"","`

**Comment by mutambaraf** [comment]
Might be related to this issue https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/831

**Comment by simonfernandes** [comment]
Please email Sarah Needham (or let me know and I'll do it) when this bug is resolved, as I have now made her aware of this bug.

**Comment by bashanlam** [comment]
@CatLucifer please find our suggestion of adding the above queries to the Reporting Tool so as to extract the answers to all questions for each technique. This is the best cost-effective solution we have at the moment indeed. Love to know your thought.

**Comment by mutambaraf** [comment]
@bashanlam should we not close this.
