### ISSUE TITLE
Allow bulk downloading of technical spec files for HPL

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#843]
HPL will need a way of being able to bulk download all technical spec files (uploaded with each proposal) ahead of the FAPs.

The technical specification (or technical pack) is a word document file that goes out with the call of access. PIs and their team fill it out with diagnostics info they are hoping to use and upload it as part of the proposal process. This allows HPL to do an assessment ahead of the FAPs from a technical perspective.

**Comment by mutambaraf** [comment]
This can be implemented by expanding the way we download proposals to include the following query strings `template questions ids ,pdf template id  and  attachment types`.

**Comment by mutambaraf** [comment]
@simonfernandes will the users upload it as a word document or a pdf document when they submit their proposals.

**Comment by simonfernandes** [comment]
I'm not sure, have a look at the question in the HPL template or @voduguwa will know

**Comment by mutambaraf** [comment]
Okay l checked looks  we will need to also download doc and they are not supported by the factory.
