### ISSUE TITLE
Update remaining post-call ISIS reports in the Reporting Tool

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#844]
These are the reports that Emma has identified as post-round reports needed: [FAP Queries.xlsx](https://github.com/UserOfficeProject/user-office-project-issue-tracker/files/9281760/FAP.Queries.xlsx).

Each one needs to be updated in the Reporting Tool so that includes both legacy and current proposal software data. Some are already complete.

Summary of reports yet to be completed:

| When? | Report |
| --- | --- |
| Immediately after call closure | https://office.facilities.rl.ac.uk/reporting/SQLView.aspx?category=funding&query=indian-funding-proposals |
| Immediately after call closure | https://office.facilities.rl.ac.uk/reporting/SQLView.aspx?category=users&query=isis-proposal-pi-and-co-is-for-year-and-round |
| Immediately after call closure | https://office.facilities.rl.ac.uk/reporting/SQLView.aspx?category=funding&query=proposal-and-student-industrial-links | 
| Immediately after call closure |  https://office.facilities.rl.ac.uk/reporting/SQLView.aspx?category=isis-proposals&query=deuteration-facility-request-proposals
| Immediately after call closure |  https://office.facilities.rl.ac.uk/reporting/SQLView.aspx?category=isis-proposals&query=diamond-facility-request-proposals
| Immediately after call closure |  https://office.facilities.rl.ac.uk/reporting/SQLView.aspx?category=samples&query=sample-environment-category-for-proposals&year=22&rounds=2
| After results issued | All ISIS equal opportunities reports

**Comment by TickleThePanda** [comment]
If we're going to look at doing anything for this round for these, we could convert them so that they only get data from the new software, if that simplifies it.
