### ISSUE TITLE
Poster for the "ISIS User meeting" (NMSUM)

### ISSUE THREAD

**Issue by RasmiaKulan** [UserOfficeProject/user-office-project-issue-tracker#845]
Design a poster for the UK Neutron & Muon Science and User Meeting to represent:

- Who P&O, S&O and U&A are / what you do / what’s your scope
- Focus on the impact to the user (rather than technical detail) on:
- Recent developments
- Current projects
- Future roadmap
- An MS Form for feedback on the software systems through a QR link on the poster
- A business card with the introduction and QR code on it for people to take away

**Comment by RasmiaKulan** [comment]
### **Poster**

![Image](https://user-images.githubusercontent.com/69144386/232787457-386779d0-bf7b-4006-af9f-f38448150b00.png)




### **Business Card**

![Image](https://user-images.githubusercontent.com/69144386/232787122-f86475fc-bca6-4af6-b24a-67b5a7c67daf.png)

**Comment by simonfernandes** [comment]
Closing as complete
