### ISSUE TITLE
As a user officer will want to be able to pause submission of proposals 

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#846]
Sometimes as a user officer would like to pause proposal submission with out necessary closing a call. At the current moment 
pausing call can only be done through closing a call which potential send events to RabbitMQ and trigger call close event on the proposals already created.

**Comment by simonfernandes** [comment]
Backlog pruning notes:

This would be nice, but closing and re-opening calls to serve the same purpose is fine and Emma is happy to keep doing this.
