### ISSUE TITLE
Co-proposer edit tool in proposal submission is not working correctly

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#847]
### What is the problem and why is it a problem
Opening the tool shows a list of previously added users, some of the checkboxes for these do not work, some add the user multiple times when clicked. Additionally, if a list of users in the display extends beyond a certain amount the "UPDATE" button is hidden behind a scrollbar rather than always being present in the view. 

### Steps to reproduce (if it's a bug).
a) clicking a user in the list often selects them more than once (only the circled control was clicked), perhaps not a problem but completely confusing:
![image](https://user-images.githubusercontent.com/71100224/233578379-35d10cf9-2273-4b0e-a4ff-85843deab049.png)
b)Clicking a user checkbox does nothing, as above perhaps not a problem but bad usability:
![image](https://user-images.githubusercontent.com/71100224/233578510-2817687a-7c8b-4659-964e-32f00853460e.png)
c) controls are hidden behind the overflow rather than being fixed at the base of the window, in this user's case they had no idea how to proceed without using the "x", thinking this would save changes
![image](https://user-images.githubusercontent.com/71100224/233578610-64dc7504-a4f0-4dd2-8f46-1ad2a2fc7a77.png)

**Comment by mutambaraf** [comment]
All of these can be tested if viewing the user's proposal that he mentions: 2320101

**Comment by simonfernandes** [comment]
Some of these may have been fixed by Martin in https://github.com/UserOfficeProject/user-office-core/pull/227

**Comment by simonfernandes** [comment]
Hi @mutambaraf, please would you mind checking whether this issue is still applicable or can be closed off after https://github.com/UserOfficeProject/user-office-core/pull/227? Maybe problem A is also caused by using local test data?

**Comment by mutambaraf** [comment]
This is now sorted.
