### ISSUE TITLE
Have a direct proposal PDF link in the proposal site for proposals

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#855]
We would like to be able to have a proposal PDF link which can be shared with other systems that are not able to use tokens to connect to our  API for authentication.

**Comment by simonfernandes** [comment]
This was brought up by @georgeflecknell while wanting to link to proposal PDFs from the pre-FAP scoring site. As a workaround, we linked to the search URL of each proposal. Unless problems with this are brought up in the future, this is probably a low priority nice to have feature.

**Comment by simonfernandes** [comment]
See what our options are and how much work each would require, and discuss with Emma. Currently Emma stores all PDFs in her OneDrive to share with scientists.

**Comment by mutambaraf** [comment]
The download link `/download/pdf/proposal/<RB16>?filter=id` needs work in the component to make it work.

**Comment by mutambaraf** [comment]
Design review notes:

1. Link ?reviewModal=1 to RB numbers
2. Fix rerouting to go to previous point before being logged out.
3. Allow passing of extra query parameters  with access token.

**Comment by mutambaraf** [comment]
We can now link directly to a proposal with 

1. `/?token=<sessionid>&proposalid=<rbnumber>`
2. `/?proposalid=<rbnumber>`
3. `/?sessionId=<sessionid>&proposalid=<rbnumber>`

**Comment by ACLay** [comment]
Just to check, is there a direct link to the PDF? Or just to the proposal, and users then have to scroll down and hit the pdf button?

**Comment by mutambaraf** [comment]
We currently don't have a direct link to the pdf but to the proposal itself. I think this gives more value because sometimes someone just need proposal information rather than the pdf form.
