### ISSUE TITLE
ISIS commercial/calibration users will be able to access legacy proposals

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#86]
Split from https://github.com/UserOfficeProject/stfc-user-office-project/issues/27

/overwrite opened 2020-09-04

**Comment by TickleThePanda** [comment]
We should size this after #82

**Comment by simonfernandes** [comment]
No longer required, see https://github.com/isisbusapps/proposal-submission/issues/1712
