### ISSUE TITLE
Production proposals legacy blaats need to be updated

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#863]
### What is the problem and why is it a problem
Production proposal Blaats are currently failing because of the switch to proposal launchpad as the new landing home page. This is the Jenkins job [Prod.External_BLAATs_Proposal](https://ci.devs.facilities.rl.ac.uk/view/.Wallboard.ProposalsAndOutcomes/job/Prod.External_BLAATs_Proposal/)

**Comment by simonfernandes** [comment]
We've decided this isn't worth doing in sprint planning.
