### ISSUE TITLE
Fix proposal lookup dev deployment job

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#864]
There is need to fix Dev_Deploy_ProposalLookup job which is failing .
[Dev_Deploy_ProposalLookup](https://ci.devs.facilities.rl.ac.uk/view/.Wallboard.Failed/job/Dev_Deploy_ProposalLookup)
### What is the problem and why is it a problem

The job is failing because it can not find current deployed application.
```
Checking if we can find the artifact to deploy
Finding out what applications are deployed
Finding application matching proposal-lookup-war
Could not find artifact to undeploy matching proposal-lookup-war, skipping this step
```

**Comment by simonfernandes** [comment]
Is this one good to be closed now @mutambaraf?
