### ISSUE TITLE
Investigate how to do FAP member management 

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/user-office-project-issue-tracker#868]
There is a way of manging  SEP/FAP member management in the software we should investigate this as a replacement for the FAP member management tool.

**Comment by simonfernandes** [comment]
You can have a look at the old requirements document for the panel member manager for a decent idea of what the Access tool currently does (can't guarantee that it covers everything or is accurate now):

https://stfc365.sharepoint.com/:w:/r/sites/proposals-and-outcomes-transformation-programme/Projects/FAP%20members%20tool.docx?d=w1792579146034c44879633bcef1eca0b&csf=1&web=1&e=WdjiRN

**Comment by Scott-James-Hurley** [comment]
Notes from the meeting with Users:
- Users has just done a WSDL release - they plan to never do one again
- Before next planned WSDL release, they hope the REST API will be able to replace the current SOAP implementation
- REST is about 30% complete
- REST API 1st phase planned to be finished by Christmas
- New method will be put in REST API
- The Roles domain is in a bad state right now - it's difficult to understand
- Method will need an API key, could limit method call to those in user office
- The REST API is not written out yet
- The proposals system is on another domain, will need to figure out how they'll talk
- Users will need help with testing the new roles method and connecting to the REST API
- The requested role method could be one of the first test methods used for connecting between apps
- Question of how JWT keys interact with different domains
- We won't have to move everything over to the REST API
- After User's sprint intermission (about 4 weeks time) Vlad will be able to work with us to implement method for testing (October/November)

Security:

- If a user is logged in and accessing a method, use jwt token
- If a program calling the API with no user attached to it, use an API key
- Use one or the other

Actions:

- Write issue in User repos enumerating roles and what they need to do

**Comment by ACLay** [comment]
Users REST updates from yesterday's planning discussions:
- Initial rest endpoints are nearly ready for dev, but main goal is to allow replacement of their struts 1 user establishment details app
- They're gonna do some work planning in the next week or so, but it sounded hopeful that the role setting endpoint we need could be added sooner rather than later.

**Comment by TCMeldrum** [comment]
Investigation complete opened #961 to track open issues for this
