### ISSUE TITLE
We should Add an STFC grading Guide 

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/user-office-project-issue-tracker#871]
A STFC grading guide needs to be written and added to the system

**Comment by ACLay** [comment]
This information is already in a document that Emma has. We should be able to upload or extract what we need from that.

**Comment by TCMeldrum** [comment]
Yeah looks like we just need to upload it to the pages tab the as a user officer, no code changes are needed. Although we might want to store it elsewhere as well
