### ISSUE TITLE
Proposals fail to load as an experiment scientist

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#872]
After Thursday 06/07/23 release, when you switch roles to Experiment Scientist, the Proposals page fails to load all proposals. 

If you wait for the Call dropdown filter to populate, or use a direct link to a call (e.g. https://proposal.facilities.rl.ac.uk/?call=154), then it does work.

![err](https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/14293717/9cd64b7f-f97b-4553-9a43-209092ec975a)

**Comment by mutambaraf** [comment]
I run a couple of queries for the backend it looks like we are trying to load to many proposals over a view .I think if we limit to 2000 then allow users to set higher thresholds with a warning that it can result in errors. Beyond 5000 l started to see errors 
`query{
  instrumentScientistProposals(first:5000, filter: {reviewer: ALL, proposalStatusId: 0 }){
    proposals {
      primaryKey
      proposalId
      title
      submitted
      finalStatus
      technicalReviewAssigneeId
      technicalReviewAssigneeFirstName
      technicalReviewAssigneeLastName
      technicalStatus
      technicalTimeAllocation
      statusName
      technicalReviewSubmitted
      instrumentId
      instrumentName
      allocationTimeUnit
      callShortCode
      statusName
      sepCode
      principalInvestigator {
        firstname
        lastname
        preferredname
        organisation
        email
      }
    }
    totalCount
  }
  
}`

**Comment by mutambaraf** [comment]
@Cat-Lucifer this looks like it is sorted. I did some check in prod.

**Comment by Cat-Lucifer** [comment]
Fab, thank you.  @simonfernandes Please can you update you're initial comms to instruments scientists about this and say it is all resolved.

**Comment by simonfernandes** [comment]
@Cat-Lucifer Email sent now
