### ISSUE TITLE
Duplicate co-proposers can appear in proposal PDFs

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#873]
Emma just reported that co-proposers were sometimes duplicated in proposal PDFs in the ISIS Direct 23/2 round. It didn't appear to cause any issues other than confusion and unprofessionalism.

**Comment by simonfernandes** [comment]
@Cat-Lucifer Do you have any reference numbers of proposals that were affected by this?

**Comment by Cat-Lucifer** [comment]
@simonfernandes There are lots (maybe a quarter to a third of all proposals).  I've listed a fair few to cover a range of instances, both internal and external:  2320008, 011, 024, 035, 062, 077, 111, 219, 222.  Thanks!

**Comment by mutambaraf** [comment]
Is this affecting ISIS Direct 23/2 round only or even some ISIS Direct 23/1 round proposal pfs .Because l  thought we removed the possibility of double co-proposers .People are working hard it must be just an edge case that went through.

**Comment by Cat-Lucifer** [comment]
@mutambaraf @simonfernandes This issue was originally raised after the 23-1 round.  We all believed it was resolved, but it has re-occurred numerous times on 23-2 round proposals.  I understand people are busy, but, as I said, about a quarter of proposals were affected, so this is more than an edge case.

**Comment by simonfernandes** [comment]
Hmm, just checked a couple of the above: 

2320008 - unique co-is in database, unique in pdf
2320011 - unique co-is in database, unique in pdf

There have been some significant changes to the internal workings of the Co-I and PI modals since the last round (ESS refactoring and Rasmia's quick switch between Co-I and PI coming soon), so it's quite possible this will no longer be a problem. But we should probably do some investigation and testing here.

**Comment by mutambaraf** [comment]
I just check also looks sorted but we also need to update the downloaded pdfs in shared proposals-by-call-id\prod\.I can quickly do that and move the previous proposals to ISIS_2023_2_OLD @Cat-Lucifer  can then get the latest versions with out duplicates.

**Comment by Cat-Lucifer** [comment]
@mutambaraf Don't worry about updating these.  Thanks anyway! 🙂

**Comment by mutambaraf** [comment]
More testing before September.

**Comment by simonfernandes** [comment]
I wasn't able to replicate this bug, or find issues with any of the previous proposals. It's possible this might be fixed. For now I've added a check and error logging that should make it more visible if and when this happens again: https://github.com/UserOfficeProject/user-office-core/pull/301.
