### ISSUE TITLE
Investigate how instrument scientist might see other proposals not assigned to there instrument

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/user-office-project-issue-tracker#877]
Instrument scientists may want to see proposals from the same facility but on different instruments.

**Comment by TCMeldrum** [comment]
Currently, the `StfcProposalDataSource` checks to see if a users instrument is on a call and then will return all proposals on that call. So if the system ends up set up like we think then all users on instruments on the same call (so a facility's worth of instruments) will see all proposals on that call which I believe is what we want. 

The only hic-up would be if scientists instrument is not on the call like if TS1 is taking proposals for example.

We should keep this in mind if we ever need to do any work on #874

**Comment by srconway** [comment]
We think this isn't an issue but needs to be confirmed

**Comment by TCMeldrum** [comment]
Testing on dev, I can't see another instruments on the same call. Looks like it was changed in the PR linked in the issue to only return proposals on that instrument when it should be able to see all proposal on the call. I think it should, may need changing again, so users can see other proposals on the call that there instrument is on.

**Comment by srconway** [comment]
Closed by #577
