### ISSUE TITLE
As a FAP secretary, I'd like some dates in proposal PDFs to exclude timestamps

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#879]
When using a custom PDF template, all of the dates in the generated PDF have a timestamp, e.g.

> Start Date:
> 2022-07-31T23:00:00.000Z
> Finish Date:
> 2024-03-31T00:00:00.000Z

Sometimes only the date is needed and so the timestamp is just extra noise.

Originally requested via Sarah Needham of LSF.

**Comment by TCMeldrum** [comment]
Since this is conserning FAPs would you like us to look into it?

**Comment by simonfernandes** [comment]
@TCMeldrum Sure, thanks. I think this is fairly low priority but I'll remove it from our project tracker and you can add it to yours then
