### ISSUE TITLE
User officer proposals table has some columns not sorting

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#881]
### What is the problem and why is it a problem
The user office proposal table is not able to sort by  the following column principal investigator name ,PI email, submitted and notified  

### Steps to reproduce (if it's a bug).
When you select any of principal investigator name ,PI email, submitted or notified the table show blank data.
![image](https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/71100224/7b3f392b-68cf-4987-bf1b-fa5d10067433)

**Comment by mutambaraf** [comment]
Related to https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/913

**Comment by srconway** [comment]
Adrian has been chasing on this one. Could you let him know when this one is released to production.
