### ISSUE TITLE
Update ISIS PI & Co-Is between dates report

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#885]
Update the report to include both new and old proposal data.

https://office.facilities.rl.ac.uk/reporting/SQLView.aspx?category=isis-investigators&query=proposal-pi-and-co-is-between-dates&start_date

~Report already exists for year and round, so we should be able to simply re-use that query and update the filter.~

**Comment by Cat-Lucifer** [comment]
Cannot use the year and round query as user account email and user details at the time of submission are required.
