### ISSUE TITLE
Update requested ALF days ISIS report

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#887]
Update the report to include both new and old proposal data.

https://office.facilities.rl.ac.uk/reporting/SQLView.aspx?category=isis-proposals&query=requested-alf-days

**Comment by simonfernandes** [comment]
@Cat-Lucifer There's a single input for this query of `start_rb` - is this still ok?

**Comment by Cat-Lucifer** [comment]
@simonfernandes Yep this is fine, thanks

**Comment by simonfernandes** [comment]
@Cat-Lucifer The existing ALF report shows legacy proposals that have said yes to alignment being required for their sample (presumably only ALF users would have selected this option?). I won't change this logic unless you want me to.

For new proposals, there isn't an ALF instrument option, so is it just supposed to show proposals that have selected excitations technique and said their sample is a crystal?

![image](https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/14293717/ce6f3986-a282-4edc-be29-2cde045e88aa)

**Comment by Cat-Lucifer** [comment]
@simonfernandes So yes, the reporting from legacy presumably takes it's info from this question:

![image](https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/108054517/7c0b4d75-86e2-4f4f-b012-060f661e530d)

Sorry, I should have said that I have created a similar question in the sample sub-template on the new system.  Q key is "alf_request".  Please can it pull through Yes or No answers from this, or just the Yes answers would be even better?

**Comment by simonfernandes** [comment]
Closed via https://github.com/isisbusapps/reporting-tool/pull/735
