### ISSUE TITLE
Update all ISIS mailing list reports

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#888]
Update *all* reports in the mailing category that are relevant to ISIS, so that they include data from the new and old software. Only below 4 reports need to be updated.

https://office.facilities.rl.ac.uk/reporting/SQLView.aspx?category=mailing-lists 

Checked queries are released in first phase and then the rest in later phase. 
- [x] CLF Community News Distribution List
- [x] CLF proposal call PI and CoI mailing list
- [x] CLF proposal call PI and CoI mailing list from date
- [x] ISIS Community News Distribution List

**Comment by Cat-Lucifer** [comment]
@bashanlam These are the two reports that the User Office need updating first:

https://office.facilities.rl.ac.uk/reporting/SQLView.aspx?category=mailing-lists&query=clf-community-news-distribution-list
https://office.facilities.rl.ac.uk/reporting/SQLView.aspx?category=mailing-lists&query=isis-community-news-distribution-list

Thanks!

**Comment by mutambaraf** [comment]
Split into issues we can do this sprint.
