### ISSUE TITLE
Update proposals by surname report

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#889]
Update the report to include both new and old proposal data.

https://office.facilities.rl.ac.uk/reporting/SQLView.aspx?category=isis-investigators&query=proposals-by-surname

**Comment by simonfernandes** [comment]
@Cat-Lucifer When did you need this one accessible by? Just trying to work around my leave as to when a release will need to be done once this is ready.

**Comment by Cat-Lucifer** [comment]
@simonfernandes I do use it a fair amount, but it's not mega urgent

**Comment by simonfernandes** [comment]
Waiting on https://github.com/isisbusapps/proposal-allocations/issues/419

**Comment by simonfernandes** [comment]
Closed via https://github.com/isisbusapps/reporting-tool/pull/741
