### ISSUE TITLE
Update ISIS proposals by RB report

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#890]
Update the report to include both new and old proposal data.

https://office.facilities.rl.ac.uk/reporting/SQLView.aspx?category=isis-proposals&query=lookup-proposal-data-by-exp-number

**Comment by simonfernandes** [comment]
If it's just as easy, make this for CLF too.

**Comment by simonfernandes** [comment]
@Cat-Lucifer This was the report I thought could be used in its place: https://office.facilities.rl.ac.uk/reporting/SQLView.aspx?category=isis-proposals&query=isis-proposals-submitted-by-round

From a quick glance it looks like there are some differences (e.g. no experiment info).

**Comment by Cat-Lucifer** [comment]
@simonfernandes I see what you mean, and I guess I could but there might be some parameters missing.  I tend to use this query when the SharePoint ProposalList has missing info for a proposal, so I can fill in absent data (not sure where this query pulls data from?).  It is more useful to retrieve specific proposal info in this way than scroll through a long list.

**Comment by simonfernandes** [comment]
@Cat-Lucifer We can now access proposals on the submissions site via a link that contains the RB, is this still necessary?

**Comment by Cat-Lucifer** [comment]
Email sent by @deepaksftc 

![image](https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/108054517/0d4fac61-97d4-4afa-8a85-f2e408c1ca28)

**Comment by Cat-Lucifer** [comment]
> Email sent by @deepaksftc
> 
> ![image](https://private-user-images.githubusercontent.com/108054517/302967457-0d4fac61-97d4-4afa-8a85-f2e408c1ca28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMDY2NTEsIm5iZiI6MTcwNzMwNjM1MSwicGF0aCI6Ii8xMDgwNTQ1MTcvMzAyOTY3NDU3LTBkNGZhYzYxLTk3ZDQtNGFmYS04YTg1LWYyZTQwOGMxY2EyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QxMTQ1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZWY0ODlhMjljYWY2YWNlYzlkYjcyMWI2NGMzMGQ5MTI3YzdkNTc5NDE2MGZkYTBjYjY0YzViMGE3YzE2YzE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P-iB5SjUA_0NZC3xgDx0w-ueXrNAfdTumG9cRLPoSqw)

@deepaksftc We need `FAP`, but the other fields can be omitted.  Yes, no problem if `Local contact` is a blank field
