### ISSUE TITLE
Update ISIS deuteration requests for scheduled experiments report

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#891]
Update the report to include both new and old proposal data.

https://office.facilities.rl.ac.uk/reporting/SQLView.aspx?category=isis-proposals&query=deuteration-requests-for-scheduled-experiments

**Comment by simonfernandes** [comment]
@Cat-Lucifer Does the PI data in this report need to be from the time of submission? It isn't currently

**Comment by Cat-Lucifer** [comment]
> @Cat-Lucifer Does the PI data in this report need to be from the time of submission? It isn't currently

@simonfernandes Yes please.

**Comment by simonfernandes** [comment]
Closed via https://github.com/isisbusapps/reporting-tool/pull/733
