### ISSUE TITLE
Update ISIS PI & Co-Is for scheduled experiments between dates report

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#896]
Update the report to include both new and old proposal data.

https://office.facilities.rl.ac.uk/reporting/SQLView.aspx?category=isis-investigators&query=pis-and-cois-for-scheduled-experiments-between-dates

**Comment by georgeflecknell** [comment]
Please can we also make sure that this report is reporting back current PI details or details at the time of submission? Ie: historical data.
