### ISSUE TITLE
Update CLF experiments between dates report

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#904]
Update the report to include both new and old proposal data.

https://office.facilities.rl.ac.uk/reporting/SQLView.aspx?category=scheduled-experiments&query=experiments-between-dates-clf-annual-report

**Comment by simonfernandes** [comment]
@mutambaraf Please could you ensure this works with HPL rounds (https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/918) while you are developing this.

**Comment by mutambaraf** [comment]
@simonfernandes this query is picking up the latest proposals because it is using `sp_proposal_list_cache` which is up-to-date.

**Comment by simonfernandes** [comment]
It doesn't get the science case from the new proposal software though, only legacy.

Also, I think we are going to have issues with queries like these when we decommission SharePoint (and the SPProposalListCache) stops. So we will eventually have to stop using the cache like this.

**Comment by mutambaraf** [comment]
@simonfernandes from the changes l made is there any additional changes we will require on this report for this issue https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/918 mentioned.

**Comment by simonfernandes** [comment]
@mutambaraf Feel free to just leave it and I will test it with the others soon 🙂
