### ISSUE TITLE
Error Log: Can not delete genericTemplate because of insufficient permissions.

### ISSUE THREAD

**Issue by bashanlam** [UserOfficeProject/user-office-project-issue-tracker#906]
Error on prod. Application Logs Monitoring Error Log: Can not delete genericTemplate because of insufficient permissions. 
{"errors":[{"message":"Can not delete genericTemplate because of insufficient permissions","locations":[{"line":2,"column":3}],"path":["deleteGenericTemplate"],"extensions":{"context":{"agent":{"id":1128265,"user_title":"Ms","firstname":"Ghazaleh","lastname":"Mazaheri Tehrani","username":"G.mazaheri-tehrani@lboro.ac.uk","preferredname":"Ghazaleh","oidcSub":"","oauthRefreshToken":"","oauthAccessToken":"","oauthIssuer":"","gender":"","nationality":1,"birthdate":"2000-01-01T00:00:00.000Z","organisation":1,"department":"Department of Materials","position":"","email":"G.mazaheri-tehrani@lboro.ac.uk","emailVerified":true,"telephone":"+441509 223387","placeholder":false,"created":"2000-01-01 00:00:00.000000+00","updated":"2000-01-01 00:00:00.000000+00","currentRole":{"id":1,"shortCode":"user","title":"User"},"externalToken":"4b545b81-c2da-43f5-bfb9-6c5fb6199beb","externalTokenValid":true,"isInternalUser":false},"genericTemplateId":8871}}}],"context":{"requestUserId":1128265,"request":{"query":"mutation deleteGenericTemplate($genericTemplateId: Int!) {\n deleteGenericTemplate(genericTemplateId: $genericTemplateId) {\n ...genericTemplate\n }\n}\n\nfragment genericTemplate on GenericTemplate {\n id\n title\n creatorId\n questionaryId\n created\n proposalPk\n questionId\n}","operationName":"deleteGenericTemplate","variables":{"genericTemplateId":8871},"http":{"method":"POST","headers":{},"search":"","body":{"query":"mutation deleteGenericTemplate($genericTemplateId: Int!) {\n deleteGenericTemplate(genericTemplateId: $genericTemplateId) {\n ...genericTemplate\n }\n}\n\nfragment genericTemplate on GenericTemplate {\n id\n title\n creatorId\n questionaryId\n created\n proposalPk\n questionId\n}","variables":{"genericTemplateId":8871},"operationName":"deleteGenericTemplate"}}}}}
"genericTemplateId":8871(Need to find generic_templates.proposl_pk.)
agent:{"id":1128265,"user_title":"Ms","firstname":"Ghazaleh","lastname":"Mazaheri Tehrani","username":"G.mazaheri-tehrani@lboro.ac.uk",…
currentRole:{"id":1,"shortCode":"user","title":"User"}

After tackling through the database , the record of generic_templates table where generic_template_id = ‘8871’ was deleted (rather than cannot delete).

**Comment by mutambaraf** [comment]
I managed to recreate this issue by creating two sub templates to a topic. Then add four answers as a user officer to a proposal. Then delete a single answer from each  sub template question .Then add back an answer to one of the sub templates  question .This will clear all answers from one of the sub template question. If you then  select save and continue the above error will appear. From then on the system is continuously  produce the above error to get out of the this the user must close the proposal or reload the browser. `As a shot term solution we can add a check in the backend before we delete then just skip the delete if the template does not exist anymore and just log a warning.`
