### ISSUE TITLE
Proposal PDFs generate with missing information 

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#907]
PDFs don't seem to contain any proposal information after the co-proposer. In the example image below, the 2nd page is completely blank, and then the 3rd and 4th page does correctly contain the user's science case.

It looks like proposals that are using a custom PDF template are still fine.

<img src="https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/14293717/8e1f2997-a724-4ffb-89b6-8bfa1b21a54c" data-canonical-src="https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/14293717/8e1f2997-a724-4ffb-89b6-8bfa1b21a54c" width="300" height="500" />

**Comment by yoganandaness** [comment]
@simonfernandes Is it for Auto PDF template?

**Comment by simonfernandes** [comment]
Hi @yoganandaness, yes this is for the default auto PDF template only.

**Comment by yoganandaness** [comment]
@simonfernandes The issue has been fixed. It is a minor code fix. A PR has been raised regarding the same, which needs approval in order to be merged. 

https://github.com/UserOfficeProject/user-office-factory/pull/259

**Comment by simonfernandes** [comment]
@yoganandaness thanks again for fixing this so quick! 😊
