### ISSUE TITLE
Give Internal Reviewer role to users

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/user-office-project-issue-tracker#910]
If we are going to use the internal reviews feature we should work out how we are going to give users these roles. It maybe the case the instrument scientist role can be used instead but that needs further investigation.

**Comment by srconway** [comment]
Confirmed these will all be STFC staff but not entirely clear whether these will all be instrument scientists. Need to decide who is responsible for assigning these 2nd reviewers (e.g. deuteration, sample env etc) - as the technical reviewer

**Comment by TCMeldrum** [comment]
This will be covered in the creation of the new basic Panel member manager: https://github.com/isisbusapps/panel-member-manager/issues/49
