### ISSUE TITLE
Update report experiments between dates per day

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#912]
Include all CLF results at once using this query:

https://office.facilities.rl.ac.uk/reporting/SQLView.aspx?category=scheduled-experiments&query=experiments-between-dates-per-day

currently it only lets you choose LSF, HPL etc. He needs this because this is the only query that shows experiments added directly to the Scheduler, as well as from the SharePoint cache.

Add additional headers from
https://office.facilities.rl.ac.uk/reporting/SQLView.aspx?category=scheduled-experiments&query=experiments-between-dates-clf-annual-report

---

> From: Facilities Business Systems & Support <[FacilitiesBusinessSystem@stfc.ac.uk](mailto:FacilitiesBusinessSystem@stfc.ac.uk)> 
> Sent: Tuesday, August 15, 2023 9:16 AM
> To: Mutambara, Farai (STFC,RAL,ISIS) <[farai.mutambara@stfc.ac.uk](mailto:farai.mutambara@stfc.ac.uk)>
> Subject: Fw: Annual data run for Energy by 14 of May 
>  
> Hi Farai,
>  
> I think you forwarded this support request to Vanessa. She didn't get back to me about it with an issue number or to tell me it was resolved.
>  
> Rob Clarke wants to be able to search all CLF results at once using this query:
> 
> https://office.facilities.rl.ac.uk/reporting/SQLView.aspx?category=scheduled-experiments&query=experiments-between-dates-per-day
> 
> currently it only lets you choose LSF, HPL etc. He needs this because this is the only query that shows experiments added directly to the Scheduler, as well as from the SharePoint cache.
>  
> Secondly, Rob needs this query to also return the additional headers that he receives currently from
> https://office.facilities.rl.ac.uk/reporting/SQLView.aspx?category=scheduled-experiments&query=experiments-between-dates-clf-annual-report
>  
> This has been open a good long while, so I think this work is quite overdue now, I'm afraid. Please could you look at it asap?
>  
> Thanks
> George

---

> From: Clarke, Rob (STFC,RAL,CLF) <[rob.clarke@stfc.ac.uk](mailto:rob.clarke@stfc.ac.uk)> 
> Sent: Tuesday, July 4, 2023 10:15 AM
> To: Facilities Business Systems & Support <[FacilitiesBusinessSystem@stfc.ac.uk](mailto:FacilitiesBusinessSystem@stfc.ac.uk)>
> Subject: FW: Annual data run for Energy by 14 of May 
>  
> Following on from Emmas request to get me access to the additional report – it seems this version of reporting can see experiments that are put into the scheduler by ourselves, whereas the other report we have been discussing (scheduled experiments) cannot….
>  
> I’m not sure this makes sense to me, but if this report has abilities that the other does not, can we customise it to provide the extra data I get from the scheduled experiments report, and enable it to search for all CLF experiments together, or, alternatively, figure out how to get the data into the other report?
>  
> Rob C.

**Comment by simonfernandes** [comment]
@mutambaraf Please could you add who this request has come from and paste the email content if there is one. We could do with working out the origin, context and priority of this.

This might be one we can pass over to the scheduler team depending on the above.

**Comment by mutambaraf** [comment]
> currently it only lets you choose LSF, HPL etc. He needs this because this is the only query that shows experiments added directly to the Scheduler, as well as from the SharePoint cache

I think it was discussed before .It came through support from Rob Clarke

**Comment by simonfernandes** [comment]
Sorry I didn't remember. Do you have context or priority for it? Where did it come from?
