### ISSUE TITLE
Update all equal opportunities reports

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#915]
Update *all** reports in the [equal opps category](https://office.facilities.rl.ac.uk/reporting/SQLView.aspx?category=equal-opps), so that they include data from the new and old software. 

*Excludes https://github.com/isisbusapps/reporting-tool/issues/719. And we may need to see which other reports in this category can be outsourced to more suitable teams.

---

#### @simonfernandes 

- [x] ISIS equal opportunity statistics for opt in status
- [x] ISIS equal opportunity statistics for gender
- [x] ISIS equal opportunity statistics for age range
- [x] ISIS equal opportunity statistics for ethnicity
- [x] ISIS equal opportunity statistics for ethnicity split by UK/International
- [x] ISIS equal opportunity statistics for disability

#### @ACLay 

- [x] CLF success rates for opted in users
- [x] CLF success rates by gender
- [x] CLF success rates by age range
- [x] CLF success rates by ethnicity
- [x] CLF success rates by disability

#### Blocked 
- ISIS proposer ethnicity by access panel (blocked by https://github.com/isisbusapps/reporting-tool/issues/767)

#### Not required

- Percentage of users who have made an equal opportunities choice
- Percentage of users who have opted to provide equal opportunities data
- Number of equal opportunity choices at latest user logins

**Comment by simonfernandes** [comment]
@mutambaraf Do you mind posting the queries you did for this via support recently? It will save someone repeating all of that work again

**Comment by mutambaraf** [comment]
### EDI data for the last ISIS rounds
```
(SELECT 
       CAST(pg_prop.proposal_id AS INT) AS "RB Number",
       p.user_number AS "User Number",
       'Principal Investigator' as "Role",
       CASE
         WHEN g.name IS null THEN 'No Record Held'
         WHEN g.name IS NOT null THEN g.name
       END "Gender",
       CASE m.opt_in
         WHEN 1 THEN 'Opted In'
         WHEN 2 THEN 'Opted Out'
         ELSE 'Neither Yet'
       END "Opted Status",
       CASE
         WHEN e.name IS NULL THEN 'No Record Held'
         WHEN e.name IS NOT NULL THEN e.name
       END "Ethnicity",
       CASE 
              WHEN d.name IS NULL THEN 'No Record Held'
              WHEN d.name IS NOT NULL THEN d.name
        END "Disability"

 FROM duo.public.proposals pg_prop

       JOIN duo.public.call pg_call 
       ON pg_call.call_id = pg_prop.call_id

       JOIN isisuserdb.isisuserdb.person p
            ON CAST(pg_prop.proposer_id AS VARCHAR) = p.user_number

       JOIN isisuserdb.isisuserdb.monitor m 
       ON p.monitor_id = m.id
                 
       LEFT JOIN isisuserdb.isisuserdb.gender g
       ON m.gender_id = g.id

       LEFT JOIN isisuserdb.isisuserdb.ethnicity e
       ON m.ethnicity_id = e.id

       LEFT JOIN isisuserdb.isisuserdb.disability d
       ON m.disability_id = d.id

 WHERE (pg_prop.submitted = true) 
   AND ( pg_call.call_short_code = '<round short code>')
)
ORDER BY "RB number" ASC;
```

**Comment by simonfernandes** [comment]
Sprint planning notes:

- Update all the ISIS ones first, excluding the age range one
- Rob Clarke will want CLF ones by end of March
- Might need to clarify how monitor ID works - has changed at some point in the ways we've asked for it and recorded it and some users have blank or missing IDs. Although fine to exclude users who don't have a monitor ID and just use latest monitor data.

**Comment by simonfernandes** [comment]
All reports complete, except one report which is covered by https://github.com/isisbusapps/reporting-tool/issues/767 and https://github.com/isisbusapps/reporting-tool/issues/782
