### ISSUE TITLE
Update ISIS privacy policy

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#916]
We need to update the privacy policy that we link to on the ISIS site so that it aligns with what we tell users in the proposal questionnaire.

> From: Gozzard, Emma (STFC,RAL,ISIS) <emma.gozzard@stfc.ac.uk> 
> Sent: Friday, August 25, 2023 8:37 AM
> To: Fernandes, Simon (STFC,RAL,ISIS) <simon.fernandes@stfc.ac.uk>
> Cc: Baust, Rachel (STFC,RAL,ISIS) <rachel.baust@stfc.ac.uk>
> Subject: RE: Proposal data usage disclaimer for users' organisation
> 
> Hi Simon,
> 
> Yes, they do need to be aligned.  Reading the privacy notice, I agree it’s quite ambiguous in places.  I’m happy for you to amend, but also happy if you want me to check anything.
> 
> Thanks,
> Emma
> 
> P.S.  Rachel – hope you are well! 🙂
> 
> From: Fernandes, Simon (STFC,RAL,ISIS) <simon.fernandes@stfc.ac.uk> 
> Sent: Thursday, August 24, 2023 4:53 PM
> To: Gozzard, Emma (STFC,RAL,ISIS) <emma.gozzard@stfc.ac.uk>
> Cc: Baust, Rachel (STFC,RAL,ISIS) <rachel.baust@stfc.ac.uk>
> Subject: Proposal data usage disclaimer for users' organisation
> 
> Hi Emma,
> 
> I’ve been talking to Rachel from the Mantid team (copied in), and they have a requirement from Reflectometry scientists to start adding in users’ affiliation/organisation to the reduced data files which users can save out. We would need to ensure that we make users aware that this information could be made public.
> 
> Our privacy page that we link to (https://www.isis.stfc.ac.uk/Pages/Privacy.aspx) doesn’t mention anything about this, however the below text found in the ISIS Direct and Rapid questionnaires does - do they need to be aligned?
> 
> Many thanks,
> Simon
> 
> The questions asked for submission will be used for assessment of the proposal by the peer review panel, technical assessment and statistical purposes.  Please note that responses to the following questions will be made publicly viewable:
> 
> •	Title
> •	Abstract
> •	PI and Co-I names and institutions
> •	Technique and instrument applied for, and no. days applied for
> •	Technique and instrument allocated, and no. days allocated.

**Comment by Cat-Lucifer** [comment]
All done.

**Comment by simonfernandes** [comment]
@Cat-Lucifer In a couple of places, it says the page was last updated on 13 Feb 2019 - do we need to update that?

**Comment by Cat-Lucifer** [comment]
@simonfernandes Oops, sorry.  Dates now changed.
