### ISSUE TITLE
Fix and update ISIS sample tool report

### ISSUE THREAD

**Issue by georgeflecknell** [UserOfficeProject/user-office-project-issue-tracker#917]
The following query never returns results:

https://office.facilities.rl.ac.uk/reporting/SQLView.aspx?category=samples&query=isis-samples-search-tool

An error is caused:

This query has errors
Query execution error:Invalid parameter binding Parameter name: search_terms

It appears that an entire input is missing for the search terms

![Image](https://user-images.githubusercontent.com/75302934/266019616-981f1eae-531a-4b8a-92fd-0129b60d4ed7.png)

The problem can be replicated using the parameters in the image above. The problem was reported by the instrument scientist Peter Baker. This query appears to have never been edited however scientists do believe they have used it successfully before.

This functionality can not be provided by the proposal system as the Instrument Scientist question search does not allow compound entry or search operands. It also doesnt show legacy results.

This query fix is required asap as it is the sole way of attaining samples information.

**Comment by srconway** [comment]
@simonfernandes Could you let Adrian know when this one is released. I've told him it's being worked on but not given him a timescale.

**Comment by simonfernandes** [comment]
@srconway Will do.
