### ISSUE TITLE
Test reporting against HPL questionnaires

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#918]
We need to check that data is returned by the various CLF reports for these two HPL calls on prod:

- [ ] **HPL TEST-DONT SUMBIT** (uses HPL Trial Questionnaire)
- [x] **HPL VulcanSD 2022_1** (uses HPL Vulcan Shutdown questionnaire based off the HPL trial one)

Doing this will allow us to check that the original HPL questionnaire was created with the correct keys and can be reported against.

**Comment by simonfernandes** [comment]
Probably needs to wait for https://github.com/isisbusapps/proposal-allocations/issues/380 (depending on query implementation)

**Comment by Cat-Lucifer** [comment]
@simonfernandes I have submitted a test proposal 22810002.  I used "HPL_DO NOT SUBMIT" as the short code, so hopefully it works 🤞

The other submissions (0000 and 0001) might work now too, depending on if the system can retroactively pull the data across.

**Comment by simonfernandes** [comment]
Thanks @Cat-Lucifer, it looks like there was a problem getting it into Allocations so I've let them know about it now.

**Comment by Cat-Lucifer** [comment]
> Thanks @Cat-Lucifer, it looks like there was a problem getting it into Allocations so I've let them know about it now.

@simonfernandes Thanks for letting me know.  Please can you keep me informed.

**Comment by simonfernandes** [comment]
> > Thanks @Cat-Lucifer, it looks like there was a problem getting it into Allocations so I've let them know about it now.
> 
> @simonfernandes Thanks for letting me know. Please can you keep me informed.

A restart was required, and the short code apparently needs to contain either `20XX_X` or `Test Round` (case sensitive). They're going to get in touch with you to coordinate another test today.

**Comment by Cat-Lucifer** [comment]
@simonfernandes I did another test submission for the Vulcan shutdown (22810003), and Tom says it has been pulled through into allocations - yay!  So, you are free to do any testing you need to.

I will do a similar test for the full HPL facility call once the questionnaire has been finalised.

**Comment by simonfernandes** [comment]
@Cat-Lucifer All of the reporting looks fine with the shutdown round, with the exception of the weeks requested not showing (email sent regarding this)

**Comment by Cat-Lucifer** [comment]
@simonfernandes HPL questionnaire is confirmed. I'll open a dummy call once allocations have done what they need to for you to test reporting.

**Comment by Cat-Lucifer** [comment]
@simonfernandes R&A have done what they need to do (https://github.com/isisbusapps/ISISBusApps/issues/924#issuecomment-1821076421).  I will do a test call on Friday.

**Comment by simonfernandes** [comment]
@Cat-Lucifer Thanks, I will need to wait for your test proposals to come in before testing

**Comment by Cat-Lucifer** [comment]
~~@simonfernandes I have now submitted two proposals via a HPL test round:  990 and 991.~~

**Comment by Cat-Lucifer** [comment]
~~@simonfernandes Ignore my comment above.  New call and proposal submissions: 9991 and 9992.~~

**Comment by Cat-Lucifer** [comment]
@simonfernandes I have submitted proposals 9902 and 9903 as part of test call short code `HPL Test Round`.

Fingers crossed!

**Comment by simonfernandes** [comment]
@Cat-Lucifer Please could I or you create an unsubmitted proposal in the test call? Needs to be a new one and not a status change. That's the last bit of testing I need to do. I've done manual checks on each of the updated CLF reports and it otherwise looks fine

**Comment by Cat-Lucifer** [comment]
@simonfernandes I did do this during the test call just in case!  It is number 639611

**Comment by simonfernandes** [comment]
@Cat-Lucifer Ah sorry Emma, I should have checked more carefully! That's perfect.

All looks fine then so I'll close 😊
