### ISSUE TITLE
Improve proposal search by waiting for user to finish typing search term

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#920]
In the proposal search box, it will execute the search immediately after typing each letter. It would be more efficient and user friendly if there was a delay so that the user can finish typing what they wish to search for.

![image](https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/14293717/6db52a14-ac01-4fda-8ec5-4f45363609f9)

**Comment by Cat-Lucifer** [comment]
@simonfernandes I don't think this is a priority.  Most search engines work in this way.  Unless we get lots of people complaining then I wouldn't want any time spent on this.  Probably one for backlog.

**Comment by simonfernandes** [comment]
@Cat-Lucifer I was planning to bring these up on Wednesday but let's skip this one then and I'll put it in the backlog. I agree with what you said - it's still perfectly usable if not optimum

**Comment by srconway** [comment]
I agree, it's a nice-to-have. It might be a good 'friendly' task for a new starter though - I'd imagine it's "just" a case of putting in a brief wait after each character and only submitting the search request if nothing is typed for say 0.5secs.

Also when we do fix this one and get it to production can we let Adrian know

**Comment by mutambaraf** [comment]
@YufanKambang will pick this up as its not urgent
