### ISSUE TITLE
Multiple file download notification on chrome when downloading attachments

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#921]
### What is the problem and why is it a problem
When you select multiple attachment questions to down on proposal a notification pops up of attempting to downloading multiple files. This is on shown on Chrome browser and not on edge. To allow the download the user will just select allow and the attachments will be downloaded successfully. 

### Steps to reproduce (if it's a bug).
1. Open proposal system in Chrome browser.
2. While on user officer table select proposals with at least two file upload answers.
3. Select download attachments.
4. Select at least two questions.
5. Select download.
6. If you haven't allowed multiple question download a pop up as bellow will appear.

![image](https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/71100224/4b635824-03a2-4179-827c-3bfa68abc4bf)

**Comment by mutambaraf** [comment]
This maybe because we are not properly setting headers when sending the download request.

**Comment by simonfernandes** [comment]
@mutambaraf 

Did this come in through support and if so from who? Emma needs this info to determine how to prioritise this. 

Also both Emma and I are struggling to replicate this, is it still broken for you on prod? I'm selecting two proposals from 2023_2 and downloading attachments from the file upload question.

**Comment by mutambaraf** [comment]
> @mutambaraf
> 
> Did this come in through support and if so from who? Emma needs this info to determine how to prioritise this.
> 
> Also both Emma and I are struggling to replicate this, is it still broken for you on prod? I'm selecting two proposals from 2023_2 and downloading attachments from the file upload question.

I also tried everything but not able to replicate it .I saw it when l was testing the feature in prod .We can close or put it in backlog till users start to experience it l guess.

**Comment by simonfernandes** [comment]
Thanks for testing, I think it'll be better to close it for now and we can always recreate/reopen if it ever comes back up 🙂 @Cat-Lucifer
