### ISSUE TITLE
Create HPL Gemini call and workflow

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#922]
We need to create a call with a corresponding workflow for the skinny Vulcan HPL round.

**Comment by Cat-Lucifer** [comment]
@simonfernandes Skinny Vulcan workflow is done, but there isn't one for HPL.  The HPL one will be the same as for LSF, so I can do if you want?

**Comment by Cat-Lucifer** [comment]
@simonfernandes In fact, I have just created the HPL workflow.  We can test a call when everything downstream is sorted?

**Comment by simonfernandes** [comment]
@Cat-Lucifer Thanks, that sounds good

**Comment by Cat-Lucifer** [comment]
@simonfernandes HPL questionnaire is confirmed.  I'll open a dummy call once allocations have done what they need to.

**Comment by simonfernandes** [comment]
@Cat-Lucifer After we have some dummy proposals submitted in the dummy call, are you able to verify the HPL PDF template? I can arrange to check it with HPL otherwise.

**Comment by Cat-Lucifer** [comment]
@simonfernandes They are happy with the pdf template, with the exception of the two new-ish issues: #956 and #957.  I said in #957 I'd submit a proposal with the limited three page science case and one with more than three pages.

ETA: These issues do not block HPL roll out

**Comment by simonfernandes** [comment]
@Cat-Lucifer Perfect, thanks!

**Comment by Cat-Lucifer** [comment]
~~@simonfernandes I have now submitted two proposals via a HPL test round:  990 and 991.~~

**Comment by Cat-Lucifer** [comment]
@simonfernandes Ignore my comment above.  New call and proposal submissions: 9991 and 9992.

**Comment by Cat-Lucifer** [comment]
@simonfernandes I have submitted proposals 9902 and 9903 as part of test call short code `HPL Test Round`.

Fingers crossed!
