### ISSUE TITLE
Proposal Template Question Can Throw Error

### ISSUE THREAD

**Issue by Scott-James-Hurley** [UserOfficeProject/user-office-project-issue-tracker#924]
### What is the problem and why is it a problem

An error is shown to the user if they enter too many characters in a proposal template question.

The number of characters a user can enter in the field should be limited in the frontend.

### Steps to reproduce

When creating or editing a proposal template question, enter more than 500 characters into the `Template basic information` field.

**Comment by mutambaraf** [comment]
Where was this discovered.

**Comment by Scott-James-Hurley** [comment]
I found it whilst investigating another issue.
