### ISSUE TITLE
Fix event logs on proposals

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#925]
We need to fix logs on proposals which are returning an error because we are not resolving the user id 0 which is being user by the system to make workflow changes to proposals. We need to either update the getUser query or eventLogResolver to return the details of the system services account.

### What is the problem and why is it a problem
At the moment user officers and instrument scientists will not be able to see status changes on any closed proposal rounds. 

### Steps to reproduce (if it's a bug).

- Select any proposal from ISIS_Direct_2023 round.
- Select logs

**Comment by mutambaraf** [comment]
I propose we bring in the service account information as a config which will make it easier to manage or update when needed.

**Comment by simonfernandes** [comment]
@mutambaraf Do you know if this has been resolved? I thought it had

**Comment by mutambaraf** [comment]
> @mutambaraf Do you know if this has been resolved? I thought it had

Will have a look because it might have been resolved.

**Comment by mutambaraf** [comment]
This now fixed and closing it now.
