### ISSUE TITLE
isis-proposals-submitted-by-round returns query error for >165 results

### ISSUE THREAD

**Issue by georgeflecknell** [UserOfficeProject/user-office-project-issue-tracker#930]
Running this query gives results up to 2410164 but no more. Running with individual instrument names appears to work okay but is not useful.

The 2410165 proposal is a "Direct Access", "Sans2D" proposal. If you use "Sans2D" as the instrument parameter, this experiment  proposal still doesn't appear in results. So it looks like a possible problem with this proposal or it's returned values. 

"SANS2D" is listed in the instrument column for query results but appears as Sans2D in the proposal. This might not be a problem though as (for example)  2410156 returns okay in a query with "Sans2D" as instrument:

![image](https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/75302934/6748a952-7c82-4ce8-a119-a0e82d162838)

Could this be either a bad value in the 2410165 proposal or some functional limit on the size of the returned results?

**Comment by simonfernandes** [comment]
@georgeflecknell @Cat-Lucifer This revealed the root problem of allocations not syncing past proposal 164, which this report relies on. The other team are aware and looking into it now

**Comment by simonfernandes** [comment]
Resolved by R&A fixing Allocations
