### ISSUE TITLE
Investigate ISIS Direct 24-1 performance issues

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#933]
We should do a post mortem of deadline day to conclude exactly what went wrong and if there's anything we can do to prevent this happening again.

**Comment by georgeflecknell** [comment]
2024_1

![image](https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/75302934/17a8f12d-34fd-4af3-9e2b-d5a72ffa08f0)

More detailed view of peaks on deadline day:
![image](https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/75302934/9925cf5d-63e7-4564-8d8f-d33441743920)



2023_1
![image](https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/75302934/7072c0d6-46c9-459f-b953-0cd20f227aa2)

**Comment by simonfernandes** [comment]
Outcomes from meeting:

- https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/938
  - What was the problem with RabbitMQ and the fix for it?
  - What was the actual underlying issue with cloud and what fixes were applied?
- Compare peak usage of this round vs previous busy round (23-1?)
  - Look at volume of logs
  - Look at event logs in database
  - Also compare to a smaller round (e.g. LSF)
- Look for reoccurring errors
  - See whether logserver errors that occurrred this time were present in previous rounds
  - See if there are any UOWS metrics we can analyse
- Investigate cluster
  - See how application scaling works
  - See if there are any metrics available
  - Look at possible effects of CAPI migration
-  https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/960
   - Get metrics from when the system is not under load (e.g. time taken to submit a proposal) to use as a comparison for when it is
   - Possibly re-run Cosimo's performance benchmark: https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/18#issuecomment-1240685423 and https://ci.devs.facilities.rl.ac.uk/view/ProposalLoadTest/
     - Consider finding and using how long people actually take to submit a proposal from creation through to submission (and use average size file upload, no. co-investigators etc.) for more realistic results
   - Get metrics from when the system is not under load (e.g. time taken to submit a proposal) to use as a comparison for when it is
   - Possibly re-run Cosimo's performance benchmark: https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/18#issuecomment-1240685423 and https://ci.devs.facilities.rl.ac.uk/view/ProposalLoadTest/
     - Consider finding and using how long people actually take to submit a proposal from creation through to submission (and use average size file upload, no. co-investigators etc.) for more realistic results

**Comment by simonfernandes** [comment]
Sprint planning notes 15/11/23:

- #938 was probably cloud but inconclusive
- After findings from #938, load test system and create metrics: https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/960
- Hopefully won't be a problem for HPL due to low numbers
