### ISSUE TITLE
Clamscan was unable to virus scan file error: For file greater than 2MB.

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#934]
Looks like Clamscan is not able to scan bigger files of 2MB.
### What is the problem and why is it a problem
`Log message: [2023-10-17T22:53:33.993Z] ERROR - Clamscan was unable to virus scan file 
 {"response":{"file":null,"isInfected":null,"viruses":[],"resultString":"UNKNOWN COMMAND","timeout":false},"errorContext":{"question":{"question":{"categoryId":1,"id":"file_upload_1634228670670","naturalKey":"Science_Case_File_Upload","dataType":"FILE_UPLOAD","question":"Upload document","config":{"small_label":"Only PDFs up to 2MB are accepted.","required":true,"tooltip":"","file_type":[".pdf"],"pdf_page_limit":0,"max_files":1}},"topicId":126,"sortOrder":0,"config":{"small_label":"Only PDFs up to 2MB are accepted.","required":true,"tooltip":"","file_type":[".pdf"],"pdf_page_limit":2,"max_files":1},"dependencies":[],"dependenciesOperator":"AND"},"answer":[{"id":"41f46631-fd98-4e4b-b22b-45824eae9862"}],"fileId":"41f46631-fd98-4e4b-b22b-45824eae9862"}}`

**Comment by mutambaraf** [comment]
We might need to limit the file size uploaded by users if Clamscan is not able to process them.

**Comment by simonfernandes** [comment]
Sprint planning notes: 

Configure ClamScan to accept a bigger limit, as users' files will reasonably be over 2MB. 10MB would be a reasonable limit.

**Comment by ACLay** [comment]
This got hit again the other day:

```
Log message: [2024-04-17T13:10:53.357Z] ERROR - Unable to virus scan file 
 {"reason":{"data":{"err":{"errno":-2,"code":"ENOENT","syscall":"access","path":"downloads/1c9deae7-3924-4ec8-ae21-66e98e18e6e4"},"file":"downloads/1c9deae7-3924-4ec8-ae21-66e98e18e6e4"},"date":"2024-04-17T13:10:53.357Z"},"errorContext":{"question":{"question":{"categoryId":1,"id":"file_upload_1634228670670","naturalKey":"Science_Case_File_Upload","dataType":"FILE_UPLOAD","question":"Upload document","config":{"small_label":"Only PDFs up to 2MB are accepted.","required":true,"tooltip":"","file_type":[".pdf"],"pdf_page_limit":0,"max_files":1,"omitFromPdf":false}},"topicId":126,"sortOrder":0,"config":{"small_label":"Only PDFs up to 2MB are accepted.","required":true,"tooltip":"","file_type":[".pdf"],"pdf_page_limit":2,"max_files":1,"omitFromPdf":false},"dependencies":[],"dependenciesOperator":"AND"},"answer":[{"id":"1c9deae7-3924-4ec8-ae21-66e98e18e6e4"}],"fileId":"1c9deae7-3924-4ec8-ae21-66e98e18e6e4"}}
```

**Comment by simonfernandes** [comment]
I think this is to do with the user multiple clicking the save button (which they shouldn't be able to do), though I've not been able to replicate this fully. Each time this happens, it looks like the file is actually scanned multiple times and passes the first time but fails on subsequent scans. It doesn't seem to cause users any issues and looks to have happened on only 3 occasions in the past year. I think with the save button fix we can monitor this further and reopen if it comes up again.
