### ISSUE TITLE
Change the create date for imported legacy proposals to their actual create date rather than import date

### ISSUE THREAD

**Issue by georgeflecknell** [UserOfficeProject/user-office-project-issue-tracker#946]
### What is the problem and why is it a problem

This issue affects all users of postgres database data, anyone writing reports with this data and anyone working on the data in the database.

Currently the create date 26-08-22 applies to ALL imported proposals. This is legacy data pulled from the Oracle database on this date. This is not only incorrect, but also prevents reporting using the postgres server alone as a single source of truth.

Affects, reporting tool reports, future report development, custom data exports at User Office request.

Issue not requested but generated as part of continuous improvements. Suggested solution is to copy the SUBMITTED_DATE from legacy data for all affected proposals.

**Comment by simonfernandes** [comment]
Backlog pruning notes:

Probably more of a developer issue that affects writing custom queries. There are ways around this (querying Allocations instead) but it would still be nice to fix this to avoid confusion in future.

**Comment by simonfernandes** [comment]
@Cat-Lucifer @georgeflecknell 

I misunderstood @deepaksftc just now in sprint planning and I think this might be solved. 

We have a [duplicate issue](https://github.com/UserOfficeProject/issue-tracker/issues/955), which is closed with a change from Deepak. In it, he changed the created date in the new submissions system to reflect the submitted date in legacy. In a reporting context, I'm not sure that we ever queried this created date.

We don't actually plainly store the submitted date in the new system. We have to look up the event logs for when the proposal was submitted. For legacy imported proposals this would be blank, but the way that we typically write reports is either to a) query both databases within the same report (i.e. get the submitted date two different ways), or b) more commonly now just get it from Allocations.

**Comment by simonfernandes** [comment]
Closing as duplicate
