### ISSUE TITLE
Checkbox options following drop-down are hard to click

### ISSUE THREAD

**Issue by srconway** [UserOfficeProject/user-office-project-issue-tracker#947]
### What is the problem and why is it a problem
Apparently in the last round certain Yes/No tick boxes were very hard to click with only a very small and specific area marked as clickable, particularly in section 4 of the questionnaire.

**Comment by simonfernandes** [comment]
Sprint planning notes:

Question was science programmes drop-down

**Comment by georgeflecknell** [comment]
![image](https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/75302934/e043066f-cbbc-408d-a582-f0ff796766e0)

This is the section for which this was reported as a problem by the user.

**Comment by simonfernandes** [comment]
Backlog pruning notes:

Only affected a single user so we don't need to worry about this
