### ISSUE TITLE
Publications not listed for selection in proposal submission

### ISSUE THREAD

**Issue by srconway** [UserOfficeProject/user-office-project-issue-tracker#948]
### What is the problem and why is it a problem
Publications couldn't be added, possibly due to having a high number of proposals, but he had to find the proposal title to search for then from that the publications could be selected. but had to specifically OK each one after an error message (Aidy)

**Comment by simonfernandes** [comment]
Sprint planning notes: It’s fine to just allow users to copy and go without re-opening with publications and grants.

Originated from 24-1 feedback document: 

> When copying over previous publications, in that sub-template, it won’t just save them and let you move on.  You have to open and close each one before you can save and continue.

**Comment by simonfernandes** [comment]
Backlog pruning notes:

Let's see if this is still an issue.

Edit: 

It's still necessary to open/close generic templates in order to proceed. Adding to to next sprint to discuss.

**Comment by simonfernandes** [comment]
Sprint planning notes:

Needs investigation as to why we ask users to re-open and confirm. If it's to check that everything is filled in, could the check be more intelligent?

Workaround if not done in time is to add an embellishment to explain the need to re-open and confirm.
