### ISSUE TITLE
We need to fix ApolloServerPluginUsageReporting warning message.

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#949]
### What is the problem and why is it a problem
We to make necessary configuration  changes  for Apollo Server because it is showing this warning log.
`You have installed `ApolloServerPluginUsageReporting` but this server appears to be a subgraph. Typically usage reports are sent to Apollo by your Router or Gateway, not directly from your subgraph. If this was unintentional, remove `ApolloServerPluginUsageReporting` from your server's `plugins` array.
Apollo usage reporting starting! See your graph at https://studio.apollographql.com/graph/Proposals-4xf9j@dev/
[2023-11-01T12:07:02.540Z] INFO - Running a GraphQL API server at localhost:4000/graphql`

**Comment by simonfernandes** [comment]
@srconway to add more people to apollo to investigate.

**Comment by simonfernandes** [comment]
@TCMeldrum and @ACLay may have more insight

**Comment by mutambaraf** [comment]
This is a warning caused by https://github.com/apollographql/apollo-server/blob/621167b8f0453199bd97b3a59e60a2bfa5b7ec0d/packages/server/src/plugin/usageReporting/plugin.ts#L128 and looks like a config issue we can ignore. Looks like there is no flag to silence it is available.
