### ISSUE TITLE
Add support for additional file types to show in appendix of final proposal PDF

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#952]
We only seem to attach PDF files to the final proposal PDF output. We sometimes allow files of different types in attachment questions (e.g. `.doc`, `.docx`) and would like those to be attached too.

---

PDF attachment:

<img src="https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/14293717/f41225c2-c174-4558-a250-bed5698abdc9" width="300"/>

.docx attachment:

<img src="https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/14293717/8b049d28-e686-4885-8c98-0d9c3817a85a" width="300"/>

---

> From: Gozzard, Emma (STFC,RAL,ISIS) <emma.gozzard@stfc.ac.uk> 
> Sent: Monday, November 6, 2023 5:02 PM
> To: Fernandes, Simon (STFC,RAL,ISIS) <simon.fernandes@stfc.ac.uk>
> Subject: FW: Query re submitted proposal
> 
> Hi Simon,
> 
> Please see below and attached.  This is for the Vulcan shutdown template, but the HPL template is also based on these constraints.
> 
> In George’s absence, please can you raise an issue and look into this?
> 
> Thanks,
> Emma
> 
> From: Gozzard, Emma (STFC,RAL,ISIS) 
> Sent: Monday, November 6, 2023 5:00 PM
> To: Carroll, David (STFC,RAL,CLF) <[david.carroll@stfc.ac.uk](mailto:david.carroll@stfc.ac.uk)>
> Cc: Facilities Business Systems & Support <[FacilitiesBusinessSystem@stfc.ac.uk](mailto:FacilitiesBusinessSystem@stfc.ac.uk)>
> Subject: RE: Query re submitted proposal
> 
> Hi David,
> 
> Yes, I specifically set the template up to accept .doc and .docx files – see below.  This is also true for the tech spec doc.  I’ll get the relevant team to take a look at this.
> 
> In the interests of time, I will merge the two docs tomorrow when I’m collating everything.  I will send the revised version to the PI.
> 
> Thanks,
> Emma
> 
> 
>  
> 
> From: Carroll, David (STFC,RAL,CLF) <[david.carroll@stfc.ac.uk](mailto:david.carroll@stfc.ac.uk)> 
> Sent: Monday, November 6, 2023 4:26 PM
> To: Gozzard, Emma (STFC,RAL,ISIS) <[emma.gozzard@stfc.ac.uk](mailto:emma.gozzard@stfc.ac.uk)>; Facilities Business Systems & Support <[FacilitiesBusinessSystem@stfc.ac.uk](mailto:FacilitiesBusinessSystem@stfc.ac.uk)>
> Subject: FW: Query re submitted proposal
> 
> Hi Emma and Business IT team,
> 
> John Pasley has contacted me as he has submitted a CLF experimental support request to the current CLF call but he has noticed the resultant output pdf is not including his 1 page summary that he uploaded as a docx file. He has sent me both the docx file and output pdf which I have attached.
> 
> My understanding was that the system would combine uploaded files that were docx and pdf into the output pdf?  Do you know what could be causing the issue?
> 
> Best regards,
> 
> David

**Comment by simonfernandes** [comment]
Sprint planning notes:

@Cat-Lucifer Could this be restricted to PDF file type?

**Comment by bashanlam** [comment]
@Cat-Lucifer any thought on pdf file type restriction?

**Comment by Cat-Lucifer** [comment]
@bashanlam The upload in the proposal questionnaire is currently restricted to pdf only

**Comment by simonfernandes** [comment]
Sprint planning notes:

Closing for now as not an issue in latest round, re-open if it comes up again
