### ISSUE TITLE
Migrate Old STFC proposal to new instrument picker question

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/user-office-project-issue-tracker#953]
When we switch over to using the new instrument picker question we will need to migrate old proposals to use the same questions for reporting purposes. This will involve running some DB scripts to add entries to the Answers table.

**Comment by RasmiaKulan** [comment]
Blocked by https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/954

**Comment by TCMeldrum** [comment]
```
Insert into answers(questionary_id, question_id, answer)
SELECT questionary_id, '<instrument_picker_question_id>', json_build_object('value', i.instrument_id) from answers  
	join instruments i on answer -> 'value' ? i.name
	where question_id = '<isis_instrument_question_id>'
```
SQL to update old answers with the new question

**Comment by TCMeldrum** [comment]
This will not assign the instrument to the proposal idk if we want that for the legacy proposals.

**Comment by Bhaswati1148** [comment]
The insert script has been executed successfully in production database.

**Comment by ACLay** [comment]
We ran this today to link to the instrument object as well as having the instrument picker answers

```sql
Insert into instrument_has_proposals (instrument_id, proposal_pk, submitted) 
    SELECT CAST(first_value AS integer), proposal_pk, FALSE from proposal_answers where question_natural_key = 'isis_instrument_picker' and first_value is not null
    on conflict do nothing;
```

**Comment by ACLay** [comment]
I've re-run the migration scripts after updating the dutch templates. Think that should be all of them now.
