### ISSUE TITLE
Change the create date for imported legacy proposals to their actual create date rather than import date

### ISSUE THREAD

**Issue by georgeflecknell** [UserOfficeProject/user-office-project-issue-tracker#955]
What is the problem and why is it a problem:
This issue affects all users of postgres database data, anyone writing reports with this data and anyone working on the data in the database.

Currently the create date 26-08-22 applies to ALL imported proposals. This is legacy data pulled from the Oracle database on this date. This is not only incorrect, but also prevents reporting using the postgres server alone as a single source of truth.

Affects, reporting tool reports, future report development, custom data exports at User Office request.

Issue not requested but generated as part of continuous improvements. Suggested solution is to copy the SUBMITTED_DATE from legacy data for all affected proposals.

**Comment by simonfernandes** [comment]
Sprint planning notes 15/11/23

- It's the legacy import script that needs to be updated
- Update date on previously imported proposals

**Comment by simonfernandes** [comment]
Sprint planning notes 12/12/23

- For existing imports, we could just make a new SQL script to make the change
- Look at how much work it would be to update the import script - we could always run the SQL script after importing any future legacy proposals as a simpler solution

**Comment by deepaksftc** [comment]
Hi @simonfernandes, @mutambaraf, the migration script is changed to consider the actual submitted date as created date during import. Its done as part of PRs,
https://github.com/UserOfficeProject/user-office-core/pull/470
https://github.com/isisbusapps/internal-scripts/pull/101

For correcting the created dates of already imported proposals in new system, I have tested and documented the steps. Please find the attachment. I have tried different approaches and could not find any way to do it with a single query. Trino not allowing updates with non constant values is one of the main reason. Please review the steps and suggest if this approach would be fine. 
[Proposal-migration data correction steps.txt](https://github.com/UserOfficeProject/user-office-project-issue-tracker/files/13940394/Proposal-migration.data.correction.steps.txt)

**Comment by simonfernandes** [comment]
Looks good to me 👍

**Comment by simonfernandes** [comment]
Small change necessary for step 2:

SELECT reference_number AS proposal_id,
submitted_date AS created_at
FROM proposal
**WHERE deleted IS NULL**
    AND reference_number IN ('1768005',
'1768001',
'1768002',
'1768003',
'1768004')

**Comment by deepaksftc** [comment]
> Small change necessary for step 2:
> 
> SELECT reference_number AS proposal_id, submitted_date AS created_at FROM proposal **WHERE deleted IS NULL** AND reference_number IN ('1768005', '1768001', '1768002', '1768003', '1768004')

Sure, updated the query.
[Proposal-migration data correction steps.txt](https://github.com/UserOfficeProject/user-office-project-issue-tracker/files/13949860/Proposal-migration.data.correction.steps.txt)

The final updated scripts:
[Proposal-migration data correction steps.txt](https://github.com/UserOfficeProject/user-office-project-issue-tracker/files/13976611/Proposal-migration.data.correction.steps.txt)
