### ISSUE TITLE
Proposal PDF is extending over 4 or more pages due to creation quirks, fonts not supported in Adobe

### ISSUE THREAD

**Issue by georgeflecknell** [UserOfficeProject/user-office-project-issue-tracker#959]
- Who does this affect?
 R&A developers creating the FAP Booklets, users of proposal PDFs, User Office trying to make the booklets useable
 - What needs to change?
Proposal PDF creation needs to be constrained to fewer pages
Proposal PDFs need to use a font that is support in Adobe as most of the time, post creation editing is required. 
 - What events does this affect?
 FAP booklets and therefore FAP review, Scoring Portal population
 - Why does it need to change?
 It is making booklet creation impossible and creates a LOT of work for developers and the User Office to make the booklets useable
 - Who requested it and when?
 Emma Gozzard 15/11/2023

### Steps to reproduce (if it's a bug).

Generate the FAP booklets.

More:
While I expected some of the proposals to go over four pages when there are lots of Co-Is, grants, publications, long abstract, etc., I did not expect a lot of the proposals to go over four pages just because the proposal pdf was not created properly.  Please see [FAP8 book](file://isis.cclrc.ac.uk/Shares/ULS/FAPs_ISIS/FAP-Books-All/24-1/FAP8_Merged.pdf) for examples: p115-117, p139-142, p161-162.  These proposals would have fit on four pages had the pdf creation worked properly.  I don’t why the ISIS Direct pdf template is doing this for some and not others.  It also doesn’t help that Adobe does not recognise or support the font used for proposal pdf creation, which makes for some very interesting editing.

This issue needs sorting by the next ISIS call opening (1 March), please, but preferably much earlier, so it can be fully tested.

Associated images:
![image](https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/75302934/df602a1e-174e-4300-a5a0-22abb31a1ae9)
[2410381.pdf](https://github.com/UserOfficeProject/user-office-project-issue-tracker/files/13363200/2410381.pdf)

Additional:
Looking at proposal 2410381 the PDF appears to be very badly formatted. This proposal has a submitted compound diagram and this seems to be breaking PDF creation:

![image](https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/75302934/f8bb8fa1-8fe9-47cf-9c2a-b436525b6c58)
I have attached this image file. It's a png and probably isn't handled correctly.
![cal stea](https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/75302934/bef0f5f6-d93c-4a7a-9d33-7c5526f8b2ca)

**Comment by georgeflecknell** [comment]
Isis deuteration sub template is he one that borked proposal 2410381

![image](https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/75302934/b910b111-adc8-43f8-bb09-b969adf9a3a5)

It appears to just have an upload "image" specification with no controls on size/format or anything else.

**Comment by simonfernandes** [comment]
Sprint planning notes 15/11/23:

- Image aren't needed in PDFs, so remove them (or have an option to exclude from PDF if not suitable for ESS)
- Font does need changing to an Adobe supported font to allow UO editing

**Comment by simonfernandes** [comment]
Might need to coordinate with @Scott-James-Hurley on https://github.com/isisbusapps/fap-booklet-generator/issues/88

**Comment by Cat-Lucifer** [comment]
@Scott-James-Hurley All of the proposal pdfs that had screwed up formatting appeared to be the ones that had deuteration images uploaded.  We don't need the images to be in the proposal pdf, so if these are removed from being embedded hopefully this solves this issue.

@deepaksftc I can edit the pdfs in Adobe pro DC, but sometimes the words become scrambled when I do this - usually words with the letter `f` in them - see first image below.  Adobe reckons it is because the font used is an unsupported Adobe font.  Is the proposal pdf font calibri?  The pdf template says the font is `Open Sans`, but this could be the same as calibri for all I know - see second image below.


![Picture1](https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/108054517/abb90847-9cb0-49c8-8673-c9e36e151f23)


![image](https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/108054517/9eff8066-094f-4363-8c53-c6468d0bf296)

**Comment by Cat-Lucifer** [comment]
Email from @deepaksftc 

![image](https://github.com/UserOfficeProject/issue-tracker/assets/108054517/a069e899-20dc-42db-aecc-396a598d0147)

**Comment by Cat-Lucifer** [comment]
> Email from @deepaksftc
> 
> ![image](https://private-user-images.githubusercontent.com/108054517/306972707-a069e899-20dc-42db-aecc-396a598d0147.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MDA1MDAsIm5iZiI6MTcwODYwMDIwMCwicGF0aCI6Ii8xMDgwNTQ1MTcvMzA2OTcyNzA3LWEwNjllODk5LTIwZGMtNDJkYi1hZWNjLTM5NmE1OThkMDE0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMlQxMTEwMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTBjYWNhMzQ5MjUzMTcxNWYzNjJkMmU4NWE3M2NlMmIxN2U0ODI5ODQzMDAyZTJkODc2MTI3OGI4NTVkNmJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jrsmMVGZ8NibkDI0DZXfajNQ511c61brZcggOzarlzg)

@deepaksftc Yes, this problem only occurs for non-default pdf templates.  There are lots of constraints with the ISIS template - @simonfernandes will be able to explain.  Thanks!

**Comment by deepaksftc** [comment]
Hi @Cat-Lucifer, I have changed the font in all the custom pdf templates, to use segoe (the font used in default pdf template). Could you please check if you are able to edit the pdfs without any issues.

**Comment by Cat-Lucifer** [comment]
@deepaksftc It's actually worse 🙁  But!  I have installed PDF-XChange editor and I can edit there all fine.  It wasn't wasted effort though, as when I tried to add and edit text using PDF-XChange editor in a pdf of the old font, all of the `f` characters disappeared, so the font did still need changing to something that Adobe recognised.  Thanks!
