### ISSUE TITLE
Add Mass Assigning of Proposals to Reviewers

### ISSUE THREAD

**Issue by Scott-James-Hurley** [UserOfficeProject/user-office-project-issue-tracker#964]
Refs: #961

Currently with the SEPs software, reviewers on a panel have to be manually assigned to proposals one-by-one. This will be painful for whoever is doing the assigning as panels can have a lot of proposal to review . We should add the ability to automatically assign reviewers to proposals, aiming for as even a distribution of proposals to reviews as possible.

**Comment by TCMeldrum** [comment]
No needed need for March

**Comment by Scott-James-Hurley** [comment]
Reopened as https://github.com/UserOfficeProject/user-office-core/pull/550 does not meet Emma's requirements.
