### ISSUE TITLE
The user experience of selecting beamline manager for a new experimental area is terrible

### ISSUE THREAD

**Issue by ACLay** [UserOfficeProject/user-office-project-issue-tracker#974]
### What is the problem and why is it a problem

The user list for beamline manager selection shown when attempting to create a new experimental area is incredibly unpleasant to use. It's 
- slow to load
- unordered
- only shows name so good luck picking correctly if multiple users have the same name
- seems to allow some level of typing to filter, but 
  - doesn't remove non-matches
  - unintuitively puts the matches at the bottom of the list
    - but sometimes it doesn't and leaves some matches at the top
  - is slow to update as you type

**Comment by ACLay** [comment]
I wonder if this is related to, and if so how much is due to #970

**Comment by Bhaswati1148** [comment]
The api `getUsers` is fetching the entire set of user's records (approx. more than 11.5k)  from [postgress database](https://github.com/UserOfficeProject/user-office-core/blob/97f28f45620dd8b959abb4c561a360e7eb411d33/apps/backend/src/datasources/stfc/StfcUserDataSource.ts#L386)
Although user role is [passed](https://github.com/UserOfficeProject/user-office-core/blob/97f28f45620dd8b959abb4c561a360e7eb411d33/apps/frontend/src/components/instrument/CreateUpdateInstrument.tsx#L41) but its never been used while querying the database.

The user numbers fetched from postgress is then used in [getStfcBasicPeopleByUserNumbers](https://github.com/UserOfficeProject/user-office-core/blob/97f28f45620dd8b959abb4c561a360e7eb411d33/apps/backend/src/datasources/stfc/StfcUserDataSource.ts#L397)
Effectively two database calls with large set of users seems to be a probable cause for slow loading of the beam line manager drop down list.

**Comment by Bhaswati1148** [comment]
`INSTRUMENT_SCIENTIST` user role is passed from front end. If this is taken into consideration while querying the postgress database, only two records are fetched as of now. This seems a little weird in production. Discussed the situation with @ACLay and @srconway. 
We need to clarify from Emma Gozzard 

- Are users with `INSTRUMENT_SCIENTIST` role only allowed in that list or should also include `USER_OFFICER`?
- Is beam line manager going to be changed frequently? if not, can this list be changed to a text field where an email can be used to choose a beamline manager?
