### ISSUE TITLE
As a Technical Reviewer I should only be able to see PI name

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/user-office-project-issue-tracker#980]
### What is the problem and why is it a problem
Feedback from FAP demo:
> Add the PI name to the Technical Review view, would aid Scientists as they would not have to resort to using reports.  Please do not show email addresses in the review stage.

### Steps to reproduce (if it's a bug).
N/A

**Comment by RasmiaKulan** [comment]
Issue update: The submission system should display the PI name and email for Experiment Scientist and Internal Reviewer, and not display the email for FAP Chair and FAP Reviewer. Although it currently does that, there is a bug where PI name and email does not appear in the Internal Reviewer Dashboard and `Proposal Information` tab
