### ISSUE TITLE
Display summary of scored proposals at reviews stage

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/user-office-project-issue-tracker#981]
### What is the problem and why is it a problem
Feedback from FAP demo:

> Chair or Secretary output shows a summary of scored proposals but only once the review stage is complete (ie at MEETINGS stage). This would be very useful to also present at the REVIEWS stage

### Steps to reproduce (if it's a bug).
N/A

**Comment by srconway** [comment]
@Cat-Lucifer Is this required for first release?

**Comment by Cat-Lucifer** [comment]
@srconway If possible please,

**Comment by Cat-Lucifer** [comment]
@RasmiaKulan From what I remember, the system doesn't highlight if all proposal external reviews are completed or not (there are usually two reviewers per proposal for ISIS).  Having this feature would make it easier for FAP Secretaries to quickly scroll down the proposal list for their FAP and easily see what is complete and what is outstanding.

I guess a red / green colour code, or reviews complete Y / N per proposal would be good.  Or something easier that can show the same info?

**Comment by srconway** [comment]
I don't know how feasible it is but a tick/cross or similar would be better than red/green from an accessibility point of view if we're adding some sort of visual indicator.

**Comment by RasmiaKulan** [comment]
@Cat-Lucifer @srconway How does the following look where the FAP Chair, FAP Secretary and FAP Reviewer can see the number of proposals reviewed out of total number of proposals to review.
![image](https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/69144386/55a6c87c-9b3b-4ab7-9fa1-e8cb154a8ae3)

**Comment by Cat-Lucifer** [comment]
@RasmiaKulan This looks good to me!  Thanks 🙂

**Comment by srconway** [comment]
Thanks @RasmiaKulan yes that looks great :)
