### ISSUE TITLE
Show number of proposals assigned to a member within the current round

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/user-office-project-issue-tracker#982]
### What is the problem and why is it a problem
In the MEMBERS tab, only the global count for assigned proposals is shown, there is no way to show number of proposals assigned to a member within the current round

![image](https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/81559866/6a534746-1e53-4772-9b8a-bcccc5c42643)

### Steps to reproduce (if it's a bug).
N/A

**Comment by srconway** [comment]
Only an issue in subsequent rounds
