### ISSUE TITLE
Update STFC reviews Export

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/user-office-project-issue-tracker#988]
Discuss with Emma, then update the STFC reviews export from the FAP meeting page

**Comment by srconway** [comment]
Need to confirm exactly what's required - is it the content of the current meeting spreadsheet?

**Comment by srconway** [comment]
@Cat-Lucifer Can you confirm exactly what you need in this export for the meetings?

**Comment by Cat-Lucifer** [comment]
Email from @TCMeldrum 

![image](https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/108054517/71cb6ef6-5e43-4430-b6f8-a792665504a8)

**Comment by Cat-Lucifer** [comment]
> Email from @TCMeldrum
> 
> ![image](https://private-user-images.githubusercontent.com/108054517/300827547-71cb6ef6-5e43-4430-b6f8-a792665504a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MjI1NTgsIm5iZiI6MTcwNjYyMjI1OCwicGF0aCI6Ii8xMDgwNTQ1MTcvMzAwODI3NTQ3LTcxY2I2ZWY2LTVlNDMtNDQzMC1iNmY4LWE3OTI2NjU1MDRhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQxMzQ0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2VjZWE2NzNlNjA1MTMwZDM5ODZkNzkzZmQ0MjhlMzFhMmNhOTI0ZDlkMzNhZTdmMWU5Njg5MjljMTNlMzJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dBDViAr44EYUvpXNde2lPQAwtCUjBwmzRcgI-Qbn8NU)

@TCMeldrum Is this the exported excel sheet at the end of the reviews process?  If so, data to exclude at this point (may be different when the meeting functionality kicks in):
`Instrument Available Time`
`FAP Allocated Time`
`Feedback`
I can guess, but I don't know what `Is in Availability Zone` is

It would be good to have `Requested Time`

I think, the ideal export after the reviews stage (but before the meeting stage) would be:
`Proposal Reference Number`
`Principal Investigator`
`PI Country`
`Instrument Name`
`Requested Time`
`Proposal Title`
`Reviewer 1 score`
`Reviewer 1 review comment`
`Reviewer 2 score`
`Reviewer 2 review comment`
`Average score`

**Comment by TCMeldrum** [comment]
@Cat-Lucifer 
The export can happen at anytime during the process, just some of the information might be missing, but I assume for this round at least the export is happening so you can run the meeting with the old spreadsheets tool. With this being the case, I want to tailor the export for the current round and update the export for when we use the meeting component when we need to. 

I think all the columns you have requested should be possible 👍

**Comment by TCMeldrum** [comment]
@Cat-Lucifer just looking into it the only one that might be hard is `PI Country`, how important is this one?

**Comment by Cat-Lucifer** [comment]
@TCMeldrum It is very important, but I'm happy for it to not hold things up for this round if it is less straightforward, as long as we can have it for the next round (September 2024).
